### PR TITLE
FAQ: Extend Gateway explanation for #551

### PR DESCRIPTION
**Pull request by MikeMcC399**
Add link to EU FAQs https://ec.europa.eu/commission/presscorner/detail/en/qanda_20_1905#gateway and explain where to find participating countries in the app.

Previously discussed with @heinezen in https://github.com/corona-warn-app/cwa-website/issues/551

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Sorry. I don't think I did this correctly. I'm a github beginner unfortunately. 

The useful changes are in:
https://github.com/corona-warn-app/cwa-website/pull/553/commits/99679e42aea350020ca04dc4810aaa430b369ccb and
https://github.com/corona-warn-app/cwa-website/pull/553/commits/af7d8bc72dbb9a82ad67daafbe3192f727018bf0

**Comment by MikeMcC399** [comment]
Closing as it didn't look right!

**Comment by heinezen** [comment]
If you want to get the latest changes from `master`, you should do a rebase. This is usually

```
git rebase upstream/master
```

or available in your favorite git client.

**Comment by MikeMcC399** [comment]
@heinezen 
> If you want to get the latest changes from master, you should do a rebase. 
Thank you for this missing bit of information. I will go through git / github training now, so I have some chance of knowing what I am doing in future. 😀

**Pull request closed without merging**
