### PR TITLE
Fix FAQ #tan-procedure formatting issues

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3221 "Missing bullet character in FAQ #tan_procedure" by adding a missing `<li>` tag near the end of the article.

In addition `\n` (new line) instances in the source of the FAQ article are converted to `<br>` (HTML break). Presumably the intention of the original FAQ author @larswmh in PR https://github.com/corona-warn-app/cwa-website/pull/3060 was to show a new line at these points for readability, however `\n` does not do this in an HTML context.

---
https://www.coronawarn.app/en/faq/results/#tan_procedure "TAN Procedure" (EN)

tan-procedure_fixed_EN

---
https://www.coronawarn.app/de/faq/results/#tan_procedure "TAN-Verfahren" (DE)
 
tan-procedure_fixed_DE

### CODE REVIEW

**Review by GisoSchroederSAP — APPROVED** [review]
Yes, please, go ahead to polish the HTML code.
Thanks in advance!

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 

> Yes, please, go ahead to polish the HTML code.
Thanks in advance!

Thank you for the encouragement! I will continue. 

In the case of this PR the errors had a visible effect. 

There are errors that I am correcting in other PRs which don't make a difference in Google Chrome. It seems the browser is quite forgiving of many HTML errors, however if the HTML is wrong there is no guarantee that other browsers and mobile devices will still display the contents as desired.

**Comment by MikeMcC399** [comment]
@brianebeling 

This is a cosmetic change only and it was already approved by @GisoSchroederSAP.

Would you like to merge it?

**Comment by brianebeling** [comment]
> Brian-J. Ebeling
> 
> This is a cosmetic change only and it was already approved by @GisoSchroederSAP.
> 
> Would you like to merge it?

Yes, absolutely. Thank you for your patience. I try to sincerely take my time with every PR, unfortunately I was unable to merge older ones recently.

**Pull request merged**
