### PR TITLE
iOS Screenshots for Version: 2.2.0

### PR DESCRIPTION
**Pull request by Corona-Warn-App-Technical-User**
iOS Screenshots for Version: 2.2.0

### CODE REVIEW

**Review by Ein-Tim — CHANGES_REQUESTED** [review]
1. The "Test registrieren & andere Warnen" section is outdated, the screens have been redesigned & the text has changed in version 2.1. 
2. The version (2.1 shown currently) needs to be bumped to 2.2

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Checking.

**Comment by dsarkar** [comment]
image
@Ein-Tim that one looks to me like the new ones. Fine, no?

**Comment by dsarkar** [comment]
R 2.2 screenshots 
image

R 2.1 screenshots 
image

LGMT ...

**Comment by dsarkar** [comment]
[ios-de.pdf](https://github.com/corona-warn-app/cwa-website/files/6435415/ios-de.pdf)

**Comment by Ein-Tim** [comment]
@dsarkar 

True! Sorry, I didn't mean outdated but that there are duplicates and other strange things. 

### Section: "Contact Journal" 

- [ ] Remove onboarding images (aren't shown for Event-Registration feature)

### Section "Check In"

- [ ] Rename German section to "Check-in" to match app text

### Section: "Test registration & Key sharing" 

- [ ] Remove image 4
- [ ] Remove image 7
- [ ] Move image 10 to first place
- [ ] Remove image 11
- [ ] Add an image showing an positive test

### Section: "Test result home" 

- [ ] Fix all images showing the same

### Section: "Rapid antigen test" 

- [ ] Remove Android screenshots
- [ ] Replace image 7 with current implementation


If you want I can open a new issue for this.

**Comment by dsarkar** [comment]
@Ein-Tim OK, thanks for detailed list! 
image

**Comment by dsarkar** [comment]
@Ein-Tim I am editing your post, hope you don't mind.

**Comment by Ein-Tim** [comment]
@dsarkar 

Not at all!

**Comment by Ein-Tim** [comment]
Can this branch be deleted, please? 
It's bit confusing if we have more than one screenshots branch for each OS at the same time.

Thank you!

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.

**Pull request merged**
