### PR TITLE
Fix infinite loop of FAQ url

### LINKED ISSUE #2837: Infinite loop using bookmarked search (414 Request-URI Too Large)
## Where to find the issue

https://www.coronawarn.app/de/faq/?search=luca#check_in_luca (quoted in auto-reply to the e-mail address [CoronaWarnApp@rki.de](mailto:CoronaWarnApp@rki.de)).

## Describe the issue

When using the bookmarked link https://www.coronawarn.app/de/faq/?search=luca#check_in_luca the web goes into an infinite loop, displays no results and the URL shown in the address bar contains multiple instances of the string `/results`, for instance:

https://www.coronawarn.app/de/faq/?search=lucaresults/results/results/results/results/results/results/results/results/results/results/results/results/results/results/results/#check_in_luca (interrupted)

## Steps to reproduce

In Google Chrome paste https://www.coronawarn.app/de/faq/?search=luca#check_in_luca into address bar and press enter

After waiting some time as the URL gets longer and longer, it finally fails with the error message:

`414 Request-URI Too Large`

## Expected behaviour

1. No infinite loop
2. Adherence to https://github.com/corona-warn-app/cwa-website/blob/master/docs/FAQ_SEARCH_SUMMARY.md#url-parameters<br><br>"_If, in addition to the search parameter, a hash (e.g., #ios_136) is part of the url to address one entry directly, the search parameter is ignored._"<br><br>thus the URL https://www.coronawarn.app/de/faq/?search=luca#check_in_luca should be resolved to https://www.coronawarn.app/de/faq/#check_in_luca and this in turn to https://www.coronawarn.app/de/faq/results/#check_in_luca

### PR DESCRIPTION
**Pull request by larswmh**
Fixes #2837 

Thanks to @ibexad for providing this fix!

### CODE REVIEW

**Review by MikeMcC399 — APPROVED** [review]
This now resolves the issue and fulfils the expectations listed in #2837. 👍🏻

**Comment by MikeMcC399** [comment]
@dsarkar 

The deployment issues seemed to have been fixed, so perhaps this PR could come out of draft state and be merged now?

**Comment by larswmh** [comment]
> The deployment issues seemed to have been fixed, so perhaps this PR could come out of draft state and be merged now?

@MikeMcC399 unfortunately the deployment issues have not been fixed, as the automatic scheduled deployments are still failing. We're actively working on a solution for this and will merge the draft pull requests once we can assure that it will not cause any further issues.

**Comment by MikeMcC399** [comment]
@larswmh 

> unfortunately the deployment issues have not been fixed, as the automatic scheduled deployments are still failing. We're actively working on a solution for this and will merge the draft pull requests once we can assure that it will not cause any further issues.

Is there any estimate about how long it will take to fix the deployment problem (see also https://github.com/corona-warn-app/cwa-website/issues/2861)?

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 ok, thanks

**Comment by MikeMcC399** [comment]
This fix now works correctly in production. There were general problems with the mime-type setting of https://www.coronawarn.app/assets/js/app.js. This has been resolved and the file now serves with ContentType: `text/javascript`.

**Pull request merged**
