### PR TITLE
added files for new science blog

### PR DESCRIPTION
**Pull request by HannaHei**

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@HannaHei / @dsarkar 
Is the some reason there was no link in the text "They can be accessed under the "Analysis" tab ..." to the actual Analysis tab on https://www.coronawarn.app/en/analysis/?

Would it make sense to add the link now?

**Comment by dsarkar** [comment]
@MikeMcC399 Nice suggestion. Will you offer a PR (I will merge) or shall we fix that one? Thanks!

**Comment by MikeMcC399** [comment]
@dsarkar 
@HannaHei has fixed this with PR https://github.com/corona-warn-app/cwa-website/pull/1809, which is already merged, so I have no further questions 🙂 !

**Comment by dsarkar** [comment]
@MikeMcC399 Alright, thanks!

**Pull request merged**
