### PR TITLE
Add Visual Studio Code json Workspace Settings for editing

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR implements the suggestion from issue https://github.com/corona-warn-app/cwa-website/issues/1724 "Missing json file settings for Visual Studio Code editor" by providing Workspace Settings for editing and saving `JSON` files in the [corona-warn-app/cwa-website](https://github.com/corona-warn-app/cwa-website) repository with the Visual Studio Code editor.

- It supports the recommendation from [CHANGE_WEBSITE_CONTENT.md](https://github.com/corona-warn-app/cwa-website/blob/master/docs/CHANGE_WEBSITE_CONTENT.md) which says "JSON files use 4 space-character soft-tab indentation" by providing the corresponding settings during editing.
- It also trims trailing white space and ensures that exactly one final newline is present in the file when saving.

## Settings with comments

These settings are applied only when editing JSON files with the Visual Studio Code editor.

See also Visual Studio Code - Reference information - [User and Workspace Settings](https://code.visualstudio.com/docs/getstarted/settings).

// Controls whether `editor.tabSize#` and `#editor.insertSpaces` will be automatically detected when a file is opened based on the file contents.

`"editor.detectIndentation": false`

// The number of spaces a tab is equal to. This setting is overridden based on the file contents when `editor.detectIndentation` is on.

`"editor.tabSize": 4`

// Insert spaces when pressing `Tab`. This setting is overridden based on the file contents when `editor.detectIndentation` is on.

`"editor.insertSpaces": true`

// Remove trailing auto inserted whitespace.

`"editor.trimAutoWhitespace": true`

// When enabled, will trim trailing whitespace when saving a file.

`"files.trimTrailingWhitespace": true`

// When enabled, insert a final new line at the end of the file when saving it

`"files.insertFinalNewline": true`

// When enabled, will trim all new lines after the final new line at the end of the file when saving it.

`"files.trimFinalNewlines": true`

## Effect of format document

In Visual Studio Code for Windows the key combination `Shift+Alt+F` formats a document. (See [Keybindings](https://code.visualstudio.com/docs/getstarted/keybindings) for other operating systems.)

Apply Format document (`Shift+Alt+F`) to the current [faq.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq.json) / [faq_de.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq_de.json) documents has no effect, since these documents are already formatted according to the convention specified.

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Works fantastic! Same key binding for Mac OS X. Thank you!

**Comment by Marcono1234** [comment]
This is restricted to VSCode though now...
At least a reference to #1684 would have been nice. There you yourself even voiced the concern that such support should not be VSCode specific (see https://github.com/corona-warn-app/cwa-website/pull/1684#issuecomment-908070570).

I did not even get any feedback on the suggestion to add only such formatter configuration (without formatting the files yet) from any of you 😒

**Comment by Ein-Tim** [comment]
@Marcono1234 

> I did not even get any feedback on the suggestion to add only such formatter configuration (without formatting the files yet) from any of you 😒

Do you mean your comment https://github.com/corona-warn-app/cwa-website/pull/1684#issuecomment-910837570, which was left unanswered? 
Is this PR basically implementing what you suggested there?
I just want to understand it, sorry for these questions 😅

**Comment by Marcono1234** [comment]
> sorry for these questions 😅

No problem. Yes my suggestion was to reduce my pull request (or create a new pull request) to only add a Prettier config and the VSCode settings to use Prettier as formatter for JSON files.
I am not sure whether or not Prettier would have been a better choice, but it would have at least been nice to discuss this after I proposed it there.

I guess the end situation is now the same, that there is a JSON formatting config specified, but the communication was in my opinion not ideal. Though don't worry too much about this.

**Comment by MikeMcC399** [comment]
@Marcono1234 
Thanks for your feedback. I should have linked your PR #1684 into the issue #1724 to provide the train of thought which sparked this PR. Sorry for that!

**Pull request merged**
