### PR TITLE
replace cwa-datenschutz-folgenabschaetzung

### PR DESCRIPTION
**Pull request by dsarkar**
Version 1.1 is replaced by Version 1.5

filenames were changed:

1. cwa-datenschutz-folgenabschaetzung.pdf  ==> cwa-datenschutz-folgenabschaetzung (Version 1.1 2020-10-16 replaced by Version 1.5 2021-01-08).pdf
2. and then new file (Version 1.5 from 8.1.2021) renamed to cwa-datenschutz-folgenabschaetzung.pdf

[EXPOSUREAPP-4834](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4834)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
There is a cross-reference error in the document on page 49:

Seite 49
(siehe Abschnitt Fehler! Verweisquelle konnte nicht gefunden werden.).

**Comment by MikeMcC399** [comment]
I noticed two minor inaccuracies in the document:

Seite 17
---

"Mit dem Release der CWA App Version 1.10 wird mit dem Kontakt-Tagebuch eine neue nutzergerichtete Funktion eingeführt werden. **Zudem wird die Statistik-Kachel eingeführt.** Diese dient zur Anzeige von aktuellen Statistiken zum Infektionsgeschehen und zur Nutzung der CWA App (siehe Abschnitt 5.4.6)."

- Statistics are not planned to be released until version 1.11 (see https://www.coronawarn.app/en/blog/2021-01-25-corona-warn-app-version-1-11-teaser/)


Seite 22
---
"Der Risikostatus wird einer der folgenden Stufen zugeordnet:

(1) **Unbekanntes Risiko**
(2) Niedriges Risiko
(3) Erhöhtes Risiko"


- The Status Unknown Risk / Unbekanntes Risiko is not used from app version 1.8 onwards (see https://github.com/corona-warn-app/cwa-website/issues/802)

**Comment by dsarkar** [comment]
@MikeMcC399 Many thanks! We will clarify internally!

**Comment by dsarkar** [comment]
[EXPOSUREAPP-4834](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4834)

**Comment by MikeMcC399** [comment]
@dsarkar 
If getting feedback (and perhaps an updated document) introduces a long delay, I would publish the existing document. There is a lot of good new information in the document and the points I raised are only minor.

Perhaps the document owner needs to decide about publishing? This is just my opinion.

**Comment by dsarkar** [comment]
@MikeMcC399 I got feedback: First of all, they have been expressing their gratitude for the wonderful help/support/contribution from the community. Secondly, this has been forwarded to be checked in legal terms by the corresponding entity.

**Comment by MikeMcC399** [comment]
@dsarkar 
It's nice to know that the community is appreciated! Thanks for handling the feedback!

**Comment by MikeMcC399** [comment]
@dsarkar 
What has happened to this document update? It is now 5 months out-of-date.

The published document [Bericht zur Datenschutz-Folgenabschätzung für die Corona-Warn-App der Bundesrepublik Deutschland Öffentliche Version](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf) is showing **Version 1.1, 16.10.2020** and it covers the app version only up to V1.5. 

CWA V1.5 was [published on October 19, 2020](https://www.coronawarn.app/en/blog/2020-10-19-version-1-5/) whilst the current version CWA 1.14 was [published on March 9, 2021](https://www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-14/).

**Comment by Ein-Tim** [comment]
@dsarkar 

Is this PR now obsolete with #1025?

**Comment by dsarkar** [comment]
@Ein-Tim Yes this one is obsolete, thanks.

**Comment by dsarkar** [comment]
@MikeMcC399 Your findings have been corrected in the new document. Thanks again, also many thanks from "behind the scenes"!

**Comment by MikeMcC399** [comment]
@dsarkar 
> Your findings have been corrected in the new document. Thanks again, also many thanks from "behind the scenes"!

Thank you. I will take a look at the new document.

**Pull request closed without merging**
