### PR TITLE
Test updates event registration

### PR DESCRIPTION
**Pull request by chrisenitan**
**Why**
Thought for start I'd add a test for the event registration page to the cypress suite. I proposed some changes to selectors and environment requirement that may need review. 

**Whats new**
1. New test folder structure: `/pages` for all page specific tests, `/fixtures/selectors` to contain all selector json files definitions
2. Sample test file: `eventRegistration.js`
3. Ignore app error in tests: Do not fail tests if main app has uncaught errors.`index.js` file in `/support`
4. updates cy to 7.6.0: Latest version update to Cypress as at time of writing.

@MikeMcC399 

Screenshot 2021-07-04 at 15 02 47

---
Internal Tracking ID: [EXPOSUREAPP-8242](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8242)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@chrisenitan 
I would be happy to see the event registration page checked by cypress, however there are some related considerations:

There hasn't been any response from the Open Source Team so far regarding general cypress issues and a specific one:
- https://github.com/corona-warn-app/cwa-website/issues/1282 and
- https://github.com/corona-warn-app/cwa-website/issues/1322

It would be good to hear some reaction from the owners before proceeding here further.

Your PR changes  `lockfileVersion` from 1 to 2, which introduces major differences in package-lock.json. We had a discussion about this after I hit the issue myelf, see https://github.com/corona-warn-app/cwa-website/issues/763, which resulted in https://github.com/corona-warn-app/cwa-website/blob/master/README.md#requirements recommending to use the LTS version of npm rather than the latest version.

**Comment by dsarkar** [comment]
@chrisenitan @MikeMcC399 Thanks.

Internal Tracking ID: [EXPOSUREAPP-8242](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8242)
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar Would you like to allow the CI to run over the code? Maybe it finds something (;

**Comment by chrisenitan** [comment]
Yes I agree we can standardise the test routine, I was worried about breaking changes as well and I'd be happy to hear any update from the owners on that. 

For the second issue on #1322 , I was unaware of the scope required for Cypress tests so I opted to listen and prevent test failure from uncaught exceptions. Also bothers on the teams decision there. 

If its required I update the the package-lock to `lockfileVersion` 1 and would be happy to get your replies. 
@MikeMcC399

**Comment by MikeMcC399** [comment]
@chrisenitan 
I'm not the owner of the cypress tests, nor a cypress expert, so I have to let others respond to the remaining points of your PR. I just commented on the points which I knew about.

**Comment by heinezen** [comment]
@Ein-Tim I have approved CI runs. Should be no problem now.

----
Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
Thanks, I have created a separate branch in the CWA repository for review first.

**Pull request merged**
