### PR TITLE
Event multi QR code generator

### PR DESCRIPTION
**Pull request by svengabr**
Continue of
https://github.com/corona-warn-app/cwa-website/pull/1698

---
Internal Tracking ID: [EXPOSUREAPP-8495](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8495)

### CODE REVIEW

**Comment by svengabr** [comment]
Resolved merge conflicts but I can still see one JS issue with the tab not being active after clicking on it. @brifemu

**Review by dsarkar — APPROVED** [review]

**Comment by Ein-Tim** [comment]
@svengabr @dsarkar @brifemu 

FYI: Twitter user is telling me that this change broke the QR-Code generator on Safari. Can you cross check? I'm not at home so I can't help out with the console output or confirm the problem. 

The environment of the user is: 

- Big Sur 11.2.3
- Safari 14.0.3

Twitter link: https://twitter.com/schnittmarke/status/1433813874738860047?s=21

**Comment by Ein-Tim** [comment]
@svengabr @dsarkar @brifemu 

FYI: #1703

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for creating an issue. We look at this.

**Pull request merged**
