### PR TITLE
added files for 2.23 blog post

### PR DESCRIPTION
**Pull request by HannaHei**

### CODE REVIEW

**Comment by MikeMcC399** [comment]
According to https://www.coronawarn.app/en/faq/results/#glossary_validity the terms in English are:

- technical validity and
- effective validity

The blog however uses the term "technological validity" and "professional validity" which is inconsistent.

**Comment by MikeMcC399** [comment]
@HannaHei / @dsarkar 

Will you address the issues I raised in this PR or do you want new issues submitted to document them?

**Comment by dsarkar** [comment]
@MikeMcC399 let me ping @HannaHei first.

**Comment by MikeMcC399** [comment]
- https://github.com/corona-warn-app/cwa-website/pull/2933 addresses the issue raised in https://github.com/corona-warn-app/cwa-website/pull/2925#issuecomment-1143807169 concerning the English-language validity terms used.

**Comment by MikeMcC399** [comment]
The title of the blog
"Extension of technologically expired certificates in the CWA"

still uses the term "technologically" instead of "technically" 🙁

**Comment by MikeMcC399** [comment]
- To follow up the issue using regular processes I submitted https://github.com/corona-warn-app/cwa-website/issues/2938

- @HannaHei has not explicitly replied here, however the text problems regarding validity terms have been resolved through two PRs she submitted, so there is no need for a new issue on this topic.

**Pull request merged**
