### PR TITLE
Update FAQ entries `minimum_requirements` & `ios135`

### LINKED ISSUE #737: FAQ entries (`minimum_requirements` & `#ios135`) are outdated
## Where to find the issue
https://www.coronawarn.app/en/faq/#minimum_requirements & https://www.coronawarn.app/en/faq/#ios135
https://www.coronawarn.app/de/faq/#minimum_requirements & https://www.coronawarn.app/de/faq/#ios135

## Describe the issue
English `minimum_requirements` entry is contradictory in itself:
>The Exposure Notification API was introduced with iOS 13.5, so your operating system needs to be iOS 13.7 or higher.

This entry also needs to be update so that it says that iOS 13.7 or higher is necessary.

German `minimum_requirements` entry says that the ENF was introduced with iOS 13.7, what is not true: 
>Die Version des Betriebssystems muss iOS 13.7 oder höher sein, da mit dieser Version die Exposure Notification API eingeführt wurde.

---

`#ios135` says that iOS 13.6 or higher is required, it needs to be update so that it says that iOS 13.7 or higher is required.

(Source for iOS 13.7: https://apps.apple.com/de/app/corona-warn-app/id1512595757)

---
Internal Tracking ID: [EXPOSUREAPP-4479](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4479) (RKI)
Internal Tracking ID: EXPOSUREAPP-4481 (Bundesregierung)

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR updates the English and German FAQ entries `minimum_requirements` and `ios135`.

<details>
<summary>Screenshots of the changes</summary>

`ios135`:

German-ios135

English-ios135

`minimum_requirements`:

German-minimum_requirements

English-minimum_requirements

Please note that the links are not shown in these screenshots.
</details>

Please make sure I've done the links right 😅👍

---
Closes #737

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
LGTM

**Comment by dsarkar** [comment]
Thanks @Ein-Tim

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The texts for the website looks good to me.

Just one very minor point for the title of the PR: the plural of "entry" is "entries" if you want to correct that, even though it is only seen internally.

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Thanks !

**Pull request merged**
