### PR TITLE
finland faq correct date

### PR DESCRIPTION
**Pull request by dsarkar**

### CODE REVIEW

**Comment by dsarkar** [comment]
07.01.2020 ==> 08.01.2020

**Comment by MikeMcC399** [comment]
@dsarkar 
In https://www.coronawarn.app/en/faq/#interoperability_countries it does not explain what the date against each country means.

Is it supposed to be the date:
- when the country starts feeding into the European Federation Gateway Service (EFGS) or
- when the German server starts pulling that country's data from the EFGS into the German infrastructure?

I ask because although the Finnland date is to be changed to 08.01.2021, the country is not listed in the app. The last country to join the list in the app is Belgium.

Also, if you are going to republish the list, then the status date "06.01.2021" should updated to the date of publishing.

**Comment by dsarkar** [comment]
@MikeMcC399 

> Is it supposed to be the date:
> 
> when the country starts feeding into the European Federation Gateway Service (EFGS) or
> when the German server starts pulling that country's data from the EFGS into the German infrastructure?
> 

Will check!

**Review by mtb77 — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@dsarkar 
Finland is still not showing in the (Android) app.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Checked, same on iPhone. Will forward info right now! Thanks.

**Comment by dsarkar** [comment]
@MikeMcC399 regarding the date, the answer is (a) when feeding starts.

**Comment by dsarkar** [comment]
@MikeMcC399 regarding https://github.com/corona-warn-app/cwa-website/pull/764#issuecomment-757683864 Finland not showing up: German servers will be configured today to pull Finland.

**Pull request merged**
