### PR TITLE
fixed decimals in analysis

### PR DESCRIPTION
**Pull request by browkin**
**Old Charts:**
oldDE
oldEN

**New Charts:**
newDE
newEN

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Review by MikeMcC399 — APPROVED** [review]
@browkin 

Thank you for fixing this!

I compared some numbers of old and new displays. The averages are rounded (not truncated) which is what I would hope for.

It looks good to merge from my side.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the review (and suggestion). Looks better now.

**Comment by dsarkar** [comment]
@HelTob FYI

**Comment by MikeMcC399** [comment]
This PR was to resolve issue #2150.

**Pull request merged**
