### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by hschepp1965**
added files for the new blog post virus variants

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@hschepp1965 
That was too fast to comment before the change was merged.

Suggestions:

- Consistently write "Corona-Warn-App" exactly that way (not "Corona Warn App" or "Corona warning app").

- Write the correct name for IIS: "The Fraunhofer Institute for Integrated Circuits IIS" see https://www.iis.fraunhofer.de/en/imprint.html in English not "Fraunhofer für Integrierte Schaltungen"

- Insert link to Twitter channel https://twitter.com/coronawarnapp, not just "@coronawarnapp" or "Twitter".

**Comment by Ein-Tim** [comment]
@MikeMcC399 I also noted this with Twitter and thought about providing a PR for it, but now I'll wait for feedback, would make more sense to have this all done in one PR. 👍

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I've opened https://github.com/corona-warn-app/cwa-website/issues/1469, so please feel free to check and comment there.

I would expect @hschepp1965 to make any changes, but if there is any problem with that, then you or I could submit a PR.

**Comment by hschepp1965** [comment]
On it!

Von: Mike McCready ***@***.***>
Datum: Donnerstag, 8. Juli 2021 um 14:07
An: corona-warn-app/cwa-website ***@***.***>
Cc: Schepp, Hilmar ***@***.***>, Mention ***@***.***>
Betreff: Re: [corona-warn-app/cwa-website] Add files via upload (#1466)

@Ein-Tim<https://github.com/Ein-Tim>
I've opened #1469<https://github.com/corona-warn-app/cwa-website/issues/1469>, so please feel free to check and comment there.

I would expect @hschepp1965<https://github.com/hschepp1965> to make any changes, but if there is any problem with that, then you or I could submit a PR.

**Pull request merged**
