### PR TITLE
Add Apple and Instagram links to the allow list to Cypress check_links.js test

### PR DESCRIPTION
**Pull request by brifemu**
Due to issue #2969, I had included like @MikeMcC399 suggested some Apple links and Instagram's profile URL to the existent allow list to avoid the error explained on the issue.

---
Internal Tracking ID: [EXPOSUREAPP-13420](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13420)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
There is a problem with a blog link. I will report this first and then return here. At this time, the test does not pass.

**Comment by MikeMcC399** [comment]
- Issue https://github.com/corona-warn-app/cwa-website/issues/2976 currently prevents this PR from passing the Cypress test.

**Comment by MikeMcC399** [comment]
- Issue #2976 is now resolved.

**Comment by MikeMcC399** [comment]
## Production test

`npx cypress run -s cypress/integration/hybrid/check_links.js -c baseUrl=https://coronawarn.app` - pass

## Local test

`npx cypress run -s cypress/integration/hybrid/check_links.js` against a local server started with `npm start` - pass 

## Full test

`npm test` - pass

**Review by MikeMcC399 — APPROVED** [review]
The test passes, so this PR can be merged.

It should improve the reliability of the test in future, although because of the dependence on external website functioning it may still experience sporadic failures.

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for your proposal and reviewing! Enjoy your evening!

**Pull request merged**
