### PR TITLE
Add link to blog post (Closes #850)

### LINKED ISSUE #850: [CWA v1.12] Add small FAQ entry explaining the contact journal
## Suggested Enhancement 

As discussed in https://github.com/corona-warn-app/cwa-app-ios/issues/1936, it would make sense to have a small FAQ entry (based on the [Blog](https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/)) which explains how to delete/edit entries.

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR adds a link to the [blog post](https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/) reg. the (use of the) contact diary to the FAQ entry https://www.coronawarn.app/en/faq/#contact_diary.

---

Closes #850 

<details>
<summary>Screenshots of the changes</summary>

German: 
image

English:
image

</details>

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@Ein-Tim LGTM, thanks! Good night!

**Comment by Ein-Tim** [comment]
Thanks @dsarkar, have a good night too.

**Comment by Ein-Tim** [comment]
I used 

`<a href='https://www.coronawarn.app/de/blog/2020-12-28-corona-warn-app-version-1-10/' target='_blank' rel='noopener noreferrer'`
` 
and

`<a href='https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/' target='_blank' rel='noopener noreferrer' `


instead of 

`<a href='..blog/2020-12-28-corona-warn-app-version-1-10/' target='_blank' rel='noopener noreferrer'` 

The user will not see any difference, this is only noticeable when building the page locally. 

I will open a PR which corrects this tomorrow, as soon as I can.

**Comment by dsarkar** [comment]
Good morning @Ein-Tim. I suggest to change in one of the next PRs. As you wish.

**Pull request merged**
