### PR TITLE
FAQ - update 'risk_update_24' entry for #971

### PR DESCRIPTION
**Pull request by heinezen**
Changelog:
- "Zero-Rating Verpflichtungen" needed additional dash

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Do we want to link to https://www.coronawarn.app/de/faq/#mobile_data_costs from this entry? 
I think this would be quite sensefull.

I can also open a new issue for that afterwards. (:

**Comment by heinezen** [comment]
@Ein-Tim I think it's a good idea. We are still discussing internally how much interlinking between entries we want, but it would be no problem here, I think.

We will leave the batch of FAQ edits open for feedback anyway, so no need to create an issue for it yet.

**Comment by heinezen** [comment]
@Ein-Tim Solved!

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@Ein-Tim @heinezen Thanks.

**Comment by dsarkar** [comment]
image

**Comment by dsarkar** [comment]
image

**Pull request merged**
