### PR TITLE
Fix responsive graph in Analysis

### PR DESCRIPTION
**Pull request by brifemu**
Due to issue #2321 I have created this PR. After several tries, I finally get to resolve this issue.

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@brifemu 

This is a big improvement. 👍🏻 

There are still however some issues. In Google Chrome with the browser window full height and 1/3 screen width:
1. Open http://localhost:8000/en/analysis/
2. Scroll down to Downloads
3. Click full-screen icon
4. Graph fills window and displays correctly. There is no vertical scroll-bar.
5. Drag bottom of window upwards to resize to smaller height.
6. The graph does not resize.
7. Click full-screen icon twice to recover.

If the browser window is resized when the display is in full-screen mode the graph should be redrawn.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for checking, we will have look at your comments.

**Comment by brifemu** [comment]
@MikeMcC399 
Thank you so much for your comment! This happens because with that width gets smartphone breakpoint. That breakpoint uses `fullscreen.js` and desktop uses `expand.js`. I will implement the same resize functionality in another PR soon.

**Comment by MikeMcC399** [comment]
@brifemu 

> This happens because with that width gets smartphone breakpoint. That breakpoint uses `fullscreen.js` and desktop uses `expand.js`. I will implement the same resize functionality in another PR soon.

Thank you for the explanation! With Windows 11 I make a lot of use of the built-in templates for window resizing, which are quite neat. If you haven't seen them, they look like this:

image

**Pull request merged**
