### PR TITLE
Update FAQ #rat_red_card_which_test & #red_card_how_to_test

### LINKED ISSUE #2965: Wrong action advised after red tile (PCR test) in FAQs
## Where to find the issue

- https://www.coronawarn.app/en/faq/results/#rat_red_card_which_test "If I see a high-risk encounter in the App, i.e. a red card, should I do a rapid antigen test or PCR-Test?"

red action EN

- https://www.coronawarn.app/de/faq/results/#rat_red_card_which_test "Wenn ich eine hohe Risiko-Begegnung in der App angezeigt bekomme, d. h. eine rote Karte/Kachel, sollte ich dann einen Schnelltest oder PCR-Test machen?"

---
- https://www.coronawarn.app/en/faq/results/#red_card_how_to_test "Red Card? How to go through Corona testing"

red action 2 EN

- https://www.coronawarn.app/de/faq/results/#red_card_how_to_test "Rote Karte? So geht es zum Corona Test"

---
- https://www.coronawarn.app/en/faq/results/#check_in_qr_warning_share "Can this information be voluntarily communicated to the health authority? If so, what information is flowing?"

image

- https://www.coronawarn.app/de/faq/results/#check_in_qr_warning_share "Können diese Informationen freiwillig dem Gesundheitsamt mitgeteilt werden? Wenn ja, welche Informationen fließen?"

---
- https://www.coronawarn.app/en/faq/results/#in_a_nutshell "In a nutshell"

image

- https://www.coronawarn.app/de/faq/results/#in_a_nutshell "Kurzgefasst"

## Describe the issue

Several FAQ articles give advice about what to do after receiving a red tile "Increased Risk" in the app. Some articles (see above) recommend a PCR test.

These articles are in conflict with information posted by the Bundesministerium für Gesundheit. [RKI: Nationale Teststrategie SARS-CoV-2](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Teststrategie/Nat-Teststrat.html) links to [BMG: Fragen und Antworten zu COVID-19 Tests](https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html), including https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html#c23925

image

The regulation [TestV](https://www.gesetze-im-internet.de/coronatestv_2021-10/)<br>"Verordnung zum Anspruch auf Testung in Bezug auf einen direkten Erregernachweis des Coronavirus SARS-CoV-2 (Coronavirus-Testverordnung - TestV)" is now changed and extended in time by the [Dritte Verordnung zur Änderung der Coronavirus-Testverordnung Vom 29. Juni 2022](https://www.bundesanzeiger.de/pub/publication/oLkvcL7aBEpNfC03aH7/content/oLkvcL7aBEpNfC03aH7/BAnz%20AT%2029.06.2022%20V1.pdf?inline). 

## Suggested change

Align the FAQs with the information on  [BMG: Fragen und Antworten zu COVID-19 Tests](https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html). Do not recommend a PCR test unless the user has symptoms, in which case the user should contact a doctor. With no symptoms the user should get a Rapid Antigen Test carried out.

## Additional information

The blog https://www.coronawarn.app/en/blog/2021-12-15-cwa-red-tile-guidance/ from Dec 2021 also covers this subject. Blog articles are however not updated and the information accuracy diminishes over time. It should be considered whether this blog article be revised and reissued.

## Related RKI instructions

The [RKI CWA website](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html) is outdated concerning actions following a red tile (last updated on /  Stand: 06.05.2022). RKI acknowledged the issue on July 1, 2022. This is however out-of-scope for GitHub issues, since the RKI website is not maintained through GitHub. 

---
Internal Tracking ID: [EXPOSUREAPP-13401](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13401)

### PR DESCRIPTION
**Pull request by larswmh**
#2965 

FAQ text changes have been seperated from previously submitted PR #3013 as they require further review

[#red_card_how_to_test](https://www.coronawarn.app/en/faq/results/#red_card_how_to_test)
image
image

[#rat_red_card_which_test](https://www.coronawarn.app/en/faq/results/#rat_red_card_which_test)
image
image

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Also

[#in_a_nutshell](https://www.coronawarn.app/en/faq/results/#in_a_nutshell)

**Comment by larswmh** [comment]
@MikeMcC399 thanks for your suggestions.

In [#red_card_how_to_test](https://www.coronawarn.app/en/faq/results/#red_card_how_to_test) we have now added another poster for rapid antigen tests that is already being linked to in [#rat_partner](https://www.coronawarn.app/de/faq/results/#rat_partner).

For [#rat_red_card_which_test](https://www.coronawarn.app/en/faq/results/#rat_red_card_which_test), we have changed the sentence you criticized to: "Please confer with your doctor for the further procedure if you have symptoms or feel sick."

While the assumption that the term "several" offers room for interpretation, we won't change it in the FAQ (for now), as this is, as you already said, the way it is implemented to the app. 

Please understand that we want to handle the other two FAQ entries that you commented about in the last hour in another pull request. This PRs texts have now undergone extensive review by our internal team and we don't want to push these changes even further back.

**Comment by MikeMcC399** [comment]
@larswmh 

> In [#red_card_how_to_test](https://www.coronawarn.app/en/faq/results/#red_card_how_to_test) we have now added another poster for rapid antigen tests that is already being linked to in [#rat_partner](https://www.coronawarn.app/de/faq/results/#rat_partner).

That problem is solved, except that there is now a bad link `[RESPONSE 404] http://localhost:8000/assets/documents/BPA_Corona-Warn-App_RKI-Plakat_Testcenter_A1_ICv2_RZ04_x3b-EN.pdf on '/en/faq/results/'` so it would be good if you could sort that out before merging.

> For [#rat_red_card_which_test](https://www.coronawarn.app/en/faq/results/#rat_red_card_which_test), we have changed the sentence you criticized to: "Please confer with your doctor for the further procedure if you have symptoms or feel sick."

That is also an improvement!

> While the assumption that the term "several" offers room for interpretation, we won't change it in the FAQ (for now), as this is, as you already said, the way it is implemented to the app.

I understand about keeping consistency. If users could perhaps later be given more concrete advice than the app gives, I think that would be helpful.

> Please understand that we want to handle the other two FAQ entries that you commented about in the last hour in another pull request. This PRs texts have now undergone extensive review by our internal team and we don't want to push these changes even further back.

I only noticed the other affected FAQ articles when I was cross-checking about quarantine today. If these articles are handled separately then fine.

**Comment by larswmh** [comment]
@MikeMcC399 

> That problem is solved, except that there is now a bad link [RESPONSE 404] http://localhost:8000/assets/documents/BPA_Corona-Warn-App_RKI-Plakat_Testcenter_A1_ICv2_RZ04_x3b-EN.pdf on '/en/faq/results/' so it would be good if you could sort that out before merging.

Thanks for the information. It has been fixed in the latest commit

**Review by MikeMcC399 — APPROVED** [review]
All the points I raised have been answered.

**Review by GisoSchroederSAP — APPROVED** [review]
Content and logic are fine and consistent/close to the current official phrases.
Approved.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for your suggestions/contributions/review. Enjoy your Sunday!

**Pull request merged**
