### PR TITLE
Fix FAQ menu for iPad Air 4th gen

### PR DESCRIPTION
**Pull request by brifemu**
Due to issue #1998 I had changed the breakpoint size for $screen-md from 862px to 918px, is when the menu starts to break.

Is very important to test the menu and all the pages on a real iPad Air 4th gen before merge this, so please @Ein-Tim give me back your feedback after test it.

### CODE REVIEW

**Comment by Ein-Tim** [comment]
@brifemu 

Thank you for the quick fix! 
I will test this change as soon as I can!

**Review by Ein-Tim — COMMENTED** [review]
I verified this change on my iPad Air 4. Gen, the FAQ page now looks like this:

IMG_A4BA4A8A87D5-1

This is definitely better than before. But one thing which should be changed is the arrow to expand the menu, it is currently cut off when opening the FAQ page. Only if one scrolls down a bit it becomes fully visible.

This change,however, also changed how the menu on the screenshot page is accessible. 
While it was visible without any problems before this change, it's now only visible after clicking on the arrow to expand it. But this does not seem like a big issue to me.

| Screenshots page before this change | Screenshots page after this change |
|---|---|
| IMG_0026 | IMG_0025 |

Also, this change changed the behaviour of the menu (of the whole coronawarn.app site) to not be shown like this anymore:


It's now shown like this:


This is a welcome improvement IHMO.

**Comment by brifemu** [comment]
Thank you so much @Ein-Tim for your feedback.

That is why it is so important to test the real device, simulating it in Chrome's DevTools, the menu button error did not happen.

I had increased the bottom space for the arrow container. Is weird that the arrow position only changes on FAQ page, to prevent, I had increased it 25px in the main style.

I will wait for your feedback to continue working on it.

**Comment by Ein-Tim** [comment]
@brifemu 

> Thank you so much @Ein-Tim for your feedback.

For sure! Thank you for fixing this issue! 

> I had increased the bottom space for the arrow container. Is weird that the arrow position only changes on FAQ page, to prevent, I had increased it 25px in the main style.
I will wait for your feedback to continue working on it.

I retested based on the latest commit [`01d67da` (#1999)](https://github.com/corona-warn-app/cwa-website/pull/1999/commits/01d67dae61cb2da6765d3c81308bb8da327af149), but sadly, this bug still persists.

Here's a screenshot. I added a red "circle" so that it's visible what the problem is:

**Comment by brifemu** [comment]
@Ein-Tim I gave it again more bottom space. I discovered that the issue was caused to have more than one tab open, the browser creates the bar and that affected the arrow position.

**Comment by Ein-Tim** [comment]
Thanks @brifemu 

I will test again.

**Review by Ein-Tim — APPROVED** [review]
Works as intended now!

Only one tab opened:


More than one tab opened (the arrow is visible but the box which is around it is still cut off a bit):

**Comment by brifemu** [comment]
@Ein-Tim can you try it again with a smaller system font size, please? I guess the problem is the system font size. Someone with default font size would see the arrow higher.

**Comment by Ein-Tim** [comment]
@brifemu 

I can do this, but I did not change the font size (=I should be using the default one).

**Comment by Ein-Tim** [comment]
So, sorry for the delay, was a busy day.

When setting the font size to the smallest one possible, the box around the arrow is still cut off, but **this is really no big problem as it does not affect the functionality of the button in any way.**

**Screenshots**:

iPad Air 4. Gen only one tab opened:

| Scrolling position | Currently | After this change |
|---|---|---|
| Not scrolled down |   |  |
| Scrolled down |  |  |

iPad AIr 4. Gen two tabs opened:

| Scrolling position | Currently | After this change |
|---|---|---|
| Not scrolled down |  |  |
| Scrolled down |  |  |

This is good to go for me! Also tested on iPhone XR. iPhone 6s & Huawei P Smart 2019. No issues.

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for report and all the feedback!

**Comment by Ein-Tim** [comment]
@dsarkar 

For sure! Thanks for fixing this so quick! Have a nice weekend!

**Pull request merged**
