### PR TITLE
Updated encounter but green

### PR DESCRIPTION
**Pull request by OlMue**
According to RKI feedback

### CODE REVIEW

**Review by SabineLoss — APPROVED** [review]

**Comment by daimpi** [comment]
@OlMue @SabineLoss 
This changes seem to contradict https://github.com/corona-warn-app/cwa-website/issues/307#issuecomment-679233521

Could you please clarify?

**Comment by OlMue** [comment]
@daimpi Yes, I pointed this out in [#319 (comment)](https://github.com/corona-warn-app/cwa-website/pull/319#issuecomment-684665351). I had to make this change first. I'm not involved in #319, so I'm not sure about the status but I assume that your suggestions will still be implemented. @MarlisFriedl @tkowark please check.

**Comment by daimpi** [comment]
@OlMue this change goes in the exact opposite direction of what was discussed in https://github.com/corona-warn-app/cwa-website/issues/307

I was telling @svengabr about the problem with this change already last week on Slack and he agreed. And now this has just been merged nevertheless. This PR introduces potentially factually wrong information into the FAQ.

**Comment by OlMue** [comment]
@daimpi I apologize, I wasn't aware of this.

@svengabr @mtb77: The request for the change this PR was forwarded to me by @janetback who was in contact with the RKI.

**Comment by daimpi** [comment]
@OlMue ok, no problem, let's try to quickly get this sorted out then 🙂 
If you want to join us on Slack btw here is the invitation link: https://join.slack.com/t/covidapps/shared_invite/zt-gmgl4l13-E4Xcn1ZfPFsPz6V_KjROCg (we're in the cwa channel)

**Pull request merged**
