### PR TITLE
FAQ iOS Error 13

### PR DESCRIPTION
**Pull request by dsarkar**
Closes https://github.com/corona-warn-app/cwa-website/issues/713

### CODE REVIEW

**Comment by dsarkar** [comment]
image

**Review by loki-cui — APPROVED** [review]

**Comment by dsarkar** [comment]
**DE**
image


**EN**
image

**Comment by MikeMcC399** [comment]
@dsarkar 

Could you

- remove the German error message from the English FAQ and
- remove the English error message from the German FAQ?

It would make your update more readable that way.

Also the English error message in the English version does not make sense and it is different to the English error message in the German version! 😕

**Comment by MikeMcC399** [comment]
New issue https://github.com/corona-warn-app/cwa-website/issues/715 opened since this PR is already merged.

**Pull request merged**
