### PR TITLE
Update Analysis Page Title

### PR DESCRIPTION
**Pull request by browkin**
- Changed Analysis Page title from "Analysis" to "Dashboard" as it fits better

Paths where it got changed:
- [/blog/2021-10-01-facts-and-figures/index.md]
- [/blog/2021-10-01-facts-and-figures/index_de.md]
- [/blog/2021-10-04-dashboard/index.md]
- [/blog/2021-10-04-dashboard/index_de.md]
- [/src/data/analyse_de.json]
- [/src/data/analyse_en.json]
- [/src/data/global.json]
- [/src/pages/de/analyse/index.html]
- [/src/pages/en/analyse/index.html]
- [/src/pages/de/analysis/index.html]
- [/src/pages/en/analysis/index.html]

**DE:**
dashboardscreen

**EN:**
ensnippeddashboard

Reference #2352 @MikeMcC399

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@browkin also change menu, please.

**Comment by MikeMcC399** [comment]
@dsarkar / @browkin 

If you change the menu, then all the references to it need to be changed in the blogs and the FAQs.

**Comment by MikeMcC399** [comment]
There are still some places that need changing.

`<title>Open-Source Project Corona-Warn-App - Analysis</title>`

also

in en/blog/2021-10-04-key-figures-dashboard/

"Analysis data from the Corona-Warn-App" => "Dashboard data from the Corona-Warn-App"

de/blog/2021-10-04-key-figures-dashboard/

"Analysedaten der Corona-Warn-App" => "Dashboarddaten der Corona-Warn-App"

**Comment by MikeMcC399** [comment]
@browkin 

Will you continue with this PR?

**Comment by MikeMcC399** [comment]
@browkin 

Please check also:
- https://github.com/corona-warn-app/cwa-website/blob/master/src/pages/en/analyse/index.html
- https://github.com/corona-warn-app/cwa-website/blob/master/src/pages/en/analysis/index.html
- https://github.com/corona-warn-app/cwa-website/blob/master/src/pages/de/analyse/index.html
- https://github.com/corona-warn-app/cwa-website/blob/master/src/pages/de/analysis/index.html

**Comment by browkin** [comment]
@MikeMcC399 all places should be covered now. Thank you, for your help!

**Review by MikeMcC399 — APPROVED** [review]
@browkin 
It's looking good. No more comments from my side 🙂 !

I think it can be merged now!
Thank you!

**Comment by MikeMcC399** [comment]
@dsarkar 
Can this be merged now? Or is there some problem or missing approval?

**Review by GisoSchroederSAP — APPROVED** [review]
"Good-to-go" from my side as well.
Please proceed.

**Pull request merged**
