### PR TITLE
Mention luca in check_in_qr_code

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR updates https://www.coronawarn.app/de/faq/#check_in_qr_code to reflect that one can now scan luca QR codes.

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by Ein-Tim** [comment]
Do we write 'luca' with or without ''?

**Comment by larswmh** [comment]
> Do we write 'luca' with or without ''?

Without ' '. We would also like to consistenly use `luca-App` instead of `luca App` in DE. In check_in_luca we're currently using both, but will correct it to `luca-App` later.

**Comment by Ein-Tim** [comment]
@larswmh Okay, I will change this when I have time!

**Comment by larswmh** [comment]
> @larswmh Okay, I will change this when I have time!

As I am currently already working on some updates for the check in FAQ I would suggest to take over your changes as well, so you don't need to put any more effort into it. I will mention this PR in my new PR

**Comment by larswmh** [comment]
@Ein-Tim your changes have been included into @floscher's PR

**Comment by Ein-Tim** [comment]
Thanks @larswmh!
Closing!

**Pull request closed without merging**
