### PR TITLE
Add FAQ redirect from `check_in_qr_warning` to `check_in`

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description

This PR adds a new FAQ redirect  from `check_in_qr_warning` to `check_in`, as the FAQ entry `check_in_qr_warning` has been deleted.

## What was changed
- A FAQ Redirect was added

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Was #check_in_qr_warning deliberately removed or was it an accident?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I guess it was deleted on purpose.

**Comment by dsarkar** [comment]
it was this article 
image

**Comment by dsarkar** [comment]
now separated Q&A
image

**Comment by MikeMcC399** [comment]
@dsarkar 

Thanks for supplying the background! So the article text was redistributed.

The article
https://www.coronawarn.app/en/faq/#check_in_qr_warning
in the old web maps to several different articles in the new web

App Features / Check In
https://www.coronawarn.app/en/faq/results/#check_in_qr_warning_procedure
https://www.coronawarn.app/en/faq/results/#check_in_qr_warning_how
https://www.coronawarn.app/en/faq/results/#check_in_qr_warning_base
https://www.coronawarn.app/en/faq/results/#check_in_qr_warning_share

and the nearest equivalent is

https://www.coronawarn.app/en/faq/results/#check_in

---

The proposed redirect from @Ein-Tim does make sense in this case.
#check_in_qr_warning => #check_in

**Review by dsarkar — APPROVED** [review]

**Pull request merged**
