### PR TITLE
Remove "International phone numbers" from the title of "international_phone_numbers"

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR removes "International phone numbers" from the title of the FAQ entry "internation_phone_numbers", since we also store the national phone numbers there.
Also, a "." was moved out of a link in "who_can_help". Instead, the "." is now normal text (;

### CODE REVIEW

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. What do you think about "national and International phone numbers" in the title? Just in case somebody uses the search function?

**Comment by Ein-Tim** [comment]
@dsarkar Yeah, we could do this but I think if somebody wants to find out the phone numbers he/she will simply search for "phone numbers". 
But as you like, I can change it if you want!

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@Ein-Tim ok, agreed. We adopt your suggestion.

**Comment by Ein-Tim** [comment]
Thanks @dsarkar 

Have a nice sunny Sunday!

**Pull request merged**
