### PR TITLE
Update build workflow to select Node.js v14 explicitly

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/2142 "GitHub new default Nodejs 16 will break build workflow".

It adds the following to [build.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) workflow

```
- name: Setup Node.js environment (v14)
  uses: actions/setup-node@v2
    with:
      node-version: 'lts/fermium'
```

Also the `name: Setup Node.js environment (v14)` key is added to 
[deploy-master.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml) for clearer logging and consistency.

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
image
@MikeMcC399 @matriceria

**Comment by MikeMcC399** [comment]
@dsarkar 

I'm not sure if the PR is strictly necessary, since 
[build.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) includes:

```
    # Cypress Docker image with Chrome v80
    # and Firefox v73 pre-installed  cypress/browsers:node14.7.0-chrome84 cypress/browsers:node10.16.3-chrome80-ff73
    container: cypress/browsers:node14.7.0-chrome84
```

https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node14.7.0-chrome84

says this is `debian version:  10.3`

so on reflection, I'm not sure how this all works. 😟

**Comment by dsarkar** [comment]
@MikeMcC399 this issue was found by @matriceria: https://stackoverflow.com/questions/19975954/a-yaml-file-cannot-contain-tabs-as-indentation#:~:text=A%20YAML%20file%20use%20spaces,by%20different%20editors%20and%20tools.

**Comment by MikeMcC399** [comment]
It seems that [build.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) was sensitive to some whitespace. I changed it and the syntax is now accepted.

**Comment by MikeMcC399** [comment]
@dsarkar 

Thanks to you and to @matriceria ! Due to some problems with Atom I had the usual formatting switched off and I put a tab in instead of spaces. 🙁.

> Anyway, we will clarify independently of this issue, if we need this PR at all.

That is a good idea. Actually I do not know what the reason for having the cypress docker image in the build workflow is, because I don't think this is used. Maybe it was intended at some time to run Cypress tests automatically and therefore a browser environment would be needed?

**Comment by MikeMcC399** [comment]
@dsarkar 

We could just wait until the `ubuntu-latest` build actually migrates to Node v16. If this causes an error, then some action is needed. If no error, then we could just close this PR.

**Comment by MikeMcC399** [comment]
@dsarkar / @matriceria 

I think that  [build.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) will fail as soon as the default for Node changes from v14 to v16 unless the workflow is changed.

I did a test on a separate test repository with only

```
  "dependencies": {
    "gulp-sass": "^4.1.1"
```
in `package.json` with the following test workflow script:

```
name: test workflow
on: [push]
jobs:
  checking-install:
    runs-on:  ubuntu-latest
    container: cypress/browsers:node14.7.0-chrome84
    strategy:
      matrix:
        node: [lts/fermium, lts/gallium]
    steps:
      - uses: actions/checkout@v2
      - name: Select node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node}}
      - name: npm install
        run: npm install
```

It was successful for `lts/fermium` and failed for `lts/gallium`.

For `lts/gallium` it updated `package-lock.json` temporarily from "lockfileVersion" 1 to 2 then failed.

I removed  `"gulp-sass": "^4.1.1"` (not compatible with node v16) and replaced it by `"node-sass": "^6.0.1"` (which is compatible with node v16) and the workflow was successful for both node versions.

## Suggestion

You may want to mitigate the risk now by merging this PR or just wait to see if the build does actually fail. If necessary this PR can be quickly merged if builds start failing after GitHub completes the migration to Node v16.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks a lot for the analysis. I think we will come tomorrow to a decision how to proceed. Enjoy your evening!

**Comment by MikeMcC399** [comment]
The PR merge for Science Blog 4 EN today (https://github.com/corona-warn-app/cwa-website/pull/2137) used ubuntu-20.04, build 20211129.1 and there were no errors in the build workflow. See https://github.com/corona-warn-app/cwa-website/pull/2137/checks:

```
2021-12-02T06:51:49.6228229Z ##[group]Operating System
2021-12-02T06:51:49.6229134Z Ubuntu
2021-12-02T06:51:49.6229580Z 20.04.3
2021-12-02T06:51:49.6229963Z LTS
2021-12-02T06:51:49.6230426Z ##[endgroup]
2021-12-02T06:51:49.6231074Z ##[group]Virtual Environment
2021-12-02T06:51:49.6231606Z Environment: ubuntu-20.04
2021-12-02T06:51:49.6232038Z Version: 20211129.1
2021-12-02T06:51:49.6232863Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211129.1/images/linux/Ubuntu2004-README.md
2021-12-02T06:51:49.6233966Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211129.1
2021-12-02T06:51:49.6234675Z ##[endgroup]
```

so it seems that this PR is not needed. I will take a look in a test repository to try to understand about the changes.

In the meantime I put this PR into draft status.

**Comment by MikeMcC399** [comment]
@dsarkar 
I did some testing and I understand this better now. I'm going to open a new issue with some suggestions.

**Comment by MikeMcC399** [comment]
For clarity, I will replace this PR with a new one.

**Pull request closed without merging**
