### PR TITLE
improvement(sitemap): updated sitemap.xml #50

### LINKED ISSUE #50: Outdated sitemap.xml
## Where to find the issue
https://www.coronawarn.app/sitemap.xml

## Describe the issue
The sitemap provided seems to include an older version with another URL structure (w/o www. sub) as well.

## Suggested change
Update the https://www.coronawarn.app/sitemap.xml with a newer version.

### PR DESCRIPTION
**Pull request by mfranzke**
Closes #50

### CODE REVIEW

**Comment by corneliusroemer** [comment]
They don't seem to like outside contributions.

**Comment by mohe2015** [comment]
@corneliusroemer It was just opened one day ago, isn't super urgent and today is release day so be patient please.

**Comment by SebastianWolf-SAP** [comment]
I can only agree with @mohe2015. You are not forgotten - it's just priorities and available resources right now.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by corneliusroemer** [comment]
@SebastianWolf-SAP Can you not ask for more resources around launch time?

**Comment by tkowark** [comment]
Thanks a lot for the PR and also sorry for taking so long to respond. While we love the up-to-date sitemap, we thought that it would also make sense to created it automatically. So, your work is not lost but inspired us to improve the page further (I'll introduce the sitemap generation, in a separate PR). Thanks a lot, again!

**Pull request closed without merging**
