### PR TITLE
faq dublin add zip code // Germany ==> Deutschland // Irland ==> Ireland // status date

### PR DESCRIPTION
**Pull request by dsarkar**
closes https://github.com/corona-warn-app/cwa-website/issues/689

### CODE REVIEW

**Comment by dsarkar** [comment]
image

**Comment by loki-cui** [comment]
@dsarkar : Pls. change "Irland" to "Ireland" in the EN version.

**Comment by dsarkar** [comment]
image

**Comment by dsarkar** [comment]
image

**Review by loki-cui — APPROVED** [review]

**Review by loki-cui — APPROVED** [review]

**Pull request merged**
