### PR TITLE
Release 2.21 Screenshots

### PR DESCRIPTION
**Pull request by larswmh**
image
image

### CODE REVIEW

**Review by MikeMcC399 — CHANGES_REQUESTED** [review]
Risk cards such as /assets/screenshots/2-21/en/android/no_risk_3.png still show 14 days of exposure risk coverage. This was reduced to 10 days in version 2.20 already.

**Comment by larswmh** [comment]
> Risk cards such as /assets/screenshots/2-21/en/android/no_risk_3.png still show 14 days of exposure risk coverage. This was reduced to 10 days in version 2.20 already.

Fixed in latest commit, thanks

**Review by MikeMcC399 — APPROVED** [review]
Request to update risk card screenshots to 10 days has been fulfilled, so cancelling request to change.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for feedbalck/review.

**Pull request merged**
