### PR TITLE
Corrections to luca FAQ

### PR DESCRIPTION
**Pull request by MikeMcC399**
@dsarkar  / @larswmh 
This follows on from https://github.com/corona-warn-app/cwa-website/pull/2041#issuecomment-963926003.

The PR corrects some points in:

- https://www.coronawarn.app/en/faq/#check_in_luca and
- https://www.coronawarn.app/de/faq/#check_in_luca

I hope the changes are all self-explanatory. Let me know if there are questions.

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.

**Comment by larswmh** [comment]
Thanks for your corrections @MikeMcC399. I mostly agree with it, except for the removal of the line `"In the respective state ordinances on infection protection, it is stipulated whether and how contact tracking must take place at events."`. I accidently put it in twice in my pull request, but it is actually supposed to be a seperate paragraph instead of a sentence at the end of the paragraph above it. Therefore it should ideally be removed from the other line and put back in as a seperate line.

**Comment by MikeMcC399** [comment]
@larswmh 
> it is actually supposed to be a seperate paragraph instead of a sentence at the end of the paragraph above it.

I wasn't sure about that, so I will change it according to your request.

Thanks for the feedback!

**Comment by MikeMcC399** [comment]
@larswmh 
It's changed now.

**Review by larswmh — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the fix!

**Comment by MikeMcC399** [comment]
@larswmh 
I didn't notice for the English text that the repeated sentences were not exactly the same:

- In the respective state ordinances on infection protection, it is stipulated whether and how contact tracking must take place at events.

- In the respective state ordinances on infection control, it is stipulated whether and how contact tracing must take place at events.

protection / control
tracking / tracing

Could you please check and make the corrections yourself if I chose the wrong sentence?

**Pull request merged**
