### PR TITLE
Release 2.28 Updates

### LINKED ISSUE #3126: Release 2.28 Updates
- [x] Update Gulpfile 
iOS 2.28.0
Android 2.28.2
- [x] Update Screenshots https://github.com/corona-warn-app/cwa-website/pull/3133
  - [x] Update release date in intro text. 
- [x] Update AppToWebLinks.json https://github.com/corona-warn-app/cwa-website/pull/3154 
- [x] Update sitemap.json and sitemap_de.json 
  - [x] Add screenshots page R 2.27 - https://github.com/corona-warn-app/cwa-website/pull/3133
  - [x] Add blog R 2.28 - https://github.com/corona-warn-app/cwa-website/pull/3130.
- [x] Update Privacy notice https://github.com/corona-warn-app/cwa-website/pull/3145
  - [x] add new docs (three PDF).
  - [x] update release date.
- [x] Update FAQ/Glossary articles
https://github.com/corona-warn-app/cwa-website/pull/3152
  - [x] Set "aktualisiert am/updated" dates.
  - [x] Set blog post date in URL.
- [x] Blog.

---
**Other new or updated content (some updates are unrelated to release 2.28)**

- https://github.com/corona-warn-app/cwa-website/pull/3113
- https://github.com/corona-warn-app/cwa-website/pull/3114
- https://github.com/corona-warn-app/cwa-website/pull/3116
- https://github.com/corona-warn-app/cwa-website/pull/3117
- https://github.com/corona-warn-app/cwa-website/pull/3118
- https://github.com/corona-warn-app/cwa-website/pull/3119
- https://github.com/corona-warn-app/cwa-website/pull/3122
- https://github.com/corona-warn-app/cwa-website/pull/3123
- https://github.com/corona-warn-app/cwa-website/pull/3124
- https://github.com/corona-warn-app/cwa-website/pull/3125
- https://github.com/corona-warn-app/cwa-website/pull/3127
- https://github.com/corona-warn-app/cwa-website/pull/3128
- https://github.com/corona-warn-app/cwa-website/pull/3129
- https://github.com/corona-warn-app/cwa-website/pull/3131
- https://github.com/corona-warn-app/cwa-website/pull/3132
- https://github.com/corona-warn-app/cwa-website/pull/3134
- https://github.com/corona-warn-app/cwa-website/pull/3136
- https://github.com/corona-warn-app/cwa-website/pull/3138
- https://github.com/corona-warn-app/cwa-website/pull/3139
- https://github.com/corona-warn-app/cwa-website/pull/3140
- https://github.com/corona-warn-app/cwa-website/pull/3141
- https://github.com/corona-warn-app/cwa-website/pull/3142
- https://github.com/corona-warn-app/cwa-website/pull/3143

--- 
Internal Tracking ID: [EXPOSUREAPP-14052](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14052)

### PR DESCRIPTION
**Pull request by larswmh**
Fixes #3126 

---
Internal Tracking ID: [EXPOSUREAPP-14052](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14052)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
I know this PR is in draft state, however the linked issue https://github.com/corona-warn-app/cwa-website/issues/3126 has ticked off the following:

- Update Privacy notice https://github.com/corona-warn-app/cwa-website/pull/3145
    - add new docs (three PDF)
    - update release date

That doesn't quite fit because the new privacy notices are missing in the branch [release/2.28](https://github.com/corona-warn-app/cwa-website/tree/release/2.28). For instance I would expect to see a document:

https://github.com/corona-warn-app/cwa-website/blob/release/2.28/src/assets/documents/cwa-privacy-notice-en.pdf

but there is no such file.

For comparison, the master branch contains this file:
https://github.com/corona-warn-app/cwa-website/blob/master/src/assets/documents/cwa-privacy-notice-en.pdf

**Comment by brianebeling** [comment]
> I know this PR is in draft state, however the linked issue #3126 has ticked off the following:
> 
> * Update Privacy notice [Privacy Notice Updates 2.28 #3145](https://github.com/corona-warn-app/cwa-website/pull/3145)
>   
>   * add new docs (three PDF)
>   * update release date
> 
> That doesn't quite fit because the new privacy notices are missing in the branch [release/2.28](https://github.com/corona-warn-app/cwa-website/tree/release/2.28). For instance I would expect to see a document:
> 
> https://github.com/corona-warn-app/cwa-website/blob/release/2.28/src/assets/documents/cwa-privacy-notice-en.pdf
> 
> but there is no such file.
> 
> For comparison, the master branch contains this file: https://github.com/corona-warn-app/cwa-website/blob/master/src/assets/documents/cwa-privacy-notice-en.pdf

Hey Mike, thanks for the heads-up. We did not forget the files, but did not include them on purpose. Rest assured, they will be added prior to release!

**Comment by MikeMcC399** [comment]
@brianebeling 

> thanks for the heads-up. We did not forget the files, but did not include them on purpose. Rest assured, they will be added prior to release!

Good to hear that nothing was forgotten. Perhaps the ticks should be removed to indicate outstanding to-do items?

image

**Review by mtb77 — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@dsarkar 

The last commit in this PR (https://github.com/corona-warn-app/cwa-website/pull/3130/commits/a25b61011cf5759ada8b2e06e9376dd40b77d450) has led to the temporary file [cypress/downloads/downloads.html](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/downloads/downloads.html) being merged into the `master` branch.

.`gitignore` includes `cypress/downloads/` to ignore, so this file should not normally be committed to the repository.

Would you like to submit a PR to remove it?

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. PR https://github.com/corona-warn-app/cwa-website/pull/3171

**Pull request merged**
