### PR TITLE
Revert old sitemap PR and create simple sitemap

### PR DESCRIPTION
**Pull request by larswmh**
This PR reverts #2504 and creates a less complicated sitemap. Among other things, many vulnerabilities that were caused by the previous solution have been terminated with this.
sitemap

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@larswmh 

Could you please check which version of `npm` you are using? For instance:
```
$ npm -v
8.5.0
```

The `package-lock.json` you committed has reverted to  `"lockfileVersion": 1`. It should be  `"lockfileVersion": 2`

It's best if you have Node.js 16 installed as recommended by https://github.com/corona-warn-app/cwa-website/blob/master/README.md#requirements.

**Review by MikeMcC399 — CHANGES_REQUESTED** [review]
Testing locally there is a German footer on the English language page http://localhost:8000/en/sitemap/. The footer should be in the same language as the page itself.

**Comment by larswmh** [comment]
@MikeMcC399 thanks for your feedback. 
I updated Node.js to the latest recommended version and `lockfileVersion` is now set back to 2.
The footer on the English sitemap has been changed to the English footer.

**Review by MikeMcC399 — APPROVED** [review]
I can't see any other issues, so LGTM!

**Comment by svengabr** [comment]
Changes approved, thanks @larswmh !

**Pull request merged**
