### PR TITLE
Change video alt attribute to aria-label

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3227 "Illegal alt attribute for video" by converting the `alt` attribute from the `<video>` content tab to an `aria-label` attribute in:

- https://www.coronawarn.app/en/faq/results/#in_a_nutshell in "Explanatory video"
- https://www.coronawarn.app/de/faq/results/#in_a_nutshell in "Erklärvideo"

### Validator

Run https://validator.w3.org on https://www.coronawarn.app/en/faq/results/ and check that the following error is no longer produced:

- "Attribute alt not allowed on element video at this point."

### Screen reader

In Windows 10 / 11

1. Open https://www.coronawarn.app/en/faq/results/#red_card in Google Chrome
2. Click on "In a nutshell" to expand
3. Enable Narrator: Windows key + Ctrl + Enter
4. Press 3 to move to "In a nutshell"
5. Press 3 until "Explanatory video" is reached and read out
6. Press Tab to move to video
7. Note that it reads the `aria-label` text "Corona-Warn-App - explanatory film" followed by "Group"
8. Press Tab to access the play control
9. Press Space to play the video

### CODE REVIEW

**Comment by brianebeling** [comment]
Hey, I was quickly researching and stumbled upon this https://www.w3.org/WAI/PF/HTML/wiki/Media_Alt_Technologies#1:_Use_.40aria-label_for_the_text_description_of_player

In there, they specifically label the video using the sentence: "hit space to toggle play/pause". 

I think we should either add that (or similar) to our label sentence or additionally use the  aria-describedby, if applicable.
What do you think?

**Comment by MikeMcC399** [comment]
@brianebeling 

Your suggestion to use also `aria-describedby` sounds like a good enhancement. So far this PR was just a bug-fix. Let me try this out with a screen-reader. This is a new area for me.

**Comment by brianebeling** [comment]
Thanks! Looking good otherwise. I think this is a great improvement already.

**Comment by MikeMcC399** [comment]
@brianebeling 

I made a start by checking that the change to `aria-label` works using the built-in [Windows 11 Narrator](https://support.microsoft.com/en-us/windows/complete-guide-to-narrator-e4397a0d-ef4f-b386-d8ae-c172f109bdb1).

I have never used this before and I found it not so intuitive. It's really necessary to go through the getting started guide.

I checked on other pages on the web site and there are other videos which need correcting as well because of their incorrect use of the `alt` attribute.

The exercise I am going through at the moment is to clean up the HTML only on the FAQ page, so I would like to suggest merging this PR as is (without the addition of `aria-describedby`) and then opening a new request to correct and enhance all video links on the web for accessibility and consistency. The resolution could include adding `aria-describedby` to all the other videos.

**Comment by MikeMcC399** [comment]
@brianebeling 

I have added verification steps using the Windows 10 / 11 screen reader (Narrator) to the original post. 

Unfortunately your suggested text "hit space to toggle play/pause" does not provide the correct instructions for the Narrator in this instance and I don't know enough about this topic to be able to suggest the correct general solution which will work on all screen readers and for the other different videos on this website.

I will open a new issue to describe the incorrect use of the `alt` attribute together with other `<video>` tag usage outside of the FAQs. Again, this will just be a bug report with a suggestion for a bug fix rather than an enhancement.

**Review by brianebeling — APPROVED** [review]
Considering that we have a new Issue now, I will merge this PR and we can take a look at the narration and accessibility in the future again.

**Comment by MikeMcC399** [comment]
Verified fixed with:

- https://validator.w3.org/
- Windows 11 Narrator (Windows key + Ctrl + Enter)

(details see original post)

**Pull request merged**
