### PR TITLE
Update website - Section: This is how the app works best 

### PR DESCRIPTION
**Pull request by dsarkar**
Closes https://github.com/corona-warn-app/cwa-website/issues/856

### CODE REVIEW

**Comment by dsarkar** [comment]
removed also

 bzw. mindestens iOS [ios.minimum-required-os-version]

**Review by GisoSchroederSAP — APPROVED** [review]
Looks good/acceptable to me

**Comment by dsarkar** [comment]
EN

image

**Comment by dsarkar** [comment]
DE

image

**Comment by Ein-Tim** [comment]
@dsarkar 

Will we keep `[ios.latest-os-version]` with the latest release (iOS 14.4)?

**Comment by Ein-Tim** [comment]
O/T @GisoSchroederSAP Maybe you would like to make your membership of the CWA organization public? 

Thanks!

**Pull request merged**
