### PR TITLE
fixed-EventRegistrationTest-i18n-Issue

### PR DESCRIPTION
**Pull request by chrisenitan**
## Why
- Fixes bug issue #1513 
Test fail when ran against the `/de/` domain due to unavailability of asserted strings. 

## What changed
Original issue reported on #1503 
- Run 3 main available tests in spec `eventRegistration.js` against `de` and `en` domains
- Removed the `cypress.env.json` file from `gitignore` 
- Removed test language localisation details from the projects README file

Screenshot 2021-07-19 at 19 21 06

---
Internal Tracking ID: [EXPOSUREAPP-8242](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8242)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@chrisenitan 
Thanks for addressing the issues in #1513!

I can see the file `cypress.env.json` included in this PR although the environment variable `testEnvLang` is no longer used in `cypress/integration/pages/eventRegistration.js`. Wouldn't it be cleaner to just remove the file `cypress.env.json` from this PR if it is not needed?

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-8242](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8242)

**Review by MikeMcC399 — APPROVED** [review]
LGTM
All tests succeed.

**Review by svengabr — APPROVED** [review]

**Comment by svengabr** [comment]
Looks good to me too, changes are approved.

Thanks!

**Pull request merged**
