### PR TITLE
Update CWA Android version in gulpfile.js

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR updates the CWA Android version in the gulpfile.js as requested from @dsarkar in https://github.com/corona-warn-app/cwa-website/pull/924#issuecomment-791194506

This PR should be merged after #924

### CODE REVIEW

**Comment by Ein-Tim** [comment]
@dsarkar are you able to resolve the merge conflict? 
I'm strangely not able to 🤔

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!

**Comment by dsarkar** [comment]
@Ein-Tim I thinks this happened because the same line was edited in both, your and my PR.

**Comment by Ein-Tim** [comment]
@dsarkar 

I think it should be ok now, or?

**Comment by dsarkar** [comment]
@Ein-Tim  Yep, edited the line in the online editor. Thanks again!

**Pull request merged**
