### PR TITLE
Update iOS Versions

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR updates the iOS Versions 

- iOS 14.4 -> iOS 14.4.2 (see https://support.apple.com/kb/HT212256)
- iOS 12.5.1 -> iOS 12.5.2 (see https://support.apple.com/kb/HT212257)

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Sorry for not squashing the commits, currently working on another PC which only has the GitHub website. Fell free to use squash and merge.

**Comment by Ein-Tim** [comment]
@dsarkar Could you please take a look at this? Thank you! 🙂

**Comment by dsarkar** [comment]
@Ein-Tim Many thanks!

**Comment by dsarkar** [comment]
@Ein-Tim If you are interested, and happy to take this over: open in doc repo an issue 


"Wie und wo kann man sich testen lassen? / How and where to get tested?"


Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar 

For sure I can do this (but only todays evening, sorry). 
May I ask why?

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. We think it might be useful and also very welcome by the GH community and other users, but it is currently not our scope. Idea is later to link to the GH issue from a FAQ article.

**Comment by Ein-Tim** [comment]
@dsarkar 

Thanks for the list and the texts, I opened https://github.com/corona-warn-app/cwa-documentation/issues/569. I adapted the texts a bit to explain how to contribute. Hope that's fine for you (:

**Pull request merged**
