### PR TITLE
Release 2.10 Screenshots

### PR DESCRIPTION
**Pull request by larswmh**
DE:
image
EN:
image

New category: Print Vaccination Certificate
iOS:
DE:
chrome_g5zHaqwbcx

EN:
chrome_KttBB6ZVhA

Android:
DE:
chrome_NY7I9wu8XA

EN:
chrome_Bu4W6Up6dh

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@larswmh 

I know this is WIP, but once the screenshots get published it is less easy to get them changed:

"Print vaccination certificate" and
"Impfzertifikat drucken" should be capitalized

---
en/screenshots/#ios_print_vaccination_certificate

first graphic is a recovery certificate, not a vaccination certificate. I'm not sure that makes sense.
second graphic vaccination certificate: shouldn't the background be blue, not grey?

---
Will there be Android screenshots for
en/screenshots/#android_print_vaccination_certificate
de/screenshots/#android_print_vaccination_certificate ?

At the moment the links are missing the filenames.

**Comment by larswmh** [comment]
@MikeMcC399 thanks for your comment. Capitalization and the first two iOS images were changed in my most recent commit. Due to a lack of assets, the iOS images were not included and now had to be manually made. The fifth screenshot in the iOS category is also supposed to be something completely different, but as a placeholder for now it displays the fourth image again. Android screenshots will also follow as soon as we get the missing assets for them. I've created the category already so I only have to paste the link later.

**Comment by MikeMcC399** [comment]
@larswmh 
I submitted PR https://github.com/corona-warn-app/cwa-website/pull/1742 to correct the capitalization of screenshot headings in English for CWA 2.9.

You may be able to cherry-pick https://github.com/MikeMcC399/cwa-website/commit/8f3916a383da95ebb91906644084adb20eb62656 from that PR to apply to 2.10, or maybe first wait until the PR is approved and merged.

**Comment by dsarkar** [comment]
The titles in screenshots-archive-2-9.json needs still to be updated (capitalised)

**Comment by dsarkar** [comment]
@MikeMcC399 @larswmh Thank you!

**Review by dsarkar — APPROVED** [review]

**Pull request merged**
