### PR TITLE
Fix missing images in PDF version of rC3 slides

### PR DESCRIPTION
**Pull request by tklingbeil**
Slides 15,16 and 18 were missing images due to overlays for animations in the original presentation.

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Obsolete with #750

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Obsolete with #750?

The pdfs are not the same, although the content looks the same. 

- The PDF from @tklingbeil https://github.com/corona-warn-app/cwa-website/pull/747/commits/5ee3157fca75bf438e58a27ebef0ea79048cd2ed was generated on macOS and the images fill the pages.
- The PDF from @HannaHei https://github.com/corona-warn-app/cwa-website/pull/750/commits/78fa295f5971213fec66c7cdbd9795e5ac36df64 was generated using Microsoft: Print to PDF and the images on the pages are smaller, so the slides are not so readable.

@tklingbeil and @HannaHei need to decide which is the final version to be published.

**Comment by MikeMcC399** [comment]
@tklingbeil @HannaHei
Are you going to resolve this PR?

**Comment by MikeMcC399** [comment]
@dsarkar 
If this PR is not going to be addressed, then it should be closed.

**Comment by heinezen** [comment]
Replaced by https://github.com/corona-warn-app/cwa-website/pull/990

**Pull request closed without merging**
