### PR TITLE
Paragraph validation FAQ

### PR DESCRIPTION
**Pull request by browkin**
- Added a paragraph in the FAQ DE & EN

**OLD:**
validationDeOld
validationEnOld

**NEW:**
validationDeNew
validationEnNew

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@browkin 

I know this is already merged, but for abbreviations in German you need to put a `&nbsp;`  not just a regular space between the letters, like `z.&nbsp;B.`.

**Comment by MikeMcC399** [comment]
@dsarkar 

Are you planning to correct this? If not, I can submit a PR to correct `z. B.` getting split across line breaks.

image

**Comment by dsarkar** [comment]
@MikeMcC399 go ahead, very much appreciated. Otherwise @browkin will do it tomorrow. As you wish! Thanks.

**Comment by MikeMcC399** [comment]
@dsarkar 
I will do it. No problem. I just did not want to duplicate anybody else's work.

**Comment by MikeMcC399** [comment]
@dsarkar 
Done in 
- PR https://github.com/corona-warn-app/cwa-website/pull/2275.

**Pull request merged**
