### PR TITLE
Fix list termination in FAQ error_log

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3229 "Wrongly terminated list in FAQ #error_log"

In the first unordered list (`<ul>`) in 

- https://www.coronawarn.app/en/faq/results/#error_log and
- https://www.coronawarn.app/de/faq/results/#error_log

the order of the closing tags is corrected to be `</li></ul>`.

### CODE REVIEW

**Review by MohamedZaghdoudi — COMMENTED** [review]
@MikeMcC399  Thank you for your deep search.

**Review by brianebeling — APPROVED** [review]
LGTM! Thank you

**Comment by MikeMcC399** [comment]
The checks are failing due to a network error:

```
npm ERR! URL: https://download.cypress.io/desktop/10.11.0?platform=linux&arch=x64
npm ERR! Error: Failed downloading the Cypress binary.
npm ERR! Response code: 524
```

**Comment by brianebeling** [comment]
> The checks are failing due to a network error:
> 
> ```
> npm ERR! URL: https://download.cypress.io/desktop/10.11.0?platform=linux&arch=x64
> npm ERR! Error: Failed downloading the Cypress binary.
> npm ERR! Response code: 524
> ```

Huh.. that is weird. Error 5XX are usually not on our end. I will try again in a bit.

**Pull request merged**
