### PR TITLE
View scroll images using lightbox on screenshots pages

### PR DESCRIPTION
**Pull request by brifemu**
With this PR we will be able to view scroll images clicking into the actual images from the screenshots pages. For that, we have to set the path of the scroll image in screenshots.json like here 

https://github.com/cuisines/cwa-website/blob/75f49bbe1030e33070aa435c037268422492b51b/src/data/screenshots.json#L28

### CODE REVIEW

**Comment by brifemu** [comment]
With this last commit, now we can 'zoom' the image, opening it in a new tab without alter the main page zoom. We can do it clicking on the zoom icon.

image

**Comment by Ein-Tim** [comment]
@brifemu 

Hey Brian, is this PR still relevant or can it be closed? Thanks for coming back to us!

**Comment by larswmh** [comment]
@Ein-Tim 

> Hey Brian, is this PR still relevant or can it be closed?

Sorry for the long silence on this PR. We're currently working on it and looking forward to implement this in the near future.

**Comment by dsarkar** [comment]
Will not be implemented.

**Pull request closed without merging**
