### PR TITLE
Science blog 4 EN

### PR DESCRIPTION
**Pull request by dsarkar**
Internal Tracking ID: [EXPOSUREAPP-10697](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10697)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@dsarkar 
Do you want feedback on this PR at the moment?
Could you explain what "on hold" means if that is relevant for a review?

**Comment by dsarkar** [comment]
Hi @MikeMcC399 This is ready for review. "On hold" because we still don't know the publishing date.

**Comment by MikeMcC399** [comment]
@dsarkar 
> This is ready for review. "On hold" because we still don't know the publishing date.

I will take a look at this. I noticed a few minor points. Also the number formatting is inconsistent concerning decimal and thousands separator.

I'm planning to submit a PR onto the cuisines fork. Due to the number formatting there will be quite a few changes which are inconvenient to add via comments. I've never done a PR for somebody else's fork before, so it will be a new experience. Stand by! 🙂

**Comment by dsarkar** [comment]
@MikeMcC399 thanks in advance for reviewing. Should you have trouble with the PR, we can move the branch to this repository (new PR). Let me know!

**Comment by MikeMcC399** [comment]
My PR is https://github.com/cuisines/cwa-website/pull/7.

There are two issues in figures which I did not address:

1. In Figure 2 "Number of donations (by operating system version)" the numerical day of the month has a dot (.) after it e.g. "8. Mar", which is a typical German format. There should be no dot in the date.
2. In Figure 7 "Participants by population density in urban and rural districts." "east" is written lower case, whereas "West" is written upper case. I suggest making "east" upper case to be consistent.

**Comment by MikeMcC399** [comment]
@dsarkar 
My inputs have now all been dealt with. Thank you for merging the PR https://github.com/cuisines/cwa-website/pull/7 into this branch.

**Pull request merged**
