### PR TITLE
Fix FAQ Link #vac_cert_booster

### LINKED ISSUE #3073: FAQ Link #vac_cert_booster does not display requested FAQ section on mobile device
## Where to find the issue

https://www.coronawarn.app/en/faq/#vac_cert_booster

## Describe the issue

If the FAQ link "For further information, please see our FAQ page." (https://www.coronawarn.app/en/faq/#vac_cert_booster) is followed in the CWA app under "Note on Booster Vaccination" and the mobile device is in portrait mode, then no useful information is shown in the web browser. Instead only top-level FAQ topics are shown.

### In app

Mobile device is connected via WLAN

1. Tap Scan and scan in a 2/2 vaccination certificate
2. Tap back-arrow
3. Tap Certificates
4. Tap right-arrow
5. Tap "Note on Booster Vaccination"
6. Tap on link at bottom of text to Rule DE-BNR-0110 "For further information, please see our FAQ page."
7. Note that browser first goes to https://www.coronawarn.app/en/faq/#vac_cert_booster then to https://www.coronawarn.app/en/faq/results/#vac_cert. The display however shows only topic sections.

Edit: The above steps work in CWA 2.25. Starting with CWA 2.26 the target link has changed and the steps no longer show the issue.

### In browser

1. Open Google Chrome on a desktop
2. Press F12 for developer mode
3. Toggle device toolbar and select Samsung Galaxy A51/71 in portrait mode with throttling set to Mid-tier mobile
4. Paste https://www.coronawarn.app/en/faq/#vac_cert_booster into address field and press `Enter`
5. Note that only section headers are shown and these do not lead to information about vaccination certificate boosters.

image

## Expectation

When using the link on a mobile device to open https://www.coronawarn.app/en/faq/#vac_cert_booster, the section FAQ > App Features > Vaccination Certificates should be shown.

vac_cert

## Workarounds

1. The following is not a useful work around in practice, however it shows that the issue is with the website in portrait mode.<br>In the app "Steps to reproduce" above, before tapping on the link "For further information, please see our FAQ page.", turn the mobile device into landscape mode.
2. Scroll up to search field. Enter word "booster", select section "App Features", tap "Search". Scroll down to search results.

## Background information

Before the FAQs were reorganized, the link https://www.coronawarn.app/en/faq/#vac_cert_booster displayed a list of links:

old-vac_cert_booster

This list was removed and the nearest equivalent was the section heading above this list which is https://www.coronawarn.app/en/faq/#vac_cert.

---
Internal Tracking ID: [EXPOSUREAPP-14102](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14102)

### PR DESCRIPTION
**Pull request by brifemu**
This PR fixes #3073. We have replaced the redirect link from "vac_cert_booster" to "vac_booster_basics"

---
Internal Tracking ID: [EXPOSUREAPP-14102](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14102)

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Review by brianebeling — APPROVED** [review]

**Comment by MikeMcC399** [comment]
Please don't merge this until I have an opportunity to check it. I'm not sure that it fixes the underlying problem and it may break the Cypress tests.

**Comment by MikeMcC399** [comment]
Redirecting #vac_cert_booster to #vac_booster_basics (an individual article, not section header) works around the reported issue, however it does not address the underlying issue, which is a fault in displaying a section on a mobile device which has been requested through a redirect.

The underlying problem continues to exist and can be seen by selecting https://www.coronawarn.app/en/faq/#vac_booster. This redirects to https://www.coronawarn.app/en/faq/#vac_cert and displays incorrectly on a mobile device in portrait mode.

**Comment by larswmh** [comment]
@MikeMcC399 

> Redirecting #vac_cert_booster to #vac_booster_basics (an individual article, not section header) works around the reported issue, however it does not address the underlying issue, which is a fault in displaying a section on a mobile device which has been requested through a redirect.
> 
> The underlying problem continues to exist and can be seen by selecting https://www.coronawarn.app/en/faq/#vac_booster. This redirects to https://www.coronawarn.app/en/faq/#vac_cert and displays incorrectly on a mobile device in portrait mode.

We understand that this does not fix the underlying technical issue but we would want to merge this now anyway to "fix this" for now. As the technical issue remains, we will still look into it and fix it soon.

**Comment by MikeMcC399** [comment]
It seems that this PR was merged without running the Cypress test suite. https://github.com/corona-warn-app/cwa-website/blob/master/README.md#testing says "To minimize the occurrence of errors we would ask you to perform all tests when contributing to our repository"

- See issue #3146

**Pull request merged**
