### PR TITLE
Replace interactive figs on mobile for images

### PR DESCRIPTION
**Pull request by brifemu**
In this PR I have solved the issue #1436 replacing interactive figs for static images using CSS classes and media queries to detect device resolution.

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Review by Ein-Tim — COMMENTED** [review]
I just tested these changes on my iPhone XR and I can only support what @MikeMcC399 said, the figs should be static in landscape-mode too. 
In horizontal-mode everything is visible nicely, as there the figs are shown as images.

**Comment by MikeMcC399** [comment]
The Plotly controls are quite difficult to select with a finger on a touch screen.

Do they conform to the recommendation on https://material.io/design/usability/accessibility.html#layout-and-typography
that touch controls should be at least 48 x 48 dp (44 x 44 pt for iOS)?

This might be another reason to go for static Plotly graphs only on mobile devices.

For a desktop browser, it's no problem to access them with a mouse.

**Review by Ein-Tim — APPROVED** [review]
Retested on iPhone XR based on the latest commit ([`e22dc9c` (#1934)](https://github.com/corona-warn-app/cwa-website/pull/1934/commits/e22dc9c9a1f4e1645e80916fb511287a37768b7e)). 

Works flawless now in landscape and portrait mode! 

Thank you @brifemu!

**Comment by brifemu** [comment]
Tested on Realme 7 without problems. Also tested on an Airpad A1475, still interactive on tablet

**Pull request merged**
