### PR TITLE
Add FAQs from issue #2184

### PR DESCRIPTION
**Pull request by thorbenkuro**
In this PR, I have added the FAQs mentioned on #2184 and added links to the FAQ-entry red_card_how_to_test

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@thorbenkuro 

This PR changes more than just the FAQ. You should probably rebase your changes on the current master branch.

**Review by MikeMcC399 — CHANGES_REQUESTED** [review]
I would not expect this PR to change the following files:

•	A src/assets/img/icons/instagram_white32x32.svg (3) 
•	A src/assets/img/icons/twitter_white32x32.svg (3) 
•	M src/assets/scss/_header.scss (25) 
•	M src/assets/scss/_variables.scss (2) 
•	M src/data/global.json (32)

**Comment by dsarkar** [comment]
continues here https://github.com/corona-warn-app/cwa-website/pull/2188

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for comment.

**Pull request closed without merging**
