### PR TITLE
FAQ Event registration - index - use bullet points

### PR DESCRIPTION
**Pull request by dsarkar**

### CODE REVIEW

**Comment by dsarkar** [comment]
image

**Comment by dsarkar** [comment]
image

**Comment by MikeMcC399** [comment]
Some lines are missing bullet points e.g. "Does everyone who scanned the same QR code get a warning?"

**Comment by dsarkar** [comment]
@MikeMcC399 The questions with one bullet point are similar, the have the same answer text

**Comment by MikeMcC399** [comment]
@dsarkar 

I see the problem.

Maybe make each question a separate entry, even if the target is the same?

For example from:
`<ul><li><a href='../faq/#check_in_qr_warning' target='_self' rel='noopener noreferrer'>What is the procedure in case of a positive result?<br>Does everyone who scanned the same QR code get a warning?<br>What exactly needs to happen in this new feature for users who have checked into a specific location to be warned through the app?</a></li><li>`

to:
`<ul><li><a href='../faq/#check_in_qr_warning' target='_self' rel='noopener noreferrer'>What is the procedure in case of a positive result?</a></li><li>`

`<ul><li><a href='../faq/#check_in_qr_warning' target='_self' rel='noopener noreferrer'>Does everyone who scanned the same QR code get a warning?</a></li><li>`

`<ul><li><a href='../faq/#check_in_qr_warning' target='_self' rel='noopener noreferrer'>What exactly needs to happen in this new feature for users who have checked into a specific location to be warned through the app?</a></li><li>`

**Comment by MikeMcC399** [comment]
@dsarkar 
You could also simplify the hyperlinks by changing all instances of the relative link from `../faq/#` to simply `#` as the hyperlinks are already in the faq directory.

**Comment by dsarkar** [comment]
image

**Pull request merged**
