### PR TITLE
Release/2.21 Updates

### PR DESCRIPTION
**Pull request by dsarkar**
- [x] Gulpfile
- [x] Screenshots
https://github.com/corona-warn-app/cwa-website/pull/2687
- [x] Privacy Notices 2.21
https://github.com/corona-warn-app/cwa-website/pull/2542
- [x] Blog
- [x] new blog articles need to be added to the sitemap files.
- [x] FAQ

---
**Release 2.21**
- Blog
  - DE https://www.coronawarn.app/de/blog/2022-04-19-cwa-2-21/
  - EN https://www.coronawarn.app/en/blog/2022-04-19-cwa-2-21/
- Screenshots
  - DE https://www.coronawarn.app/de/screenshots/ 
  - EN  https://www.coronawarn.app/en/screenshots/
- Privacy notice R 2.21. (Previous update was R 2.19)
  - DE https://www.coronawarn.app/de/privacy/
  - EN https://www.coronawarn.app/en/privacy/ 
- FAQ (new or updated)
   - DE **Was mache ich, wenn ich mehrere PCR-Test-QR-Codes habe?**
https://www.coronawarn.app/de/faq/results/#QRcodes
  - EN **What to do with several PCR-Test QR codes?**
https://www.coronawarn.app/en/faq/results/#QRcodes
  - DE **Können mehrere Tests registriert werden?**
https://www.coronawarn.app/de/faq/results/#in_a_nutshell
  - EN **Can multiple tests be registered?**
https://www.coronawarn.app/en/faq/results/#in_a_nutshell
  - DE **Kann ich mehrere Schnelltests speichern/verwalten?**
https://www.coronawarn.app/de/faq/results/#rat_multiple_rat
  - EN **Can I save/manage multiple rapid antigen tests?**
https://www.coronawarn.app/en/faq/results/#rat_multiple_rat

   
**Other new or updated content (Not related to  release 2.21 )**
- Removed button on main webpage to
  - DE **Schnelltestpartner werden!**
  https://www.coronawarn.app/de/rat-partner/
  - EN **Become a rapid test partner!**
  https://www.coronawarn.app/en/rat-partner/
- Updated:
  - DE **In welchen internationalen App Stores ist die App verfügbar?**
https://www.coronawarn.app/de/faq/results/#international
  - EN **In which international app stores is the app available?**
https://www.coronawarn.app/en/faq/results/#international
- New:
  - DE **Das öffentliche Dashboard der Corona-Warn-App zählt neuerdings rückwirkend für den Zeitraum seit August 2021 deutlich weniger PCR-Tests als zuvor. Warum?**
https://www.coronawarn.app/de/faq/results/#dashboard_pcr_tests
  - EN **The Corona-Warn-App's public dashboard has recently been counting significantly fewer PCR tests retroactively for the period since August 2021 than before. Why?**
https://www.coronawarn.app/en/faq/results/#dashboard_pcr_tests
- New:
  - DE **Fehlermeldung 'DCC_RI_429'**
https://www.coronawarn.app/de/faq/results/#dcc_ri_429
  - EN **Error 'DCC_RI_429'**
https://www.coronawarn.app/en/faq/results/#dcc_ri_429
- Updated
  - DE **Fragen und Antworten zur Zertifikatsprüfung bei Ticketbuchungen**
https://www.coronawarn.app/de/faq/results/#val_service_basics
  - EN **Questions and answers about certificate verification during ticketing**
https://www.coronawarn.app/en/faq/results/#val_service_basics
- Removed, redirected to #val_service_basics:
  - DE **Warum erhalte ich die Meldung, dass kein geeignetes Zertifikat vorhanden ist?**
  https://www.coronawarn.app/de/faq/results/#val_service_no_valid_dcc
  - EN **Why do I get the message that there is no suitable certificate**
  https://www.coronawarn.app/en/faq/results/#val_service_no_valid_dcc
- Removed, redirected to #val_service_basics :
  - DE **Warum ist mein Zertifikat nicht prüfbar oder wird nicht anerkannt?**
https://www.coronawarn.app/de/faq/results/#val_service_result
  - EN **Why is my certificate not verifiable or not recognized?**
https://www.coronawarn.app/en/faq/results/#val_service_result
- Updated (valid for both, Android and iOS)
  - DE **Warum werden seit Version 2.19 weniger Schlüssel in den Begegnungsaufzeichnungen abgeglichen?**
https://www.coronawarn.app/de/faq/results/#delta_submission 
  - EN **Why are fewer keys matched since version 2.19?**
https://www.coronawarn.app/en/faq/results/#delta_submission 
- Updated (Switzerland)
  - DE **In welchen Ländern kann die Corona-Warn-App genutzt werden?**
https://www.coronawarn.app/de/faq/results/#interoperability_countries
  - EN **In which countries can the Corona-Warn-App be used?**
https://www.coronawarn.app/en/faq/results/#interoperability_countries
- New
  - DE **[Apple/iOS]: Was sind die Voraussetzungen für die Installation der Corona-Warn-App auf einem iPhone?**
https://www.coronawarn.app/de/faq/results/#ios_install_requirements
  - EN **[Apple/iOS]: What are the requirements for installing the Corona-Warn-App on an iPhone?**
https://www.coronawarn.app/en/faq/results/#ios_install_requirements

**In preparation:**

- Luca app related articles removed, redirected to #.....
  - EN
    - Can luca also read and process QR codes from the Corona-Warn-App?
    - Can users of the luca app be alerted if CWA users test positive?
    - Can all QR codes for check-in be read immediately by the Corona-Warn-App and the luca app?
    - How does the collaboration between the Corona-Warn-App and luca work?
    - Do app users need to change settings on their smartphones?
    - What happens when QR codes are scanned by the Corona-Warn-App?
    - How else do the Corona-Warn-App and luca app differ when it comes to check-in/event registration?
    - Why was joint use implemented?
    - Why is luca QR code joint use coming now?
    - Is the data of the users of the Corona-Warn-App still secure?
    - What data is transferred from the CWA to luca?
    - Do we now only need one app for event registration?
    - Do users need to install both apps for it to work?
  - DE
    - Kann auch luca die QR-Codes der Corona-Warn-App lesen und verarbeiten?
    - Können Nutzende der luca-App gewarnt werden, wenn CWA-Nutzende positiv getestet wurden?
    - Können alle QR-Codes zum Check-in sofort von der Corona-Warn-App und der luca-App gelesen werden?
    - Wie funktioniert die Zusammenarbeit von der Corona-Warn-App und luca?
    - Müssen Nutzende der Apps Einstellungen auf ihren Smartphones verändern?
    - Was passiert beim Scan der QR-Codes durch die Corona-Warn-App?
    - Wie unterscheiden sich die Corona-Warn-App und luca-App beim Check-in/der Eventregistrierung noch?
    - Warum wurde die Mitnutzung umgesetzt?
    - Warum kommt die Mitnutzung der luca-QR-Codes jetzt?
    - Sind die Daten der Nutzenden der Corona-Warn-App weiterhin sicher?
    - Welche Daten werden von der CWA an luca übertragen?
    - Braucht man nur noch eine App für die Eventregistrierung?
    - Müssen Nutzende beide Apps installieren, damit es funktioniert? 
- Luca app related articles updated
  - EN
    - Is it possible to check in using the CWA to scan Event QR codes from other apps?
    - Can the Corona-Warn-App read and process the QR codes from Luca?
  - DE
    - Kann man mit der CWA einchecken, indem man Event-QR-Codes anderer Apps scannt?
    - Kann die Corona-Warn-App die QR-Codes von luca lesen und verarbeiten?

---
Internal Tracking ID: [EXPOSUREAPP-12585](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12585)

### CODE REVIEW

**Comment by Ein-Tim** [comment]
FYI: I provided PR #2764 which removes the DCC ticketing screenshots. It should be merged into this branch.

**Comment by MikeMcC399** [comment]
@dsarkar 

It seems that the sitemap files now have to be manually maintained:

- [src/data/sitemap.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/sitemap.json)
- [src/data/sitemap_de.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/sitemap_de.json)

So, when 2.21 is released and a blog article is published, then entries for the new blog articles would need to be added to the sitemap files. Depending on how you handle this in your release process, you might want to add this task to this PR.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for pointing this https://github.com/corona-warn-app/cwa-website/pull/2677#issuecomment-1101188657 out. Do you want to provide a PR targeting this branch for updating sitemap.json ? (Or @Ein-Tim ?)

**Comment by MikeMcC399** [comment]
@dsarkar 
> Do you want to provide a PR targeting this branch for updating sitemap.json ? 

The changes to the sitemap need to be bundled either with the blog announcement or in a PR which is merged **after** the blog is merged.

This PR does not currently contain the blog announcement, so it would be risky to change sitemap.json without having the blog available. Also without the blog, the title is unknown.

So, in short, the answer is NO at this time, because I can't do it with a reliable outcome.

I could do it after the blog is published, but I think this is really an Open Source Team responsibility. Nevertheless please let me know if you want support for this.

**Comment by dsarkar** [comment]
@MikeMcC399 FYI - We will merge this PR after the blog PR.

**Comment by MikeMcC399** [comment]
@dsarkar 
>  FYI - We will merge this PR after the blog PR.

I see now that there were already links to the unpublished blog in the FAQs, so the same information can be used in the sitemap. You've already done that now anyway in https://github.com/corona-warn-app/cwa-website/pull/2677/commits/bbd8deaae26acdf4226522ca0f4fd82511101819. 👍🏻

**Pull request merged**
