### PR TITLE
Migrate cwa-website to use node16

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR follows on from issue https://github.com/corona-warn-app/cwa-website/issues/2155 "Website migration steps for Nodejs 16" and implements the steps required to migrate this repository to use Nodejs version 16.

The Nodejs version selected is `lts/gallium` which is equivalent to the cached version 16.13.2 specified in the [Ubuntu 20.04.3 LTS - Readme](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#nodejs)

I have tested it locally on Ubuntu 20.04 and Windows 11 with the Cypress test suite.

I also tested the workflows on a private clone of the repository. The only portion I cannot test is the final deployment in [deploy-master.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml) using `jakejarvis/s3-sync-action@master`.

---
Internal Tracking ID: [EXPOSUREAPP-10928](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10928)

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Hi Mike, thanks for this PR! I have some questions: 

Could you elaborate on the consequences for contributors? Do I need to update to node16 manually when this change is merged? Anything else I should note with node16?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thank you for your questions.

If you continue to use Nodejs 14 you will get a warning if you run `npm install`:

`npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
`

You can still use the commands to build and run the web locally,
```
npm run build
npm start
```

For anybody who is contributing only text inputs to the repository, they could continue to use Nodejs 14 in the interim, however it would be recommended to update to Nodejs 16 at some time.

Anyone who is updating package versions or doing more technical work should probably update to Nodejs 16 before making any significant contributions.

**Comment by Ein-Tim** [comment]
Okay, thanks for the explanations @MikeMcC399!

**Comment by MikeMcC399** [comment]
The PR is now up-to-date with the `master` branch and all npm modules are up-to-date according to the version specifications in `package.json` as well.

```
$ npm outdated
Package          Current  Wanted  Latest  Location                      Depended by
autoprefixer       9.8.8   9.8.8  10.4.1  node_modules/autoprefixer     cwa-website
cypress            7.7.0   7.7.0   9.2.0  node_modules/cypress          cwa-website
gulp-imagemin      7.1.0   7.1.0   8.0.0  node_modules/gulp-imagemin    cwa-website
gulp-postcss       8.0.0   8.0.0   9.0.1  node_modules/gulp-postcss     cwa-website
gulp-sitemap       7.7.0   7.7.0   8.0.0  node_modules/gulp-sitemap     cwa-website
gulp-sourcemaps    2.6.5   2.6.5   3.0.0  node_modules/gulp-sourcemaps  cwa-website
js-yaml           3.14.1  3.14.1   4.1.0  node_modules/js-yaml          cwa-website
marked             2.1.3   2.1.3   4.0.9  node_modules/marked           cwa-website
node-fetch         2.6.6   2.6.6   3.1.0  node_modules/node-fetch       cwa-website
node-sass          6.0.1   6.0.1   7.0.1  node_modules/node-sass        cwa-website
screenfull         5.2.0   5.2.0   6.0.0  node_modules/screenfull       cwa-website
webpack           4.46.0  4.46.0  5.65.0  node_modules/webpack          cwa-website
webpack-stream     5.2.1   5.2.1   7.0.0  node_modules/webpack-stream   cwa-website
yargs             15.4.1  15.4.1  17.3.1  node_modules/yargs            cwa-website


```

**Comment by MikeMcC399** [comment]
In the meantime Node `lts/gallium` equates to Node 16.13.2 (previously 16.13.1) and this is cached in [GitHub's virtual environment Ubuntu 20.04.3 LTS](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#nodejs).

Also there are some new minor versions of some npm packages.

If there is interest in pursuing this PR I will update and test it with the newer patches and minor versions, otherwise I leave it as it is.

**Comment by dsarkar** [comment]
@MikeMcC399 Indeed, there is interest in pursuing this PR! Thanks!

**Comment by MikeMcC399** [comment]
@dsarkar 
> Indeed, there is interest in pursuing this PR!

That is good to hear! I will update the PR soon in that case (rebase / re-install / re-test).

**Comment by MikeMcC399** [comment]
@dsarkar 
This PR is updated. It still passes the Cypress test suite with
`$ npm test`
on Ubuntu 20.04.

**Comment by MikeMcC399** [comment]
Rebased once again to resolve conflicts with `master` branch.

**Comment by svengabr** [comment]
Oh damn @MikeMcC399 I just did a manual merge conflict as well, currently looking into getting it running with node16

**Comment by MikeMcC399** [comment]
@svengabr 

> Oh damn @MikeMcC399 I just did a manual merge conflict as well, currently looking into getting it running with node16

Do you want me to force push again?

Sorry that we were working in parallel!

**Comment by svengabr** [comment]
@MikeMcC399 you can continue what you were working on. I wanted to fix the merge conflict and then test it using 

```
nvm install 16.13.2
nvm use 16.13.2
npm ci
npm run build
```

After that, I wanted to have it deployed to the non-productive test environment for a quick review

**Comment by MikeMcC399** [comment]
@svengabr 
Stand by. I will post (hopefully) positive results from cypress test.

**Comment by MikeMcC399** [comment]
@svengabr 

> I wanted to fix the merge conflict and then test it using
>
```
nvm install 16.13.2
nvm use 16.13.2
npm ci
npm run build
```
> After that, I wanted to have it deployed to the non-productive test environment for a quick review

It would be good to run those tests manually, however in fact they are already checked automatically (see https://github.com/corona-warn-app/cwa-website/pull/2282/checks).

To your test suite, I suggest to add:

```
npm run test:prepare
npm test
```

to run the Cypress test suite.

I just did that, with the following result:

<pre>    <font color="#555753">Spec</font>                                              <font color="#555753">Tests</font>  <font color="#555753">Passing</font>  <font color="#555753">Failing</font>  <font color="#555753">Pending</font>  <font color="#555753">Skipped</font> <font color="#555753"> </font>
<font color="#555753">  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐</font>
<font color="#555753">  │</font> <font color="#4E9A06">✔</font>  applink_spec.js                          <font color="#555753">00:02</font>        3        <font color="#4E9A06">3</font>        <font color="#555753">-</font>        <font color="#555753">-</font>        <font color="#555753">-</font> <font color="#555753">│</font>
<font color="#555753">  ├────────────────────────────────────────────────────────────────────────────────────────────────┤</font>
<font color="#555753">  │</font> <font color="#4E9A06">✔</font>  blog_spec.js                             <font color="#555753">00:03</font>        2        <font color="#4E9A06">2</font>        <font color="#555753">-</font>        <font color="#555753">-</font>        <font color="#555753">-</font> <font color="#555753">│</font>
<font color="#555753">  ├────────────────────────────────────────────────────────────────────────────────────────────────┤</font>
<font color="#555753">  │</font> <font color="#4E9A06">✔</font>  check_anchor_links.js                    <font color="#555753">01:26</font>       31       <font color="#4E9A06">31</font>        <font color="#555753">-</font>        <font color="#555753">-</font>        <font color="#555753">-</font> <font color="#555753">│</font>
<font color="#555753">  ├────────────────────────────────────────────────────────────────────────────────────────────────┤</font>
<font color="#555753">  │</font> <font color="#4E9A06">✔</font>  check_links.js                           <font color="#555753">15:07</font>       31       <font color="#4E9A06">31</font>        <font color="#555753">-</font>        <font color="#555753">-</font>        <font color="#555753">-</font> <font color="#555753">│</font>
<font color="#555753">  ├────────────────────────────────────────────────────────────────────────────────────────────────┤</font>
<font color="#555753">  │</font> <font color="#4E9A06">✔</font>  hotline_spec.js                          <font color="#555753">915ms</font>        1        <font color="#4E9A06">1</font>        <font color="#555753">-</font>        <font color="#555753">-</font>        <font color="#555753">-</font> <font color="#555753">│</font>
<font color="#555753">  ├────────────────────────────────────────────────────────────────────────────────────────────────┤</font>
<font color="#555753">  │</font> <font color="#4E9A06">✔</font>  pages/eventRegistration.js               <font color="#555753">00:10</font>        6        <font color="#4E9A06">6</font>        <font color="#555753">-</font>        <font color="#555753">-</font>        <font color="#555753">-</font> <font color="#555753">│</font>
<font color="#555753">  └────────────────────────────────────────────────────────────────────────────────────────────────┘</font>
<font color="#555753">   </font> <font color="#4E9A06">✔</font>  <font color="#4E9A06">All specs passed!</font>                        <font color="#555753">16:51</font>       74       <font color="#4E9A06">74</font>        <font color="#555753">-</font>        <font color="#555753">-</font>        <font color="#555753">-</font> <font color="#555753"> </font>

</pre>

```
$ node -v
v16.13.2
```

**Comment by MikeMcC399** [comment]
@svengabr 
Ready for you again. 🙂

**Comment by svengabr** [comment]
@MikeMcC399 looks all good to me. Is anything missing from your side/any open tasks or can we consider merging into `main`?

**Comment by MikeMcC399** [comment]
@svengabr 
>  Is anything missing from your side/any open tasks or can we consider merging into `main`?

There are no open tasks on my side, so you are welcome to go ahead and merge into `master`.

**Comment by MikeMcC399** [comment]
Set to draft and waiting for a convenient time to update the website to use Nodejs 16.

**Review by dsarkar — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@svengabr / @dsarkar 

I did update this yesterday. Does this mean that you are ready to go with it?

**Comment by svengabr** [comment]
@MikeMcC399
Yes, we are ready to go with it. Golive is planned for tomorrow morning.

**Comment by MikeMcC399** [comment]
@svengabr 
> Yes, we are ready to go with it. Golive is planned for tomorrow morning.

Thank you for letting me know. I will not touch the PR unless you ask me to. I have retested the current contents on Ubuntu and Windows 11 successfully.

@Ein-Tim 
Thank you for the Slack link. I stopped following Slack because at the time there was very little active involvement from the Open Source Team. If that has now changed I will start following again.

**Comment by Ein-Tim** [comment]
@svengabr I can offer to test this on my Mac Book Air running the latest macOS version.

@MikeMcC399 
For sure! This was the first message in a long time from @svengabr on Slack, so I don't know whether there will be more frequent posts from him again. 

If I test this PR, I'd need to install node16, right?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> If I test this PR, I'd need to install node16, right?

Yes, you need node 16 to test with node 16 😆 

Conversation continued in Slack....

**Review by Ein-Tim — COMMENTED** [review]
This change breaks building the page locally on M1 MacBook. 

The terminal says:
`Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Node.js 16.x`

In https://github.com/sass/node-sass/issues/3033 you can read that Node Saas does not yet supports Apple ARM. 

However, it seems like I can continue using Node.js version 14.18.3 without having any difficulties to build the page. I'm not even seeing a warning message like the one @MikeMcC399 posted above. 

So from my POV, this is not an optimal change, however, I also won't block it.

**Comment by Ein-Tim** [comment]
I just started to wonder: Aren't we already using Node Saas currently? 

If yes, I wonder why I only see this message when testing this PR and not when building the `main` branch. 🤔

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Your error message is part of the problem that Node Sass is deprecated (see https://www.npmjs.com/package/node-sass).

"**node-sass**

Warning: [LibSass and Node Sass are deprecated](https://sass-lang.com/blog/libsass-is-deprecated). While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto [Dart Sass](https://sass-lang.com/dart-sass)."

I'm sorry that I didn't realise that macOS users like yourself could be impacted.

It is possible to migrate to [Dart Sass](https://sass-lang.com/dart-sass) but this means some other technical changes to the website. I did try it out a couple of months ago and I would have suggested it at the time if it had been 100% compatible.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> I'm sorry that I didn't realise that macOS users like yourself could be impacted.

No problem. As stated above, this is not optimal for me, but I will just continue to use Node.js 14.18.3. I hope this works!

**Comment by svengabr** [comment]
Delaying a little bit (later today) until I have internal results using a M1 macbook

**Comment by svengabr** [comment]
A colleague just tested using an M1 Macbook with NodeJS 16 and everything worked as intended with no errors. From my perspective, we are good to go.

**Comment by Ein-Tim** [comment]
I wonder what caused this error then.
Feel free to merge already, I will retest later with a clean fork of cwa-website and a new install of nvm.

**Review by svengabr — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@Ein-Tim 
>  I will retest later with a clean fork of cwa-website and a new install of nvm.

That would be helpful. I suggest to open a new issue to look at this after this PR is merged.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I suggest to begin with just do:

```
git switch master
git fetch upstream
git merge upstream/master
npm ci
npm run build

```
without upgrading to nvm 16.

That seems to be no problem on Windows at least.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I'll try this now.

**Comment by Ein-Tim** [comment]
FYI: I will follow up in https://github.com/corona-warn-app/cwa-website/issues/2411.

**Pull request merged**
