### PR TITLE
blog 5 fig fix

### PR DESCRIPTION
**Pull request by browkin**
- Fixed last 3 figures in blog 5 and made them interactive

Figures that were affected: 
1plotly

2plotly

3plotly

### CODE REVIEW

**Review by larswmh — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@browkin 
The graph x-axis covers the years 2020, 2021 and 2022 however the labels do not include the year, so they are unclear.

Could you add the year to the axis labels?

**Comment by dsarkar** [comment]
@MikeMcC399 We will have a look at this.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for testing. We will address the x-axis issue in another PR.

**Comment by MikeMcC399** [comment]
@dsarkar 
Thanks for letting me know that the x-axis issue will be looked at!

**Pull request merged**
