### PR TITLE
Updated the FAQ according to #339 

### PR DESCRIPTION
**Pull request by mtb77**
as Android devices are now exporting more then 100 entries since end of August.

### CODE REVIEW

**Review by MarlisFriedl — COMMENTED** [review]
see also text suggestion in / update also https://github.com/corona-warn-app/cwa-faq/issues/337 accordingly

**Comment by MikeMcC399** [comment]
@MarlisFriedl 
> see also text suggestion in / update also [corona-warn-app/cwa-faq#337](https://github.com/corona-warn-app/cwa-faq/issues/337) accordingly

The link https://github.com/corona-warn-app/cwa-faq/issues/337 doesn't work for me (404 error). Maybe it's a private repository?

**Comment by MikeMcC399** [comment]
Regarding the proposed text change:
"The log limit of 100 entries on Android devices has been recently removed by Google with a configuration change at the end of August 2020."

I'm not convinced that the limit was brought about by a configuration change, however I am unable to prove otherwise! Given that we don't really know,  I would remove the text "with a configuration change" making the text instead:

"The log limit of 100 entries on Android devices has been recently removed by Google at the end of August 2020."

If Google reveals at some time how they made the change, the FAQ entry could be updated accordingly.

**Comment by MarlisFriedl** [comment]
@MikeMcC399 Hi Mike, yes you're right. We use it to prepare updates that we see coming. All changes are then done only publicly in cwa-website.

**Pull request merged**
