### PR TITLE
Added an paragraph about the commission adopted rules to FAQ #vac_booster_jj

### PR DESCRIPTION
**Pull request by browkin**
- Added to DE & EN

**Deutsch:**
comissionDE

**English:**
commissionEN

### CODE REVIEW

**Review by MikeMcC399 — CHANGES_REQUESTED** [review]
@browkin 

I suggest that you write at the top:
"UPDATE December 30, 2021" in bold
like used on https://www.coronawarn.app/en/faq/#minimum_requirements
(avoid stating dates numerically in English because they are locale dependent).

Also to follow the example of https://www.coronawarn.app/de/faq/#minimum_requirements write
"AKTUELL 30. Dezember 2021" in bold

----
For the external links with `target='_blank'` add `rel='noopener noreferrer'` for security with older browsers.

**Comment by MikeMcC399** [comment]
This is related to issue #2240.

**Comment by MikeMcC399** [comment]
This is the best practice reference:
https://web.dev/external-anchors-use-rel-noopener/

It probably should be added to the website documentation so that all contributors are creating hyperlinks consistently.

**Review by MikeMcC399 — APPROVED** [review]
@browkin 
Thank you for taking account of my suggestions.
It looks fine now!

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reviewing !

**Pull request merged**
