### PR TITLE
Workflow for check_links

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR creates a workflow `.github/workflows/test-check_links.yml` which runs the Cypress test [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js) to check hyperlinks which are not anchors.

The test is run weekly every Monday at 03:15 UTC and on demand.

The workflow does not have a `pull_request` trigger because the success of the test relies in many cases on the correct performance of external third-party websites over which cwa-website has no control. Any failure needs to be followed up manually and should not result in a CI failure of any PR. Also the test takes much longer to run than any other of the Cypress tests. (Tests in a fork showed that it typically runs for approximately 18 minutes when successful.)

If the test fails then log files are uploaded as artifacts to aid in troubleshooting.

~~It is currently draft status only. It may need some more tuning to remove any websites which prove to be too unreliable.~~

This is a follow-on from previous PRs https://github.com/corona-warn-app/cwa-website/pull/3384 and https://github.com/corona-warn-app/cwa-website/pull/3399.

image

image

---
Internal Tracking ID: [EXPOSUREAPP-14844](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14844)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Unfortunately https://support.apple.com/ is causing issues and timing out.

I ran the workflow 3 times and it was successful only 1 time. This is not enough to put this workflow into production.

The issue is with the `check_links` test. I suspect that some sites are switching into attack protection mode and refuse connects when they are checked too often, too fast.  `check_links` does not remember which links it has already tested and will just repeat the tests.

**Comment by MikeMcC399** [comment]
Additional exclusion added for instragram.

Retesting

**Comment by MikeMcC399** [comment]
Unfortunately this test is still too flaky 🙁 !

It ran locally successfully 3 times.
On GitHub it ran once, then failed checking 

```
Method: GET
URL: https://support.apple.com/guide/iphone/supported-iphone-models-iphe3fa5df43/ios

No response was received within the timeout.
```

I proposed to enhance [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js) to allow the definition of domains to skip checking instead of complete URLs. I will open a separate issue for this and hopefully I can manage the JavaScript changes to implement it!

**Comment by MikeMcC399** [comment]
- Now waiting for merge of PR #3404. Then I will rebase, retest and request review.

**Comment by MikeMcC399** [comment]
- The improvements made in https://github.com/corona-warn-app/cwa-website/pull/3404 have made this workflow successful.

I ran the workflow in my fork successfully three times today. The run durations were

Job | Duration mm:ss
--- | ---
19 | 20:44
20 | 20:49
21 | 16:52

This issue is now ready for review.

**Review by larswmh — APPROVED** [review]
Thanks for the PR @MikeMcC399, it's great to see this workflow running flawlessly now! We appreciate your efforts to make this run

**Comment by MikeMcC399** [comment]
@larswmh 

Thank you for your comments and merging! It took quite a few steps to clear the way to get this to run.

I will submit a PR for the markdown links suggestion now and when that is all done I will make some suggestions to update the documentation.

**Comment by MikeMcC399** [comment]
The first scheduled run of https://github.com/corona-warn-app/cwa-website/actions/workflows/test-check_links.yml, yesterday, Monday, Feb 27, 2023, was successful 👍🏻 !

Run [4278566160](https://github.com/corona-warn-app/cwa-website/actions/runs/4278566160) completed after 18m 28s.

**Pull request merged**
