### PR TITLE
[WIP] Move resolved FAQ entries to Markdown file

### PR DESCRIPTION
**Pull request by heinezen**
As discussed in https://github.com/corona-warn-app/cwa-website/pull/789#issuecomment-778148998

### CODE REVIEW

**Comment by Ein-Tim** [comment]
These FAQ entry won't be live anymore on the website, or?

**Comment by dsarkar** [comment]
@heinezen @Ein-Tim 

Several ideas:

1. Simplify entries with "UPDATE"s, e.g. https://www.coronawarn.app/en/faq/#ENError13 and then add a link to the old version in the .md file
2. Min iOS version is CWA 1.5.3 (Android currently 1.0.4, but probably will also be 1.5.1). So move articles out to md file, again with link.

**Comment by heinezen** [comment]
**Update**

We are currently discussing several approaches for handling the resolved section, particularly whether it should be moved to the Github repo or some other location that is easier to see. We will try to find a way to keep only the relevant information in the main FAQ and store the outdated information in another place (transparently of course)

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
What's the current status here?

**Review by Ein-Tim — COMMENTED** [review]
I think this PR should finally be closed. The CWA team seems to be working on an updated FAQ which will be better to navigate through and not show all the resolved entries until the user selects them.

cc @heinezen @dsarkar @svengabr

**Pull request closed without merging**
