### PR TITLE
Change video alt to aria-label in science and sign-language

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3242 "Illegal alt attribute for other videos".

For the `<video>` tags on the following pages, the `alt` attributes are changed to an `aria-label` attribute. This enables a screen reader such as Windows Narrator to read out the text property of the `aria-label`.

These are the pages affected:

- https://www.coronawarn.app/en/science/2021-06-15-science-blog-1/
"What is the purpose of evaluating the CWA and what aspects play a role in the evaluation?"

- https://www.coronawarn.app/de/science/2021-06-15-science-blog-1/
"Über die Wirksamkeit und den Nutzen der Corona-Warn-App"

- https://www.coronawarn.app/de/sign-language/ "Gebärdensprache" (also one typo on this page is corrected)

### Validator

Run https://validator.w3.org on 

- https://www.coronawarn.app/en/science/2021-06-15-science-blog-1/ (3 videos)
- https://www.coronawarn.app/de/science/2021-06-15-science-blog-1/ (2 videos)
- https://www.coronawarn.app/de/sign-language/ (1 video)
  
and ensure that the following video-related error message is no longer produced:

- "Attribute alt not allowed on element video at this point."

### Screen reader

In Windows 10 / 11

1. Open corresponding web page in Google Chrome
2. Enable Narrator: Windows key + Ctrl + Enter
3. Navigate through document with numerical heading keys and tab
4. Move to video
5. Note that it reads a description corresponding to the `aria-label` attribute property, followed by the word "Group"

### CODE REVIEW

**Review by MohamedZaghdoudi — COMMENTED** [review]
@MikeMcC399 Very observative, thanks!

**Comment by MikeMcC399** [comment]
This is really a bug.

1. It is a bug because `alt` is not allowed inside `<video>` .
2. Since the alt texts were added as part of PR https://github.com/corona-warn-app/cwa-website/pull/2481 by @larswmh which was an accessibility effort, I assume that this was a mistake, so this current PR corrects a bug in the accessibility implementation, rather than an enhancement.

**Comment by brianebeling** [comment]
> This is really a bug.
> 
> 1. It is a bug because `alt` is not allowed inside `<video>` .
> 2. Since the alt texts were added as part of PR [Add missing alts to blog and science blog #2481](https://github.com/corona-warn-app/cwa-website/pull/2481) by Lars which was an accessibility effort, I assume that this was a mistake, so this current PR corrects a bug in the accessibility implementation, rather than an enhancement.

Ok. I was thinking enhancement because of the added accessibility, e.g. narrator. Will change the label then.

**Comment by MikeMcC399** [comment]
@brianebeling 

> Ok. I was thinking enhancement because of the added accessibility, e.g. narrator. Will change the label then.

Thanks for changing the label! I understand why you classified it as an enhancement. Providing the PR gets merged, the category is not really so important.

**Review by brianebeling — APPROVED** [review]

**Pull request merged**
