### PR TITLE
Add link to BZgA online tool to FAQ "vac_status"

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description

This PR adds a link to the ~~Corona vaccination check of the BZgA (https://www.infektionsschutz.de/coronavirus/schutzimpfung/der-corona-impfcheck)~~ Impf-Guide of the BMG (https://www.zusammengegencorona.de/impfen/#id-862101356) to the FAQ entry `vac_status`.

## What was changed

- https://www.coronawarn.app/de/faq/results/#vac_status
- https://www.coronawarn.app/en/faq/results/#vac_status

## Screenshots

| German | English |
|---|---|
| De | En |

## Additional information

I did *not* test this PR using Cypress as I can't get the Cypress test suite to work in my environment. Sorry for that!

---
Internal Tracking ID: [EXPOSUREAPP-14143](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14143)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I suggest to link to https://www.zusammengegencorona.de/impfen/#id-862101356 instead, since this is already referred to in the FAQs and it has a finer age selection compared to https://www.zusammengegencorona.de/impfen/#id-862101356.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Would be ok for me, but I want to wait for feedback from the team.

Have a nice Sunday!

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Thanks for the PR and suggestion: Indeed, it is a good idea to include one of these links. We check later, which one is the most practical to be included. I think, @MikeMcC399's suggestion does make sense.

Enjoy Saturday!

**Review by GisoSchroederSAP — APPROVED** [review]
Yes, please. Gor for the discuessed hyperlinks; those provide appropriate guidance for the users.
Thanks for pointing out.
Approved for going forward.

**Comment by Ein-Tim** [comment]
@dsarkar I'll only have time to do so at the end of this week so if you want to merge this PR soon it would be great if you could do that.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for your feedback, in that case we will do it of course!

**Comment by larswmh** [comment]
The link has been replaced and the opening comment has been aligned accordingly

**Review by dsarkar — APPROVED** [review]

**Comment by Ein-Tim** [comment]
Thanks @dsarkar & @larswmh.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks you for proposal and PR!

**Pull request merged**
