### PR TITLE
added new faq article battery_optimization_background

### PR DESCRIPTION
**Pull request by svengabr**

### CODE REVIEW

**Comment by marsp61** [comment]
How to get rid of the permanent emails from Github?

**Comment by svengabr** [comment]
@marsp61 try this:

emails

Most likely you need to go through each repository you did subscribe to...

**Comment by marsp61** [comment]
I did not subscribe any...

**Comment by marsp61** [comment]
image

**Comment by svengabr** [comment]
@marsp61 then I suggest taking a look at your account settings in the "Mails" section:

2020-10-29 11_31_11-Email settings

**Comment by marsp61** [comment]
Thanks, I think I solved it... on the iPad I found other prefernces than on the iPhone.

**Comment by MikeMcC399** [comment]
@marsp61 
Also for reference check out https://github.com/watching which gives you both Watching and Subscriptions.

**Pull request merged**
