### PR TITLE
Update FAQ error 11

### PR DESCRIPTION
**Pull request by Ein-Tim**
Closing #425 

Please note that the FAQ entry is still under "Solved", I wasn't sure how I should lift it up to the "Common Issues" Section...

@svengabr If you are happy with these changes please approve and merge them. Thanks.

### CODE REVIEW

**Comment by svengabr** [comment]
closes https://github.com/corona-warn-app/cwa-website/issues/425

**Comment by Ein-Tim** [comment]
Didn't know that "" will lead to an Error, thx for fixing and now I know @svengabr ❤️

**Comment by svengabr** [comment]
Yea because the JSON was invalid. Also, the English version was missing a comma at the end of the first block which is also an invalid JSON. Easier to fix it myself very quickly. Thanks again for your effort in writing the texts!

**Comment by Ein-Tim** [comment]
Ahh, good to know that, Thanks!
No problem, I'm always happy to help 👍

**Pull request merged**
