### PR TITLE
Restructure build and server start for Cypress tests (resolves timeout #1993)

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves the timeout issue which may occur when testing the [cwa-website](https://github.com/corona-warn-app/cwa-website) locally as described in "Timeout running Cypress test" https://github.com/corona-warn-app/cwa-website/issues/1993.

It prepares for a migration to Cypress 8, however the PR itself does not change the Cypress version from its current `"^7.7.0"`.

### `package.json`

1. A new script `start-server` is added to `package.json`. It starts the `browsersync` server via `gulp start` which can then be used for manual testing or for automated Cypress testing. The script assumes that there is a complete web built and available in the `public` directory.
2. The scripts `test:open`, `test:chrome` and `test:firefox` are modified to first build the web, then start the server, instead of attempting to start the server before the web is built.
3. The scripts `cypress:run:chrome` and `cypress:run:firefox` are modified to specify explicitly to run in headed mode, which is the default for the currently used Cypress 7 version. The default changes in Cypress 8, so this change prepares the scripts for any future update by making them upwards compatible. 
4. The version number of `package.json` is incremented to 1.1.0. The name of "Corona-Warn-App" is used consistently.

### `gulpfile.js`

1. A new task `start-server` is added which starts the `browsersync` server then watches for changes.
2. The `default` task is equivalent to and compatible with the previous version of the `default` task. For conciseness it calls the new task `start-server` instead of individually calling `server` then `watch`.
### Other changes

- `npx browserslist@latest --update-db` has updated caniuse-lite to the latest version

## Impact

The PR is compatible with all commands documented in README.md.

There is no change the `gulp build` task so there should be no impact to the web deployment.

`start-server` is a new npm script.

## Verification Environment

Cypress 7.7.0 and Cypress 8.7.0

### Windows 10 (21H1)

Google Chrome 95.0.4638.69 
Mozilla Firefox 94.0

### Ubuntu 20.04.3

Google Chrome 95.0.4638.69 
Mozilla Firefox 93.0

For Firefox execute once:
`sudo apt install ffmpeg`
otherwise Cypress tests timeout

## Verification

Tests are carried out in a bash terminal window from the root directory of a cloned copy of [cwa-website](https://github.com/corona-warn-app/cwa-website).

No timeouts should occur during the tests. Only `start-server` is new. All other commands listed below should not show any regressions compared to before this PR.

Execute
`npm ci`
once from this branch before running tests.

### Test `start-server`

```bash
npm run build
npm run start-server
```

A browser window http://localhost:8000/en/ will be started displaying the CWA website.
Kill the terminal process.

### Test `start`

```bash
npm start
```

The same as the previous test. A browser window http://localhost:8000/en/ will be started displaying the CWA website.
Kill the terminal process.

### Test `test:open`

```bash
npm run test:open
```
In the Cypress console click on `applink_spec.js` to run it.
A new window opens and the three tests should run successfully.
In the Cypress console click on Stop.
Close the Cypress console.
Kill the terminal process.

### Test `test:chrome`

```bash
npm run test:prepare
npm run test:chrome
```

All tests should be run automatically in a Google Chrome browser.
When the tests complete, the line
`All specs passed!` should appear in the terminal window.

### Test `test:firefox`

```bash
npm run test:prepare
npm run test:firefox
```

All tests should be run automatically in a Mozilla Firefox browser.
When the tests complete, the line
`All specs passed!` should appear in the terminal window.

(Note this test has not always run successfully before the PR. It has timed out sometimes.)

### Test `test`

This is equivalent to `test:chrome`.

```bash
npm run test:prepare
npm test
```

`npm test` and `npm run test` are interpredted the same by `npm`.

The success criteria is the same as for `test:chrome`.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
This is a draft PR waiting for the solution to:
- [ ] https://github.com/corona-warn-app/cwa-website/issues/1986

Once the above issue is resolved, then this PR can be successfully verified. It will otherwise fail because of the failing unit test `check_anchor_links.js`.

**Comment by MikeMcC399** [comment]
Currently testing this PR before requesting review.

**Comment by matriceria** [comment]
@MikeMcC399 While using the command npm run test:open, I get the following error 

image

**Comment by MikeMcC399** [comment]
@matriceria
Thank you for your feedback and test!

I see that you get the error
`Task never defined: build;`
when you try to execute `npm run test:open`

I would like to give you some troubleshooting steps. Could you please tell me what operating system you are testing under? It looks like Microsoft Windows.

**Comment by matriceria** [comment]
We tested it on:
 Edition Windows 10 Home
Version 20H2
Installed on ‎13/‎03/‎2021
OS build 19042.1288
Experience Windows Feature Experience Pack 120.2212.3920.0

Node version: v14.17.0
Npm version: 6.14.13

and 
Edition Windows 10 Enterprise
Version 21H1
Installed on ‎10/‎5/‎2021
OS build 19043.1288
Experience Windows Feature Experience Pack 120.2212.3920.0

Node version: v14.18.1
Npm version: 6.14.15

Our gulp version is the same as yours and our gulpfile.js is identical

**Comment by MikeMcC399** [comment]
@matriceria 

Thanks for the version information. That looks all correct.

I don't understand what is going wrong and I have also cloned the branch to another system and run it successfully. Do you have any idea what the problem is?

What happens if you run
`npx gulp build`
from a bash terminal on Windows?

**Comment by MikeMcC399** [comment]
What happens also if you try:
`npm start`
and
`npm run build`
?

Do those run correctly?

**Comment by MikeMcC399** [comment]
@matriceria 

I've attached a log of successfully cloning the branch from the fork and running the test which failed in your environment. I didn't think it should have any influence, but I was running this in a Microsoft OneDrive directory to be like what you are using.

```
git clone https://github.com/MikeMcC399/cwa-website
cd cwa-website
git switch fix/start-server-wait-timeout
npm install
npm run test:prepare
npm run test:open
```

[start-server-wait-timeout_full_log.txt](https://github.com/corona-warn-app/cwa-website/files/7498288/start-server-wait-timeout_full_log.txt)

Perhaps you could compare how that is working in your environment?

**Comment by MikeMcC399** [comment]
@matriceria 

The problem is probably due to OneDrive if you cloned the repo to one system and then tested on another system.

I managed to reproduce a similar error to the one you are seeing. At the moment OneDrive is syncing from my first local Windows system to the OneDrive server and it has not completely finished uploading to the server. It is 3.3GB with all files, so it takes quite a long time.

On a second (Windows) system I tried to execute `npm run test:open` and I got the error that it could not find the command `start-server-and-test`. The second system initially said that OneDrive is synchronized, but of course it could not know that the original first system had not completely uploaded the branch.

Please check that the directory you are working in is complete! If you are relying on OneDrive and the branch is incomplete then the errors are unpredictable.

**Comment by brifemu** [comment]
I had tested it on two devices:

### Windows

I get the same error as @matriceria, but I haven't the project on OneDrive environment.

Edition Windows 10 Enterprise
Version 21H1
Installed on ‎10/‎5/‎2021
OS build 19043.1288
Experience Windows Feature Experience Pack 120.2212.3920.0

Node version: v14.18.1
Npm version: 6.14.15

### Mac

All works fine, tested on a MacBook Pro early 2011 using macOS Sierra version 10.12.6

**Comment by MikeMcC399** [comment]
@matriceria 
I assume that you are testing this on the instructions of @svengabr to whom this PR is assigned. Is that correct?

@svengabr / @dsarkar 
Could we please get this tested without Microsoft OneDrive?

OneDrive has quite a few issues when used in parallel to cwa-website.
- the directory public is deleted and then recreated by the build process.
- the directory node_modules is deleted and then recreated by `npm ci`
- excluding directories in OneDrive which are recreated does not work well
- OneDrive and git are working in parallel to maintain a mirror of data status. That also does not work well

**Comment by MikeMcC399** [comment]
@brifemu 

I guess we were writing in parallel!

It's strange that it works on Mac and not on your Windows environment.

I can't get it to fail in my Windows environments!

Do you have any suggestions about how I could change it to work for you on Windows?

**Comment by MikeMcC399** [comment]
@brifemu 
I am running the commands in a git bash environment on Windows. What do you use on Windows?

(On Ubuntu I run in a native terminal and it works fine there too.)

**Comment by brifemu** [comment]
> @brifemu I am running the commands in a git bash environment on Windows. What do you use on Windows?
> 
> (On Ubuntu I run in a native terminal and it works fine there too.)

I use git bash too. It is very strange that it does not work even having the same or very similar versions of node and npm. I will keep trying to solve it, if I succeed I will notify you here

**Comment by matriceria** [comment]
It also works on MAC for me, I will test it on windows in another file path to see if I can also make it work when I arrive home

**Comment by brifemu** [comment]
@MikeMcC399 

If I run `npm run test:open` console return:

> $ npm run test:open
>
> corona-warn-app-landingpage@1.1.0 test:open C:\Users\Brian\My Documents\Workspace\cwa-website
>  gulp build; start-server-and-test start-server http://localhost:8000 cypress:open
> 
> [12:40:50] Using gulpfile ~\My Documents\Workspace\cwa-website\gulpfile.js
> [12:40:50] Task never defined: build;
> [12:40:50] To list available tasks, try running: gulp --tasks
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! corona-warn-app-landingpage@1.1.0 test:open: `gulp build; start-server-and-test start-server http://localhost:8000 cypress:open`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the corona-warn-app-landingpage@1.1.0 test:open script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Brian\AppData\Roaming\npm-cache\_logs\2021-11-09T11_40_50_713Z-debug.log


But if I use directly `gulp build; start-server-and-test start-server http://localhost:8000 cypress:open console` return:

> $ gulp build; start-server-and-test start-server http://localhost:8000 cypress:open
> [12:41:19] Using gulpfile ~\My Documents\Workspace\cwa-website\gulpfile.js
> [12:41:19] Starting 'build'...
> [12:41:19] Starting 'clean'...
> [12:41:20] Finished 'clean' after 874 ms
> [12:41:20] Starting 'cleanBlogs'...
> [12:41:20] Finished 'cleanBlogs' after 40 ms
> [12:41:20] Starting 'cleanScienceBlogs'...
> [12:41:20] Finished 'cleanScienceBlogs' after 4.34 ms
> [12:41:20] Starting 'buildBlogFiles'...
> [12:41:20] Finished 'buildBlogFiles' after 257 ms
> [12:41:20] Starting 'buildScienceBlogFiles'...
> [12:41:21] Finished 'buildScienceBlogFiles' after 305 ms
> [12:41:21] Starting 'analyseData'...
> [12:41:21] Finished 'analyseData' after 773 ms
> [12:41:21] Starting 'cwaaJs'...
> [12:41:29] Version: webpack 4.46.0
> Built at: 11/09/2021 12:41:29 PM
>   Asset     Size  Chunks                    Chunk Names
> cwaa.js  807 KiB       0  [emitted]  [big]  cwaa
> Entrypoint cwaa [big] = cwaa.js
> 
> WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> This can impact web performance.
> Assets:
>   cwaa.js (807 KiB)
> 
> WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> Entrypoints:
>   cwaa (807 KiB)
>       cwaa.js
> 
> 
> WARNING in webpack performance recommendations:
> You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
> For more info visit https://webpack.js.org/guides/code-splitting/
> [12:41:29] Finished 'cwaaJs' after 7.28 s
> [12:41:29] Starting 'javascript'...
> [12:41:38] Version: webpack 4.46.0
> Built at: 11/09/2021 12:41:38 PM
>                Asset      Size  Chunks                    Chunk Names
>               app.js   140 KiB       0  [emitted]         app
> eventregistration.js   679 KiB       1  [emitted]  [big]  eventregistration
>       screenshots.js  91.5 KiB       2  [emitted]         screenshots
> Entrypoint app = app.js
> Entrypoint eventregistration [big] = eventregistration.js
> Entrypoint screenshots = screenshots.js
> 
> WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> This can impact web performance.
> Assets:
>   eventregistration.js (679 KiB)
> 
> WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> Entrypoints:
>   eventregistration (679 KiB)
>       eventregistration.js
> 
> 
> WARNING in webpack performance recommendations:
> You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
> For more info visit https://webpack.js.org/guides/code-splitting/
> [12:41:38] Finished 'javascript' after 9.26 s
> [12:41:38] Starting 'pages'...
> [12:41:38] Starting 'images_minify'...
> [12:41:38] Starting 'copy'...
> [12:41:38] Starting 'copyFAQs'...
> [12:41:38] Starting 'copyFAQRedirects'...
> folder created: ./public/.well-known
> [12:41:38] Finished 'copyFAQs' after 269 ms
> [12:41:39] Finished 'copyFAQRedirects' after 924 ms
> [12:41:42] Finished 'pages' after 3.62 s
> [12:41:42] gulp-imagemin: Minified 19 images (saved 1.06 MB - 35.1%)
> [12:41:42] Finished 'images_minify' after 3.79 s
> [12:41:52] Finished 'copy' after 14 s
> [12:41:52] Starting 'images_webp'...
> [12:41:58] Finished 'images_webp' after 6.21 s
> [12:41:58] Starting 'sass'...
> [12:42:00] Finished 'sass' after 1.41 s
> [12:42:00] Starting 'build_sitemap'...
> [12:42:00] Finished 'build_sitemap' after 402 ms
> [12:42:00] Starting 'createFaqRedirects'...
> [12:42:00] Finished 'createFaqRedirects' after 375 ms
> [12:42:00] Starting 'replaceVersionNumbers'...
> [12:42:02] Finished 'replaceVersionNumbers' after 1.6 s
> [12:42:02] Finished 'build' after 43 s
> bash: start-server-and-test: command not found

Maybe is a syntax error, I'm gonna ask for help to @svengabr

**Comment by MikeMcC399** [comment]
@brifemu 
Thanks for researching further!

For the command string
`gulp build; start-server-and-test start-server http://localhost:8000 cypress:open`
that only works if you have gulp-cli installed globally (`npm install --global gulp-cli`). To avoid the dependence on the gulp-cli installation use:
`npx gulp build`

The second part of the command string:
`start-server-and-test start-server http://localhost:8000 cypress:open`
fails as expected (`bash: start-server-and-test: command not found`) because it is not a shell command. You could also run this with npx
`npx start-server-and-test start-server http://localhost:8000 cypress:open`

Do you get the same task list for
`nxp gulp -T`
and
`gulp -T`
?

**Comment by brifemu** [comment]
@MikeMcC399 

If I run `gulp build; npx start-server-and-test start-server http://localhost:8000 cypress:open` it works, but if replace the content of `npm run test:open` for `gulp build; npx start-server-and-test start-server http://localhost:8000 cypress:open` it fails again.

About gulp: `npx gulp -T` and `gulp -T` have the same result.

> [14:11:06] Tasks for ~\Documents\Workspace\cwa-website\gulpfile.js
> [14:11:06] ├─┬ build
> [14:11:06] │ └─┬ <series>
> [14:11:06] │   ├── clean
> [14:11:06] │   ├── cleanBlogs
> [14:11:06] │   ├── cleanScienceBlogs
> [14:11:06] │   ├── buildBlogFiles
> [14:11:06] │   ├── buildScienceBlogFiles
> [14:11:06] │   ├── analyseData
> [14:11:06] │   ├── cwaaJs
> [14:11:06] │   ├── javascript
> [14:11:06] │   ├─┬ <parallel>
> [14:11:06] │   │ ├── pages
> [14:11:06] │   │ ├── images_minify
> [14:11:06] │   │ ├── copy
> [14:11:06] │   │ ├── copyFAQs
> [14:11:06] │   │ └── copyFAQRedirects
> [14:11:06] │   ├── images_webp
> [14:11:06] │   ├── sass
> [14:11:06] │   ├── build_sitemap
> [14:11:06] │   ├── createFaqRedirects
> [14:11:06] │   └── replaceVersionNumbers
> [14:11:06] ├─┬ blog
> [14:11:06] │ └─┬ <series>
> [14:11:06] │   ├── cleanBlogs
> [14:11:06] │   └── buildBlogFiles
> [14:11:06] ├─┬ science
> [14:11:06] │ └─┬ <series>
> [14:11:06] │   ├── cleanScienceBlogs
> [14:11:06] │   └── buildScienceBlogFiles
> [14:11:06] ├─┬ start-server
> [14:11:06] │ └─┬ <series>
> [14:11:06] │   ├── server
> [14:11:06] │   └── watch
> [14:11:06] └─┬ default
> [14:11:06]   └─┬ <series>
> [14:11:06]     ├─┬ build
> [14:11:06]     │ └─┬ <series>
> [14:11:06]     │   ├── clean
> [14:11:06]     │   ├── cleanBlogs
> [14:11:06]     │   ├── cleanScienceBlogs
> [14:11:06]     │   ├── buildBlogFiles
> [14:11:06]     │   ├── buildScienceBlogFiles
> [14:11:06]     │   ├── analyseData
> [14:11:06]     │   ├── cwaaJs
> [14:11:06]     │   ├── javascript
> [14:11:06]     │   ├─┬ <parallel>
> [14:11:06]     │   │ ├── pages
> [14:11:06]     │   │ ├── images_minify
> [14:11:06]     │   │ ├── copy
> [14:11:06]     │   │ ├── copyFAQs
> [14:11:06]     │   │ └── copyFAQRedirects
> [14:11:06]     │   ├── images_webp
> [14:11:06]     │   ├── sass
> [14:11:06]     │   ├── build_sitemap
> [14:11:06]     │   ├── createFaqRedirects
> [14:11:06]     │   └── replaceVersionNumbers
> [14:11:06]     └─┬ start-server
> [14:11:06]       └─┬ <series>
> [14:11:06]         ├── server
> [14:11:06]         └── watch
 
We are getting closer! 🚀

**Comment by svengabr** [comment]
On my machine, I got it working using your suggested
`npx gulp build` and `npx start-server-and-test start-server http://localhost:8000 cypress:open`

But using `npm run test:open` I'm also running into the same problem

**Comment by MikeMcC399** [comment]
I found a related issue in the npm repo:
https://github.com/npm/npm/issues/4040 "npm run-script doesn't work on windows when the script contains multiple commands"

I am closing this PR now and I will work on an alternative solution with the goal of having it runnable cross-platform.

Thanks again to @matriceria / @brifemu / @svengabr for your collaboration!

**Comment by MikeMcC399** [comment]
The reason that this PR was failing on Windows was the missing npm key `shell-script` which needed to point to the bash shell executable.

This was already a requirement to successfully run the existing and unchanged `npm run test:prepare` command so I had not specified this as a prerequisite. Unfortunately I also did not recognize the reason for the failure until it came up in https://github.com/corona-warn-app/cwa-website/pull/2067#issuecomment-966064671. 

Executing `npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"` would allow this PR to work on Windows.

In any case this PR is closed and withdrawn and replaced by PR #2067 which is more robust in terms of environmental requirements.

**Pull request closed without merging**
