### PR TITLE
Bump current iOS and Android app version

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR bumps the current iOS app version from 2.13.1 to 2.13.2 & the current Android app version from 2.13.2 to 2.13.3

---

GitHub Release: 
iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.13.2
Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.13.3

### CODE REVIEW

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.

**Comment by dsarkar** [comment]
@Ein-Tim Android will be 2.13.3, could you change that one as well, please?

**Comment by Ein-Tim** [comment]
@dsarkar 

I created #2078, or would you prefer that I commit the change here?

**Comment by dsarkar** [comment]
@Ein-Tim Better in one single PR (more time efficient)

**Comment by Ein-Tim** [comment]
@dsarkar 

Added in https://github.com/corona-warn-app/cwa-website/commit/bae54b59ef374a19ff05235288a4bf4fef3e4ba3.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.

**Comment by MikeMcC399** [comment]
@dsarkar 
The new releases are already visible in both the stores.

**Pull request merged**
