### PR TITLE
Add a description to risk card category on screenshots page

### PR DESCRIPTION
**Pull request by larswmh**
DE:
image
EN:
image

---
Internal Tracking ID: [EXPOSUREAPP-10139](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10139)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@larswmh 
Since this PR is still in draft status and it's on hold so I'm not sure if you are ready for comments, but anyway ...

1. In the text description I was confused about the instructions. Could you make it clear that you are describing actions in the app and not on the website?
2. The screenshots are a mixture of iOS and Android on the same page. This is not caused by this PR. It is already like that on:
- https://www.coronawarn.app/en/screenshots/#ios_cards
- https://www.coronawarn.app/en/screenshots/#android_cards
- https://www.coronawarn.app/de/screenshots/#ios_cards
- https://www.coronawarn.app/de/screenshots/#android_cards

**Comment by larswmh** [comment]
@MikeMcC399 

In my latest commit I have tried to make it more clear that the instructions are for in-app use.
We will replace the screenshots in the risk card category with screenshots of the respective operating system in the future, but we do not have the assets for it right now. Therefore there is currently a mixture of both iOS and Android screenshots displayed in both screenshot pages.

**Comment by MikeMcC399** [comment]
@larswmh 

> In my latest commit I have tried to make it more clear that the instructions are for in-app use.

That is clearer now. This is the first time that there have been any instructions for using the app on the screenshot page, so it is good to be explicit.

> We will replace the screenshots in the risk card category with screenshots of the respective operating system in the future, but we do not have the assets for it right now. Therefore there is currently a mixture of both iOS and Android screenshots displayed in both screenshot pages.

There are some textual differences between Android and iOS (see https://github.com/corona-warn-app/cwa-documentation/issues/813#issuecomment-1017696810) so this is not just a cosmetic issue.

**Comment by MikeMcC399** [comment]
The screenshots for Risk Cards / Risiko-Karten are now appearing with descriptions, so it seems that this PR is a duplicate and is obsolete.

- https://www.coronawarn.app/en/screenshots/#ios_cards
- https://www.coronawarn.app/en/screenshots/#android_cards
- https://www.coronawarn.app/de/screenshots/#ios_cards
- https://www.coronawarn.app/de/screenshots/#android_cards

It should probably be closed.

**Pull request closed without merging**
