### PR TITLE
Add FAQ #vac_status

### PR DESCRIPTION
**Pull request by larswmh**
image
image

### CODE REVIEW

**Review by Ein-Tim — COMMENTED** [review]
Why use "vac_status" as anchor and not e.g. "vac_infofmation" or "vac_recommendations"?
IMO "vac_status" does not really fit here.

**Comment by MikeMcC399** [comment]
The link in this new faq is also included in 

[#vaccination_recommendation](https://www.coronawarn.app/en/faq/results/#vaccination_recommendation) which is located in the section https://www.coronawarn.app/en/faq/results/#vaccination_recommendation

image

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Why use "vac_status" as anchor and not e.g. "vac_infofmation" or "vac_recommendations"? IMO "vac_status" does not really fit here.

I agree that #vac_status does not fit the contents of the new faq.  "vac_infofmation" should probably be  "vac_information". "vac_recommendations" is too similar to the existing [#vaccination_recommendation](https://www.coronawarn.app/en/faq/results/#vaccination_recommendation) however.

**Comment by larswmh** [comment]
@MikeMcC399 @Ein-Tim thanks for your quick feedback. `COVID-19 > General` truly fits better than `Troubleshooting > General` and the FAQ has been moved with https://github.com/corona-warn-app/cwa-website/pull/2824/commits/dbd784dd06117f052aa1bd155f46d8c6112b97f8.
About the anchor: It is predefined by stakeholders and can therefore not be changed. It is planned to be used in the app.

**Comment by Ein-Tim** [comment]
@larswmh 

Thanks for the feedback, this doesn't make sense IMO but OK!

**Review by dsarkar — APPROVED** [review]

**Pull request merged**
