### PR TITLE
Release 2.13 updates

### PR DESCRIPTION
**Pull request by dsarkar**
- [x] Gulpfile: 2.13.1
- [x] Privacy notice - no updates
- [x] FAQs
  - [ ] https://github.com/corona-warn-app/cwa-website/issues/1929
  - [x] Redirect vac_booster to existing vac_cert_booster. CWA will link to vac_booster 
  https://github.com/corona-warn-app/cwa-website/pull/1949
  - [x] https://github.com/corona-warn-app/cwa-website/pull/1966
  - [x] https://github.com/corona-warn-app/cwa-website/pull/2001
- [x] Screenshots
https://github.com/corona-warn-app/cwa-website/pull/1945

### CODE REVIEW

**Comment by MikeMcC399** [comment]
During the Android 2.13.x development cycle the "Recycle bin" was first called "Trash" . It looks like the new name is not being used everywhere yet. I will get back with more details after I check the app.

**Comment by Ein-Tim** [comment]
Version 2.13.1 has been released on GitHub:

iOS release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.13.1
Android release: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.13.1

I can't download this version on the App Store yet.

**Comment by dsarkar** [comment]
@Ein-Tim Try again now.

**Comment by Ein-Tim** [comment]
Now I can download it! Please merge 👍

**Comment by MikeMcC399** [comment]
I have opened a new issue for the incorrect Recycle Bin screenshots for Android English. See https://github.com/corona-warn-app/cwa-website/issues/2006.

**Pull request merged**
