### PR TITLE
Update gulp-sass to v5 and node-sass to v6

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR implements the suggestion from issue https://github.com/corona-warn-app/cwa-website/issues/2170 "Update sass npm packages (gulp-sass and node-sass)?" by updating the following two packages:

Package | Previous version | New version
--- | --- | ---
[gulp-sass](https://github.com/dlmanning/gulp-sass) | 4.1.1 | 5.0.0
[node-sass](https://github.com/sass/node-sass) | 4.14.1 | 6.0.1

Migration to gulp-sass v5 is a breaking change with [Migrating to version 5](https://github.com/dlmanning/gulp-sass#migrating-to-version-5) instructions which this PR has followed.

The npm update is achieved through:

`npm install node-sass@6 gulp-sass@5 --save`

## Benefits

1. The npm `tar` package is implicitly updated from 2.2.2 to 6.1.11 which resolves one GitHub Dependabot alert.
2. The `node-sass` package, which is currently compatible with Node.js 14, becomes compatible with Node.js 16 through updating from v4 to v6 (see https://github.com/sass/node-sass). This removes one barrier to updating the cwa-website to Node.js 16 (see issue https://github.com/corona-warn-app/cwa-website/issues/2155 from more details).

## Verification

On Windows and Ubuntu execute the following:

```
npm ci
npm run test:prepare
npm test
```

Ensure that the Cypress test suite runs successfully to completion with no failures.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
This is currently a draft PR waiting for a strategy answer on:
- issue #2170

The changes have been successfully tested on:
- Windows 10
- Ubuntu 20.04

**Comment by brifemu** [comment]
@MikeMcC399 

It's works good for me on macOS Monterey v.12.0.1

Preparing Windows and Ubuntu environment for testing it too.

**Comment by MikeMcC399** [comment]
@brifemu 
> It works good for me on macOS Monterey v.12.0.1

That's good! 👍🏻 I don't have that environment, so I can't test macOS.

My next Windows test will be on Windows 11 instead of Windows 10. I upgraded my hardware and environment this week and I am leaving Windows 10 behind me. 🙂

**Comment by MikeMcC399** [comment]
Rebased, since you are now actively testing.

**Comment by dsarkar** [comment]
Thanks @MikeMcC399

**Comment by MikeMcC399** [comment]
I have successfully retested, just using

```
npm ci
npm run build
```

on

- Ubuntu 20.04
- Windows 11 Version 21H2

**Comment by brifemu** [comment]
@MikeMcC399 

Tested again on Mac, flawless. Thanks!

**Comment by brifemu** [comment]
@MikeMcC399 

Tested on Ubuntu 20.04.3 and Windows 10 21H2 without problems.

**Review by svengabr — APPROVED** [review]
Nothing bad here. :) You also got approval from my side.

Thanks @MikeMcC399 your changes will be merged today!

**Pull request merged**
