### PR TITLE
Correct use of hyphens

### PR DESCRIPTION
**Pull request by MohamedZaghdoudi**
Correct use of hyphens

---
Internal Tracking ID: [EXPOSUREAPP-14625](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14625)

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@MohamedZaghdoudi / @dsarkar 

Will you also convert dates like "15 July, 2022" to "July 15, 2022" in https://www.coronawarn.app/en/faq/results/#check_in_luca_all?

And German formatted dates like "04.02.2021" to "Feb 4, 2021" (three letter month) in https://www.coronawarn.app/en/faq/results/#interoperability_countries?

or were you only concerned about removing the "st, nd, rd, th" notation?

**Comment by MohamedZaghdoudi** [comment]
@MikeMcC399 
yes i think it will be better to change it to this :"Feb 4, 2021"
I will change it

**Comment by dsarkar** [comment]
@MikeMcC399 thanks for your input here. Something was a bit "messed up" with two PRs:
This PR #2246 now contains changes in the use of hyphens.
PR #3348 is about date format.

**Comment by MikeMcC399** [comment]
@dsarkar 

>  This PR #2246 now contains changes in the use of hyphens.

This PR is actually #3346.

It's quite confusing when the branch name `Refactoring-Faq-Date_formates` doesn't  match the changes being made. Unfortunately this can't be changed in an existing PR. To clean it up, it would need the PR closing, branch renaming and a new PR being opened.

**Comment by dsarkar** [comment]
@MikeMcC399 agreed.

**Pull request closed without merging**
