### PR TITLE
Mention "luca" in `check_in_qr_code` (Addresses #1461)

### LINKED ISSUE #1461: FAQ does not mention Luca QR codes
According to several sources CWA is supposed to be able to read Luca QR codes by now.
(Obviously, that's still not the case, yet the feature is of great interest not only to me)
None of these sources seems to be the CWA web site -- suspicioulsly, the FAQ does not even mention Luca, let alone contains information about the status.

Please, add (und update) information about that to the FAQ, even if it is just "WIP" or "not going to happen".

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR adds a mention of the "luca" app to the FAQ entry `check_in_qr_code` as requested by @2019-05-10 in https://github.com/corona-warn-app/cwa-website/issues/1461#issuecomment-880800334. 

<details>
<summary>Preview of the changes</summary>

| English | German |
|---|---|
| Preview EN | Preview DE | 

</details>

---

This PR **closes #1461**.

This PR is a follow up to #1500.

### CODE REVIEW

**Comment by Ein-Tim** [comment]
@dsarkar Is this change welcome and has to be clarified/signed-off by e.g. the RKI? Or has this PR "snowed" under?

**Comment by dsarkar** [comment]
@Ein-Tim Thanks a lot for the suggestion, however, this has to wait until further notice.

**Comment by Ein-Tim** [comment]
Changing to draft due to https://github.com/corona-warn-app/cwa-server/pull/1594

**Comment by dsarkar** [comment]
@Ein-Tim FYI PR https://github.com/corona-warn-app/cwa-website/pull/2041

**Comment by Ein-Tim** [comment]
@dsarkar

Thank you! 

Closing this PR

**Pull request closed without merging**
