### PR TITLE
[WIP] FAQ - update 'encounter_19_calc' entry for #971

### PR DESCRIPTION
**Pull request by heinezen**
Changelog:
- Move last paragraph's text sections to a better place
- "only" removed in english entry
- remove mention of 10 minutes signal attenuation time window and just keep 5 minutes

### CODE REVIEW

**Review by MikeMcC399 — CHANGES_REQUESTED** [review]
Please change all references to 2.0 of the API to 2 (without a minor version ".0") otherwise the version might be confused with the major.minor version numbering of the Google Play services module, which is currently at 1.8.

---
Unfortunately Apple and Google have not aligned their nomenclature!

Apple uses the name "Exposure Notifications framework"
(see https://developer.apple.com/documentation/exposurenotification#overview)
and refers to version 2
(see https://developer.apple.com/documentation/bundleresources/information_property_list/enapiversion).

Google uses the name "Exposure Notifications system"
(see https://developers.google.com/android/exposure-notifications/exposure-notifications-api#architecture) 
and the version which follows "Legacy v1 mode" is **not** v2, it is called "ExposureWindow mode"
(see https://developers.google.com/android/exposure-notifications/exposure-notifications-api#modes).

In the Google world "ExposureWindow mode" was introduced with version 1.5 of Google Play services. The current version of Google Play services is version 1.8.

To avoid hitting CWA users with the confusing naming issues, I would suggest calling it "Exposure Notification Framework" in any place where Apple and Google are being referred to. 


You could change the introductory sentence to 
"With the introduction of Corona-Warn-App version 1.9, a new version of the Exposure Notification Framework (ENF) from Apple/Google is used, version 2 (also known as ExposureWindow mode by Google)."

After that only refer to version 2, not to ExposureWindow mode in the text.

**Comment by MikeMcC399** [comment]
The description about the risk calculation regarding dB levels does not match the documentation on https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf.

**Comment by MikeMcC399** [comment]
There is a lot of overlap between
http://localhost:8000/en/faq/#encounter_count_19 and
http://localhost:8000/en/faq/#encounter_19_calc

Please consider combining the two FAQ articles, so that the risk calculation is only described in one place.

**Comment by MikeMcC399** [comment]
There is no explanation of what dB levels mean. See https://github.com/corona-warn-app/cwa-website/issues/712 and the explanation published to https://github.com/corona-warn-app/cwa-documentation/issues/484#issuecomment-781382074.

**Comment by heinezen** [comment]
@MikeMcC399 I'll let this PR stay up until the PR for `encounter_count_19` is up too for direct comparison.

> To avoid hitting CWA users with the confusing naming issues, I would suggest calling it "Exposure Notification Framework" in any place where Apple and Google are being referred to.

Noted. I've added it to the general issues/remarks in #971

**Comment by heinezen** [comment]
Closed in favour of https://github.com/corona-warn-app/cwa-website/pull/1222

**Pull request closed without merging**
