### PR TITLE
Update FAQ ios135

### PR DESCRIPTION
**Pull request by dsarkar**
- with the CWA release 1.12, iOS 12.5 and 13.7 are min req. depending on the iPhone model
- move the article up, just below to min_req article as suggested by @Ein-Tim.

### CODE REVIEW

**Comment by dsarkar** [comment]
DE

image

**Comment by dsarkar** [comment]
EN

image

**Comment by dsarkar** [comment]
Closes https://github.com/corona-warn-app/cwa-website/issues/855

**Review by MikeMcC399 — COMMENTED** [review]
I noticed that the terms "release" and "version" are used interchangeably. That might confuse a non-technical person.

Perhaps it would be better to standardise on the one term "version" when referring to a particular version?

**Comment by dsarkar** [comment]
@MikeMcC399 

> I noticed that the terms "release" and "version" are used interchangeably. That might confuse a non-technical person.
> 
> Perhaps it would be better to standardise on the one term "version" when referring to a particular version?


ok, ´version´ it is!

**Comment by dsarkar** [comment]
DE

image

**Comment by dsarkar** [comment]
EN 

image

**Comment by dsarkar** [comment]
@Ein-Tim and @MikeMcC399 

I appreciate very much all your help! I will merge this now since we have gone over this serval times. However, should you see anything to improve, go ahead and let us know, and we fix it.

Many thanks again!

**Comment by MikeMcC399** [comment]
@dsarkar 
See comment in merged 
https://github.com/corona-warn-app/cwa-website/pull/852#issuecomment-776805936
as I think that https://www.coronawarn.app/en/faq/#minimum_requirements should be linking to #ios135

**Comment by dsarkar** [comment]
@MikeMcC399 Yes, thanks. I correct it in this PR.

**Comment by MikeMcC399** [comment]
@dsarkar 
> Yes, thanks. I correct it in this PR.

It seems only the DE version, not the EN version was corrected.

Since this PR is closed and in any case it is getting quite long I opened a new issue https://github.com/corona-warn-app/cwa-website/issues/874 to track this point.

**Pull request merged**
