### PR TITLE
Link to test portal

### PR DESCRIPTION
**Pull request by dsarkar**
Internal Tracking ID: [EXPOSUREAPP-8313](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8313)

### CODE REVIEW

**Comment by dsarkar** [comment]
main page

image


all other pages

image

**Comment by Ein-Tim** [comment]
@dsarkar 

I'd consider to change the wording so that it gets clear that this only refers to RAT and not PCR tests. 
Maybe "Wo kann ich einen Schnelltest machen?"? 

If you like the suggestion I can open a PR.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I'd consider to change the wording so that it gets clear that this only refers to RAT and not PCR tests.

The database of test centers is incomplete, however it is not true that in general no PCR tests are offered. You can even search by PCR test.

image

Searching using the PLZ of Munich main station 80335 doesn't find any PCR test centers in Munich, but it does show one in Zorneding, 22km away from the center of Munich.

@dsarkar 
How can the database of test centers be improved and made more complete?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks, I did not know this. Always thought it only lists rapid antigen testing sites, since the domain also is https://map.schnelltestportal.de. 

Thank you again! 👍

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The domain name and the title are misleading. Search even finds test centers which **only** offer PCR tests
e.g. Covidzentrum Berlin Mitte, Schröderstraße 1, 10115 Berlin.

**Comment by Ein-Tim** [comment]
Yeah... I hope they open source the site soon so that we can report issues reg. the site in the respective repo.

**Pull request merged**
