### PR TITLE
Add new FAQ entry `rec_cert_where` on how and where to get a certificate of recovery (Addresses #3098)

### LINKED ISSUE #3098: Add information on how to receive a certificate of recovery to the FAQs
## Feature description

The FAQs should hold information on how & where the user is able to obtain an EU digital COVID certificate of recovery.

## Problem and motivation
In the past I explained how to get such a certificate quite often on Twitter. It seems like the information is not yet easy to find for most users, so a CWA FAQ entry would help here.

Some examples of me explaining this:
- https://twitter.com/EinTim2/status/1567153516199772162?s=20&t=sTTtSs-hSmZA7wdLdOGfWw
- https://twitter.com/EinTim2/status/1548698786968616961?s=20&t=sTTtSs-hSmZA7wdLdOGfWw
- https://twitter.com/EinTim2/status/1544757643423936513?s=20&t=sTTtSs-hSmZA7wdLdOGfWw
- https://twitter.com/EinTim2/status/1544696752493805569?s=20&t=sTTtSs-hSmZA7wdLdOGfWw

## Is this something you're interested in working on

Yes

---
Internal Tracking ID: [EXPOSUREAPP-14047](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14047)

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR adds a new FAQ entry which explain where and how to get a certificate of recovery.

## What was changed
The files
- https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq.json
- https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq_de.json

were changed.

## Screenshots
| German | English |
|---|---|
| German | English |

## Additional information

I was not able to test these changes using cypress, sorry! I'm working on fixing Cypress in my environment.

---

**Closes #3098**

---
Internal Tracking ID: [EXPOSUREAPP-14047](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14047)

### CODE REVIEW

**Comment by Ein-Tim** [comment]
@MikeMcC399 If you find some time in the next days, I'd appreciate your feedback on the English text in this PR. Thanks and enjoy your Sunday!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- The English is fine. 

- Regarding the content, I posted two official FAQs in #3098 for comparison. They both limit the validity to 3 months / 90 days. The second one also mentions the Gesundheitsamt.

Since there is almost no activity here in this repository from the side of the Open Source Team for the last 6 weeks, I'm reluctant to invest much time in PRs at the moment.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> They both limit the validity to 3 months / 90 days. The second one also mentions the Gesundheitsamt.

Yes, I'll adapt the text in this PR.

> Since there is almost no activity here in this repository from the side of the Open Source Team for the last 6 weeks, I'm reluctant to invest much time in PRs at the moment.

I understand this!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> I was not able to test these changes using cypress, sorry! I'm working on fixing Cypress in my environment.

Are you using Apple M1? I proposed in https://github.com/corona-warn-app/cwa-website/issues/2980 to upgrade Cypress to 10.2 however there was no response. Cypress is now available as version 10.7, whereas cwa-website is still using 9.7. If you need native M1 support, then please comment in the above issue and I will open a new issue to migrate to the latest Cypress version. Of course any configuration change will need the support of the Open Source Team to perform a final test and merge.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, I'm using an Apple M1 chip.

I'll add a comment to the issue you referenced, thanks!

**Comment by Ein-Tim** [comment]
@dsarkar Are there any plans to review this PR?

**Comment by dsarkar** [comment]
@Ein-Tim Yes, we have forwarded this. I will come back to you on Monday hopefully.

**Comment by Ein-Tim** [comment]
@dsarkar Any update on this?

**Comment by Ein-Tim** [comment]
@dsarkar Reminder on this PR.

**Comment by Ein-Tim** [comment]
@dsarkar

Will you come back to this PR?

**Comment by dsarkar** [comment]
@Ein-Tim Yes, sorry for the delay !

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@Ein-Tim Thanks a lot for your efforts, approved!

**Review by GisoSchroederSAP — APPROVED** [review]
Double-checked with the tough guidelines of BMG;
so far, this is acceptable to be communicated, as it explains the "usual" way of doing to retrieve a recovery certificate.
=> approved; thanks for your work!

**Pull request merged**
