### PR TITLE
Update eventregistration texts

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR updates the eventregistration texts to reflect that the feature is available for quite some time now. It also removes an extra whitespace.

## Screenshots

| German | English |
|---|---|
| German | English |

---
Internal Tracking ID: [EXPOSUREAPP-14046](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14046)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Are any health authorities currently using the process of providing a TAN for event [warn for others](https://www.coronawarn.app/en/faq/results/?search=&topic=application#warn_for_others)?

Presumably the information from https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Kontaktperson/Management.html also applies to this feature. (Die Empfehlungen des RKI zur Kontaktpersonen-Nachverfolgung bei SARS-CoV-2-Infektionen sind ab dem 2.5.2022 nicht mehr gültig.)

image

In addition individual Health Authorities had to apply to take part in this scheme (see https://www.coronawarn.app/assets/documents/DE_CWA_RKI-Plakat_Stellvertreter-Warnung.pdf) using onboarding_cwa_health_authorities@t-systems.com. I don't remember if there was ever a list of which health authorities used this.

**Comment by Ein-Tim** [comment]
@MikeMcC399

I don't know if the process of warning others who were checked in to the same event via a TAN is in active use at the moment.

I only know that there weren't many health authorities who ever supported this feature, so I doubt that this is still (widely) used, also due to the fact that check ins are rarely used anymore.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the PR and updating the text.

**Comment by Ein-Tim** [comment]
@dsarkar 

Thanks for reviewing and merging!

**Comment by dsarkar** [comment]
Thanks @Ein-Tim! We are also happy to be back on board ! Also, good to see you that you and other community members keep on going with contributing to this project!

**Comment by Ein-Tim** [comment]
This PR causes the cypress test to fail. Sorry! I don't know how to fix that.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> This PR causes the cypress test to fail. Sorry! I don't know how to fix that.

- Unfortunately the Cypress test expects exact text matches. I don't think this is a good test strategy because it makes the test too sensitive to changes, however I suggested how to fix it in issue #3115. Hopefully you can use this suggestion and submit a new PR.
- It would be good to test any changes with Cypress before merging.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks for the issue, PR follows in the due course of today.

**Pull request merged**
