### PR TITLE
Add Cypress check for FAQ #mask_rules

### PR DESCRIPTION
**Pull request by MikeMcC399**
- This PR adds the anchor FAQ `#mask_rules` to be checked by the Cypress test spec [cypress/integration/app_to_web.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/app_to_web.js)

- The new anchor is planned to be added with [CCL 3.3](https://github.com/corona-warn-app/cwa-app-ccl/milestone/6). See also response from @mlenkeit in https://github.com/corona-warn-app/cwa-app-ccl/pull/102#issuecomment-1243757234.

- Since the FAQ article `#mask_rules` has not yet been created in this repository, this PR is submitted in Draft state. Also, since there is as yet no branch release/2.27.x, the PR targets the `master` branch.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Since there are other anchors which should be added for CCL 3.3, I am closing this draft and will resubmit after CCL 3.3 is finalised. That will be more efficient in terms of submission and testing.

**Comment by mlenkeit** [comment]
> Since there are other anchors which should be added for CCL 3.3, I am closing this draft and will resubmit after CCL 3.3 is finalised. That will be more efficient in terms of submission and testing.

@MikeMcC399 which other anchors do you think are missing for CCL 3.3? AFAIK, `#mask_state` is the only new one...

**Comment by MikeMcC399** [comment]
Do not merge until the FAQ article `#mask_rules` is available

**Comment by MikeMcC399** [comment]
- Closed, since the change was already made by https://github.com/corona-warn-app/cwa-website/commit/01f332b53cc46849da65616da7f5961eda20bd91

**Pull request closed without merging**
