### PR TITLE
Android Screenshots for Version: 2.9.0

### PR DESCRIPTION
**Pull request by Corona-Warn-App-Technical-User**
Android Screenshots for Version: 2.9.0

### CODE REVIEW

**Comment by MikeMcC399** [comment]
"Max, Mustermann" is shown incorrectly in Android screenshots, so I submitted https://github.com/corona-warn-app/cwa-app-android/issues/3994 to report the issue.

**Comment by MikeMcC399** [comment]
Merged PR https://github.com/corona-warn-app/cwa-app-android/pull/3997 fixes the "Max, Mustermann" screenshot issue corona-warn-app/cwa-app-android#3994 for 2.9.x.

**Comment by MikeMcC399** [comment]
@kaddaSz 

The PR "Correct to "Mustermann, Max" in certificate screenshots (EXPOSUREAPP-9233) (COMMUNITY)" https://github.com/corona-warn-app/cwa-app-android/pull/3997 is already included in [v2.9.0-RC1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.9.0-RC1) so I don't understand why the screenshots for [v2.9.0-RC2](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.9.0-RC2) do not reflect this fix.

How are these screenshots generated?

I generated screenshots locally in Android Studio for PR https://github.com/corona-warn-app/cwa-app-android/pull/3997, and they look like this:

[9233-screenshots.zip](https://github.com/corona-warn-app/cwa-app-android/files/7077601/9233-screenshots.zip)

I checked also for screenshots which I generated from [v2.9.0-RC2](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.9.0-RC2) using Android Studio, and they are consistent with the "Mustermann, Max" being applied. 

So something seems to have gone wrong with the screenshots uploaded to this website PR.

**Comment by kaddaSz** [comment]
@MikeMcC399:
if I look at the android screenshots from the last commit I did to this PR and check all the files you generated on your own 
(9233-screenshots.zip) I don't see a difference regarding the name "Mustermann, Max". 

Screenshot 2021-09-02 at 13 45 27

Could you please describe in more details what is missing at the new screenshots? Maybe I missed something.

**Comment by MikeMcC399** [comment]
@kaddaSz 
My apologies. I'm afraid that I made a mistake!

I checked again today and the branch https://github.com/corona-warn-app/cwa-website/tree/admin/Android-screenshots-for-version-2.9.0 with commit https://github.com/corona-warn-app/cwa-website/commit/87f395e741e35da31c0a9e8f3f73b3deb379163b is fine concerning the "Mustermann, Max" formatting.

Thank you very much for cross-checking!

**Comment by MikeMcC399** [comment]
Issue https://github.com/corona-warn-app/cwa-app-android/issues/4019 "Test certificate screenshot wrong content" opened in the Android repository since this is a problem with the automatic screenshot generation in CWA 2.9.0-RC2.

**Comment by MikeMcC399** [comment]
Can this PR be closed? It seems that it may be obsolete after the opening of PR https://github.com/corona-warn-app/cwa-website/pull/1707 by @larswmh.

`npm start`
run locally on the branch `admin/Android-screenshots-for-version-2.9.0` fails with errors starting with

```
Error: Panini: rendering error occured.
Error: Panini error: no layout named "science" exists.
```

**Comment by MikeMcC399** [comment]
Please close, since this PR is now obsolete. 
2.9 screenshots have been published through PR https://github.com/corona-warn-app/cwa-website/pull/1692.

**Pull request closed without merging**
