### PR TITLE
Fix form responsive FAQ results and clean button

### PR DESCRIPTION
**Pull request by 10delin**
Fix size form, clean button position and fix form responsive.
Here is a video with the changes: https://user-images.githubusercontent.com/56647378/161027712-edbb0f73-79c0-4037-a5c9-9e9a3f0c5750.mp4

### CODE REVIEW

**Comment by svengabr** [comment]
I took a look at the changes locally and it looks very good now. Thanks @10delin !

**Review by svengabr — APPROVED** [review]

**Comment by svengabr** [comment]
@MikeMcC399 I have resolved the conflicts now. Also I have added screenshots before/after.

Note that this is just for the detailed FAQ screen. The same is going to happen for the FAQ landing page in another PR later today or tomorrow.

**Comment by MikeMcC399** [comment]
- This PR is related to https://github.com/corona-warn-app/cwa-website/issues/2601

**Comment by MikeMcC399** [comment]
@svengabr 

> Note that this is just for the detailed FAQ screen. The same is going to happen for the FAQ landing page in another PR later today or tomorrow.

Thanks for the hint. I confirm that it looks good on the detail FAQ screen https://www.coronawarn.app/en/faq/results/, with or without a search term present in the search box.

**Pull request merged**
