### PR TITLE
Update page-index.html: Remove sticky app download banner

### PR DESCRIPTION
**Pull request by dsarkar**
Remove:

image

---
Internal Tracking ID: [EXPOSUREAPP-15175](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15175)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@dsarkar 

Will you also change other places which provide app store download information?

For example:
https://www.coronawarn.app/en/faq/results/#where_to_get

**Comment by Ein-Tim** [comment]
The app will continue to be available for some more time so that the last version can be released and rolled out, see also #3521. In my opinion, we can still merge this PR tomorrow, but that's not approved by the team. @dsarkar Do you want me to check internally how we want to proceed here?

**Comment by dsarkar** [comment]
@Ein-Tim Yes, please, check internally, if this should be merged under given circumstances.

**Comment by Ein-Tim** [comment]
Okay, we will keep the banner until the app is removed from the stores.

**Comment by Ein-Tim** [comment]
This PR could be merged now

**Pull request merged**
