### PR TITLE
Fix/FAQ vc_2of1

### PR DESCRIPTION
**Pull request by dsarkar**
image

image

### CODE REVIEW

**Comment by dsarkar** [comment]
FAQ #vac_booster_jj:

**DE**
image

**EN**
image

**Comment by Ein-Tim** [comment]
@dsarkar Should the "UPDATE" part of #vac_booster_jj be updated?

**Comment by dsarkar** [comment]
@Ein-Tim Alright, suggestion: Move the link up:

"

**Update 2. February 2022:**
See this FAQ article regarding [2/1 Vaccination certificates](https://www.coronawarn.app/en/faq/#vc_2of1).
sap2
"

**Comment by dsarkar** [comment]
EN
image

DE
image

**Pull request merged**
