### PR TITLE
Remove references to RKI KPI archive

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/3046 "Link to RKI archived app statistics gives 404 error" by removing references which use the link https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html, since this link is no longer available on the [RKI website](https://www.rki.de).

## Verification

`npm test`

Single test on production system
`npx cypress run -s cypress/integration/hybrid/check_links.js -c baseUrl=https://coronawarn.app`

---
Internal Tracking ID: [EXPOSUREAPP-13688](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13688)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
See comment in https://github.com/corona-warn-app/cwa-website/issues/3046#issuecomment-1193280257 from @Ein-Tim who suggested an alternate resolution by linking to the blog post:
- https://www.coronawarn.app/en/blog/2021-10-01-facts-and-figures/
- https://www.coronawarn.app/de/blog/2021-10-01-facts-and-figures/

**Comment by MikeMcC399** [comment]
Waiting for feedback now about whether this should be merged or whether the blog link should be used instead.

**Comment by MikeMcC399** [comment]
I checked the data https://www.coronawarn.app/de/blog/2021-10-01-facts-and-figures/ and all historical statistics concerning:
- downloads
- test results
- test result sharing

are all available on https://www.coronawarn.app/en/analysis/

The only statistic which is no longer published concerns the number of calls to the hotlines.

My opinion is that most people will be satisfied with the data in the dashboard and  they will not need any link to the blog post https://www.coronawarn.app/de/blog/2021-10-01-facts-and-figures/ since most of the figures published there are redundant to the figures stored on https://www.coronawarn.app/en/analysis/.

This PR is ready for review again and merging if accepted.

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting issue and offering a fix. For the time being this seems to be a good solution.

**Pull request merged**
