### PR TITLE
refactor: remove moment.js from eventregistration bundle

### PR DESCRIPTION
**Pull request by mojoaxel**
The PR removes `moment` from the `eventregistration` bundle (It is still used in the blog-preprocessing).

### Why?

* moment is BIG. Removing it reduces the distribution bundle size from 679 kB to 318 kB!
* moment is [deprecated](https://momentjs.com/docs/#/-project-status/).
* moment is not needed:
  * testing if a string is a valid date can easily be done in javascript.
  * getting a unix timestamp from a date is also basic javascript.
* moment was not mentioned in the THIRD-PARTY-NOTICES.
* moment was only installed as devDependency and should not used in dist bundles.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@mojoaxel 
It looks like this PR partially addresses https://github.com/corona-warn-app/cwa-website/issues/1168.
Thank you!

**Comment by dsarkar** [comment]
@mojoaxel Thanks. We will review this.

**Comment by mojoaxel** [comment]
If that helps here are some quick "test" I did to ensure my functions did what they are suppose to do.

```
> dateTimeToUnixTimestamp("2021-01-01", "12:00")
1609498800
> moment("2021-01-01 12:00").format("X")
"1609498800"
```

```
> isValidDate("2021-01-01")
true
> moment("2021-01-01").isValid()
true
```

```
> isValidDate("2021-01-40")
false
> moment("2021-01-40").isValid()
false
```

**Comment by svengabr** [comment]
> 
> 
> @mojoaxel
> It looks like this PR partially addresses #1168.
> Thank you!

Partially addresses yes, but unfortunately it does not fix it.

I did a test locally and I cant find any bugs in this pull request so I will approve this pull request.

Thanks for your contribution @mojoaxel

**Review by svengabr — APPROVED** [review]

**Comment by Ein-Tim** [comment]
FYI: #1706 reverts this PR as it caused a quite significant error: #1703

**Pull request merged**
