### PR TITLE
Add a reference to the science blog (Closes #1605)

### LINKED ISSUE #1605: No reference to science blog in `data_donation_and_EDUS` FAQ entry
## Where to find the issue
EN: https://www.coronawarn.app/en/faq/#data_donation_and_EDUS
DE: https://www.coronawarn.app/de/faq/#data_donation_and_EDUS

## Describe the issue
There is no reference to the [science blog](https://www.coronawarn.app/en/science/) in this FAQ entry.

## Suggested change
Add a reference to the science blog to this entry.

## Additional information
I will provide a PR for this.

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR adds a reference to the science blog to the FAQ entry "data_donation_and_EDUS".

<details>
<summary>Preview of the changes</summary>

| English | German |
|---|---|
|EN| DE|

</details>

---

**Closes #1605**

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@Ein-Tim I will wait for @MikeMcC399 's verdict before merging, since he opened the issue.

**Review by MikeMcC399 — APPROVED** [review]
LGTM!

**Comment by MikeMcC399** [comment]
@dsarkar 
>  I will wait for @MikeMcC399 's verdict before merging, since he opened the issue.

In fact @Ein-Tim opened the issue https://github.com/corona-warn-app/cwa-website/issues/1605, but I checked anyway and it looks fine to me!

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 ;-) Thanks.

**Pull request merged**
