### PR TITLE
Update Cypress to 9.6.1

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR implements the suggestion https://github.com/corona-warn-app/cwa-website/issues/2900 to update Cypress from version 7.7.0 to version 9.6.1.

## Local update

After this PR is merged, users with a local cloned copy of [cwa-website](https://github.com/corona-warn-app/cwa-website) may execute `npm install` at any time to update their local Cypress installation to version 9.6.1. This can be checked with `npm ls cypress` which should then show `cypress@9.6.1` in the output.

## Verification

Execute `npm run test` before and after `npm install` is executed. Both should be successful.

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the PR!

**Review by thorbenkuro — COMMENTED** [review]
Thanks for the PR! Looks good to me and works as expected.

**Comment by MikeMcC399** [comment]
@thorbenkuro 
Could you explain your changes please?

**Comment by thorbenkuro** [comment]
@MikeMcC399 
Sorry for the confusion! I reverted my commit and everything should be ready to merge.

**Comment by MikeMcC399** [comment]
@thorbenkuro 

The commit definitely had me confused before you reverted it, as the package-lock.json was suddenly version 1!

**Pull request merged**
