### PR TITLE
iOS Screenshots for Version: 2.3.0

### PR DESCRIPTION
**Pull request by Corona-Warn-App-Technical-User**
iOS Screenshots for Version: 2.3.0

### CODE REVIEW

**Review by Ein-Tim — APPROVED** [review]
LGTM! 

Some screenshots are from an iPhone without notch, but this is alright, I think.

**Comment by dsarkar** [comment]
obsolete with https://github.com/corona-warn-app/cwa-website/tree/svengabr/screenshot-archive

**Comment by Ein-Tim** [comment]
@dsarkar Could you maybe explain what purpose the screenshot archive has? And why it makes this PR obsolete? 

Thank you!

**Comment by dsarkar** [comment]
@Ein-Tim It will show from now on past screenshot versions. starting with 2.2

**Comment by Ein-Tim** [comment]
Okay thanks, and why is this PR obsolete then?

**Comment by Ein-Tim** [comment]
Obsolete because of: https://github.com/corona-warn-app/cwa-website/commit/90ea0c6988b11ccf26e37ae477b0d0f6a15c0a69

**Pull request closed without merging**
