### PR TITLE
Update #glossary_validity: Replace validity time

### LINKED ISSUE #2911: Out of date / inconsistent text for "Certificate of recovery" in Glossary validity
## Where to find the issue

- https://www.coronawarn.app/en/faq/results/#glossary_validity "Validity of an EU Digital COVID Certificate"
- https://www.coronawarn.app/de/faq/results/#glossary_validity "Gültigkeit eines EU digitalen COVID-Zertifikats"

## Describe the issue

The English and German versions of the Glossary article `#glossary_validity` contain different and outdated texts concerning the validity of Certificates of Recovery.

The applicable legal regulation is [Gesetz zur Verhütung und Bekämpfung von Infektionskrankheiten beim Menschen (Infektionsschutzgesetz - IfSG) § 22a Impf-, Genesenen und Testnachweis bei COVID-19; COVID-19-Zertifikate; Verordnungsermächtigung](https://www.gesetze-im-internet.de/ifsg/__22a.html) which says:

"_... die Testung zum Nachweis der vorherigen Infektion mindestens 28 Tage und höchstens 90 Tage zurückliegt._"

### Describe the issue (EN)

The English-language FAQ article [#glossary_validity](https://www.coronawarn.app/en/faq/results/#glossary_validity) contains the text:

"_Certificate of recovery_

_In the case of a certificate of recovery, according to the EU eHealth Network, the effective validity is set at 'date of the holder's first positive PCR test result' plus 180 days_"

The German regulations define 90 days, not 180 days - see [Infektionsschutzgesetz - IfSG) § 22a](https://www.gesetze-im-internet.de/ifsg/__22a.html).

### Describe the issue (DE)

The German-language FAQ article [#glossary_validity](https://www.coronawarn.app/de/faq/results/#glossary_validity) links to the outdated https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Genesenennachweis.html "Fachliche Vorgaben des RKI für COVID-19-Genesenennachweise – außer Kraft".

The FAQ article says:

"_Genesenenzertifikat_

_Bei einem Genesenenzertifikat ist die maximale fachliche Gültigkeit laut dem [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Genesenennachweis.html) festgelegt auf 90 Tage._"

## Suggested change

1. Ensure that the English and German version articles for `#glossary_validity` contain essentially the same information.
2. Decide whether to continue to link to the RKI page https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Genesenennachweis.html or whether to directly reference the [Infektionsschutzgesetz - IfSG) § 22a](https://www.gesetze-im-internet.de/ifsg/__22a.html) in both FAQs.

### PR DESCRIPTION
**Pull request by larswmh**
Fixes #2911 

- In English, the glossary now shows 90 days instead of 180 days of validity for certificates of recovery
- Replace outdated link with link to German Infection Protection Act
- Fix missing "<" in glossary "digital_certificate"

image
image

### CODE REVIEW

**Review by Ein-Tim — APPROVED** [review]
LGTM!

**Review by GisoSchroederSAP — APPROVED** [review]
As far as I can see, those changes are okay and help to sharpen the FAQ.
Unfortunately, there is no public "official" English translation for the referred legal documents, so we must refer to the German publications.

Approved.

**Review by MikeMcC399 — APPROVED** [review]
LGTM

**Comment by dsarkar** [comment]
Good morning @Ein-Tim and @MikeMcC399 Thanks for reviewing and commenting!

**Pull request merged**
