### PR TITLE
Bump current iOS app version

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR bumps the current iOS app version from 2.21.1 to 2.21.2.

GitHub release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.21.2

### CODE REVIEW

**Comment by MikeMcC399** [comment]
I still wonder why it is not part of the Open Source Team's release process to ensure that the version numbers in the web are synchronized with each bug-fix release.

It's "reverse engineering" when @Ein-Tim from the community is noticing releases in the store and then submitting PRs to correct the situation.

**Comment by Ein-Tim** [comment]
I think most sense would make a bot which notices when a new version is released to GitHub (https://github.com/corona-warn-app/cwa-app-ios/releases / https://github.com/corona-warn-app/cwa-app-android/releases), then checks in the gulpfile whether this version is already set and if not opens a PR.

But for me it's not much work, so I'm fine with doing this.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Will check if it worth the effort to create a bot for this task.

**Comment by Ein-Tim** [comment]
Okay @dsarkar, I will continue to provide these PRs, until I'm told to stop 👍

**Comment by MikeMcC399** [comment]
- This is a bit related to https://github.com/corona-warn-app/cwa-app-android/issues/3698#issuecomment-1105054979 as you cannot be sure that a release marked on GitHub means that a release has been submitted to one of the app stores. There are manual steps involved which are not visible on GitHub.

**Review by svengabr — COMMENTED** [review]
Changes approved

**Comment by Ein-Tim** [comment]
@MikeMcC399 Under iOS, if a version is released to the App Store, it can instantly be downloaded manually. 

Under Android I agree, however, I suggest you open a new issue reg. the question when to update the gulpfile:
a) When a GitHub release is created
b) When the staged rollout begins
c) When the stated rollout ends.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

It has to be linked to the store availability, since the website says:

"Here we have briefly summarized the most important tips for using the app:

1. Download the current version of the app (iOS: 2.21.2 or Android: 2.21.1)"

- For iOS that is simple. As you say, a new version is available immediately for all users. For Android, it's more complicated and there is an unresolved topic under discussion in https://github.com/corona-warn-app/cwa-app-android/issues/3698.

- So I'll leave it first to @dsarkar to look at the possibility of automating the process.

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 We decided that we will not implement a bot for this task, since it seems that the effort will not pay off. Furthermore, not always the GH release notes are updated immediately, so it would not speed up the process. We improve internally the way the Corona-Warn-App Open Source Team is kept in the loop regarding roll out start, in order to decrease the delay between availability in the stores and information on the website.

**Pull request merged**
