### PR TITLE
Restructure build and server start for Cypress tests (resolves timeout #1993) V2

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves the timeout issue which may occur when testing the [cwa-website](https://github.com/corona-warn-app/cwa-website) locally as described in "Timeout running Cypress test" https://github.com/corona-warn-app/cwa-website/issues/1993. It follows on from the closed PR https://github.com/corona-warn-app/cwa-website/pull/1997 which encountered a syntax error on some Windows platforms. Separating serial commands with a semicolon ";" turned out not to be accepted everywhere.

It prepares for a migration to Cypress 8 or 9, however the PR itself does not change the Cypress version from its current `"^7.7.0"`.

### `package.json`

1. A new script `start-server` is added to `package.json`. It starts the `browsersync` server via `gulp start` which can then be used for manual testing or for automated Cypress testing. The script assumes that there is a complete web built and available in the `public` directory.
2. The scripts `test:open`, `test:chrome` and `test:firefox` are modified to first build the web, then start the server, instead of attempting to start the server before the web is built. The original scripts are split into two parts, for example:
    - `"test:open:phase2": "start-server-and-test start-server http://localhost:8000 cypress:open"` runs only the `start-server-and-test` command, which is chained in
    - `"test:open": "run-s build test:open:phase2"` to run serially using `run-s` after `build` (phase1 is the `build`, followed by phase2 which is the `start-server-and-test`)
3. The scripts `cypress:run:chrome` and `cypress:run:firefox` are modified to specify headed mode explicitly (option `--headed`), which is the default for the currently used Cypress 7 version. The default changes in Cypress 8, so this change prepares the scripts for any future update by making them upwards compatible. (See [Cypress Migration Guide](https://docs.cypress.io/guides/references/migration-guide).)
4. The version number of `package.json` is incremented to 1.1.0. The name of "Corona-Warn-App" is used consistently.

### `gulpfile.js`

1. A new task `start-server` is added which starts the `browsersync` server then watches for changes.
2. The `default` task is equivalent to and compatible with the previous version of the `default` task. For conciseness it calls the new task `start-server` instead of individually calling `server` then `watch`.

### Other changes

- `npx browserslist@latest --update-db` has updated caniuse-lite to the latest version

## Impact

- The PR is compatible with all commands documented in README.md.

- There is no change to the `gulp build` task so there should be no impact to the web deployment.

- `start-server` is a new npm script.

- The npm package [npm-run-all](https://www.npmjs.com/package/npm-run-all) is installed to be able to run scripts serially in npm through the `run-s` CLI command. See [npm-run-all README](https://github.com/mysticatea/npm-run-all#readme) documentation for installation and usage information.

## Verification Environment

Cypress 7.7.0

### Windows 10 (21H1 Home)

Google Chrome 95.0.4638.69 
Mozilla Firefox 94.0

Since PR https://github.com/corona-warn-app/cwa-website/pull/1997 failed on Edition Windows 10 Enterprise Version 21H1 and Edition Windows 10 Home Version 20H2 it would be good to verify in these environments too.

Note on Windows that the `npm run test:prepare` command relies on running in the bash shell.
Check with `npm config get shell-script` and if necessary (for instance, if the key is `undefined`) execute

`npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"`

This is not new with this PR.

### Ubuntu 20.04.3

Google Chrome 95.0.4638.69 
Mozilla Firefox 93.0

For Firefox execute once:
`sudo apt install ffmpeg`
otherwise Cypress tests timeout

### Mac

I don't have this environment, so feedback welcome.

## Verification

Tests are carried out in a bash terminal window from the root directory of a cloned copy of [cwa-website](https://github.com/corona-warn-app/cwa-website).

No timeouts should occur during the tests. Only `start-server` is new. All other commands listed below should not show any regressions compared to before this PR.

Execute
`npm install`
once from this branch before running tests.

### Test `start-server`

```bash
npm run build
npm run start-server
```

A browser window http://localhost:8000/en/ will be started displaying the CWA website. 

Then, in an separate terminal window, execute:
```bash
npx cypress open
```
Cypress opens. (It is helpful to run Cypress standalone first if the version has not yet been run on a system, as the first time it starts it does some checking which takes time and can cause npm scripts to timeout.)

Close browser window, exit / kill terminal process.

### Test `start`

```bash
npm start
```

The same as the previous test. A browser window http://localhost:8000/en/ will be started displaying the CWA website.
Kill the terminal process.

### Test `test:open`

```bash
npm run test:open
```
In the Cypress console click on `applink_spec.js` to run it.
A new window opens and the three tests should run successfully.
In the Cypress console click on Stop.
Close the Cypress console.
Kill the terminal process.

### Test `test:chrome`

```bash
npm run test:prepare
npm run test:chrome
```

All tests should be run automatically in a Google Chrome browser.
When the tests complete, the line
`All specs passed!` should appear in the terminal window.

### Test `test:firefox`

```bash
npm run test:prepare
npm run test:firefox
```

All tests should be run automatically in a Mozilla Firefox browser.
When the tests complete, the line
`All specs passed!` should appear in the terminal window.

(Note this test has not always run successfully before the PR. It has timed out sometimes.)

### Test `test`

This is equivalent to `test:chrome`.

```bash
npm run test:prepare
npm test
```

`npm test` and `npm run test` are interpreted the same by `npm`.

The success criteria is the same as for `test:chrome`.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@svengabr
@brifemu
@matriceria

I have used [npm-run-all](https://www.npmjs.com/package/npm-run-all) to solve the issue where ";" was causing the error `Task never defined: build;`

I have tested this successfully in VMware with Ubuntu 20.04 and Windows 10 Home (21H1).

I hope it will now run in all your environments as well!

**Comment by brifemu** [comment]
@MikeMcC399 

The problem with `npm run test:open` had been solved. That's a good new!

Now I get an error running `npm run test:prepare`. I guess it's another syntax error, maybe?

> $ npm run test:prepare
> 
> corona-warn-app-landingpage@1.1.0 test:prepare C:\Users\Brian\Documents\Workspace\cwa-website
> ./cypress/prepare.sh
> 
> '.' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! corona-warn-app-landingpage@1.1.0 test:prepare: `./cypress/prepare.sh`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the corona-warn-app-landingpage@1.1.0 test:prepare script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Brian\AppData\Roaming\npm-cache\_logs\2021-11-11T07_39_11_572Z-debug.log

It was tested on:

Edition	Windows 10 Enterprise
Version	21H1
Installed on	‎10/‎5/‎2021
OS build	19043.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by MikeMcC399** [comment]
Good morning @brifemu!
> 
> The problem with `npm run test:open` had been solved. That's a good new!

I'm very happy to hear that!

> Now I get an error running `npm run test:prepare`. I guess it's another syntax error, maybe?
> 
> > $ npm run test:prepare
> > corona-warn-app-landingpage@1.1.0 test:prepare C:\Users\Brian\Documents\Workspace\cwa-website
> > ./cypress/prepare.sh
> > '.' is not recognized as an internal or external command,
> > operable program or batch file.

This is an error that can occur on Windows and it is possibly the reason that the original script did not work.

I documented this a while back in https://github.com/corona-warn-app/cwa-website/blob/master/README.md:

#### Cypress under Microsoft Windows

If executing `$ npm run test:prepare` causes an error on Microsoft Windows

`'.' is not recognized as an internal or external command,`

ensure that [git](https://git-scm.com/downloads) is installed and execute the following command:

`npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"`

**Comment by brifemu** [comment]
@MikeMcC399 

Using `npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"` all work fine!

For me, it's ready to be merged.
Thank you so much for your support! Great work! 🚀

**Comment by MikeMcC399** [comment]
@brifemu 

Thanks for your testing and your "green light" to merge!

**Comment by matriceria** [comment]
It also works fine in mac!!

**Comment by MikeMcC399** [comment]
@matriceria 
> It also works fine in mac!!

Thank you very much for your test and confirmation!

**Comment by MikeMcC399** [comment]
I have added a note in the verification section about setting the npm key `script-shell` to the bash shell. This also was required previously for the full set of Cypress tests.

I am also checking with a newly-created Windows account to make sure I didn't miss anything else.

**Comment by MikeMcC399** [comment]
I successfully ran all tests on a clean new Windows 10 account after executing the necessary command:
`npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"`

Without this command npm runs scripts in the Windows 10 `cmd.exe`  command line interpreter and this is not compatible with [prepare.sh](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/prepare.sh) used by `npm run test:prepare` . A possible future enhancement would be to replace [prepare.sh](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/prepare.sh) by a gulp task which could make it platform and shell independent.

In this PR, the special script-shell setting is only needed to execute the existing `npm run test:prepare` command. 
`npm run test:prepare` is however a pre-requisite to execute `npm test` as was the case before this PR and as is described in [README.md#testing](https://github.com/corona-warn-app/cwa-website/blob/master/README.md#testing).

From my perspective this PR is ready for merge.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. We try to have a look at this tomorrow!

**Comment by MikeMcC399** [comment]
@dsarkar 
> We try to have a look at this tomorrow!

I don't know of any problems with this PR, so I hope you can merge it.

The only issues I have seen are unrelated to the PR itself. I use "[Norton 360](https://de.norton.com/products)" virus and firewall on Windows and I have to temporarily disable Auto-Protect and Smart-Firewall when I run the full test suite (`npm test`) otherwise the webserver dataflow is affected and the link checking can fail. I guess that the link checking causes quite a heavy data load which makes it overly sensitive. I had this problem before the PR but I didn't understand until now what was causing it and how to work around it.

**Comment by MikeMcC399** [comment]
Apart from solving a timeout issue, the PR also allows the cwa-website Cypress scripts to run on the latest Cypress Test Runner v9.0.0 released 11.11.2021 (see https://cypress.io/whats-new) if and when an upgrade to this version should be needed.

**Comment by MikeMcC399** [comment]
@dsarkar 
Will you be able to look at merging this PR soon? (I appreciate that you are very busy!)

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I'm sure you know, but just because the last 7 (If I have counted correctly) commits are all "Merge branch master" commits, @heinezen stated in: https://github.com/corona-warn-app/cwa-website/pull/554#pullrequestreview-529152391:
"You do not have to click the "Update branch" button every time there is a change. When we merge the PR, we will do that for you :)"

Maybe it would be good to leave it to the Open-Source Team to merge the branch master into PRs before they merge the PR?

But this is just a minor detail here (:

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I'm sure you know, but just because the last 7 (If I have counted correctly) commits are all "Merge branch master" commits, @heinezen stated in: [#554 (review)](https://github.com/corona-warn-app/cwa-website/pull/554#pullrequestreview-529152391): "You do not have to click the "Update branch" button every time there is a change. When we merge the PR, we will do that for you :)"
> 
> Maybe it would be good to leave it to the Open-Source Team to merge the branch master into PRs before they merge the PR?

I have rebased and forced pushed the changes. The history is now cleaner.

I now await feedback from the Open Source Team, if they want to accept it, request changes or reject it.

@brifemu and @matriceria already successfully tested it.

**Review by svengabr — APPROVED** [review]

**Comment by svengabr** [comment]
Changes are approved, thank you @MikeMcC399

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks you very much!

**Pull request merged**
