### PR TITLE
Solve issue url "[ 'http://localhost:8000' ]" is responding with HTTP status code NaN

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR updates

https://github.com/corona-warn-app/cwa-website/blob/0c52ddae35073311c9041c01aa04df5e88a13865/package.json#L85

to 1.15.4.

### Local

Execute

```bash
npm run open
```

and check that the logs show "HTTP status code 200" not "HTTP status code NaN" in the excerpt below:

```text
> start-server-and-test start-server http://localhost:8000 cypress:open

1: starting server using command "npm run start-server"
and when url "[ 'http://localhost:8000' ]" is responding with HTTP status code 200
running tests using command "npm run cypress:open"
```

## GitHub action

Similarly to the above, examine the action log files in:

https://github.com/corona-warn-app/cwa-website/actions/workflows/build-and-test.yml

for the job `test`. It should show "HTTP status code 200".

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Verified in https://github.com/corona-warn-app/cwa-website/actions/runs/4166768218/jobs/7211574836#step:6:8

This PR is ready for merge.

**Comment by dsarkar** [comment]
Good morning @MikeMcC399! Thanks for providing a PR, we will review it soon.

**Review by larswmh — APPROVED** [review]
Thanks for the PR @MikeMcC399!

**Review by dsarkar — APPROVED** [review]

**Comment by MikeMcC399** [comment]
Good morning @dsarkar and @larswmh !

I managed to get the package owner to fix `start-server-and-test` yesterday. Thanks for merging the update!

**Pull request merged**
