### PR TITLE
Remove TAN hotline info from footer

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR removes the number of the TAN hotline from the footer and adapts the corresponding test.

## What was changed?
- `src/data/global.json` (removal of the hotline info)
- `cypress/e2e/hotline.cy.js` (adapting of the tests to make them pass without TAN hotline info)

## Preview of the changes
You can find a live preview of the changes here: https://cwa-website-f1w1d7ydv-ein-tim.vercel.app

### CODE REVIEW

**Review by GisoSchroederSAP — APPROVED** [review]
Very attentive, thanx a lot!
Approved.

**Comment by MikeMcC399** [comment]
This should not be merged until after Jan 31, 2023.

**Comment by MikeMcC399** [comment]
No need to wait longer, as the TAN hotline already shut down. The recorded message is in place.

**Comment by larswmh** [comment]
Thanks for your PR @Ein-Tim!

**Comment by MikeMcC399** [comment]
Although the TAN checks were removed from the [Cypress hotline test](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hotline.cy.js) the test title was not changed:

https://github.com/corona-warn-app/cwa-website/blob/a3157f93534f906edd39b4cb9e47f0eae8b53c41/cypress/e2e/hotline.cy.js#L6

This shows in the logs of https://github.com/corona-warn-app/cwa-website/actions/workflows/cypress-test-prod.yml

See for example https://github.com/corona-warn-app/cwa-website/actions/runs/4150636512/jobs/7180428606#step:5:380

To clean up the change "and TAN " should be removed.

**Comment by Ein-Tim** [comment]
I'll provide a PR for this on Monday. Thanks @MikeMcC399!

**Pull request merged**
