### PR TITLE
Remove DCC ticketing screenshots

### LINKED ISSUE #2762: Remove `certificate_check` screenshots from screenshot page
## Where to find the issue
- https://www.coronawarn.app/en/screenshots/#ios_certificate_check
- https://www.coronawarn.app/de/screenshots/#ios_certificate_check
- https://www.coronawarn.app/en/screenshots/#android_certificate_check
- https://www.coronawarn.app/de/screenshots/#android_certificate_check

## Describe the issue
The feature "Certificate check for bookings" is not in use at the moment, as there is no validation service provider. The feature is de facto on ice without any process expected in the next months.
Thus, the screenshots should be removed from the page. 

## Suggested change
Remove the screenshots from the page. 

## Additional information
PR follows tomorrow. 

---
Internal Tracking ID: [EXPOSUREAPP-12844](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12844)

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description

This PR removes the DCC ticketing screenshots from the screenshots page.

## What was changed

- https://www.coronawarn.app/en/screenshots/#ios_certificate_check was deleted
- https://www.coronawarn.app/de/screenshots/#ios_certificate_check was deleted
- https://www.coronawarn.app/en/screenshots/#android_certificate_check was deleted
- https://www.coronawarn.app/de/screenshots/#android_certificate_check was deleted
- The corresponding, now unused, assets were deleted. 

## Additional information

This PR is based on the `release/2.21` branch & intended to be merged into this branch, it therefore has to be merged before PR #2677 is merged.

---

**Closes #2762**

### CODE REVIEW

**Comment by Ein-Tim** [comment]
@dsarkar 

I guess this needs internal approval?

**Comment by dsarkar** [comment]
Hi @Ein-Tim, Thanks for the PR, ans also to you: Happy Eastern! Best, DS

**Comment by Ein-Tim** [comment]
@dsarkar 

Thank you! Same back to you: Happy easter!

**Comment by dsarkar** [comment]
@Ein-Tim Thank you!

**Pull request merged**
