### PR TITLE
Add entry 'Cause 9002: Something went wrong (timeout)' as requested in #998

### PR DESCRIPTION
**Pull request by vaubaehn**
@GPclips kindly [invited to create a PR](https://github.com/corona-warn-app/cwa-app-android/issues/998#issuecomment-678142777) to add an entry to the FAQ concerning error message 'Cause 9002: Something went wrong. timeout' as discussed in #998.

Thanks to the support of @Jo-Achim and @Gladdi causes of this exception could have been identified and resolutions can be provided.

As requested, I added the entry to section "id": "notification", just below 'Cause 9002: ... (sqlite). You might consider to move the new entry down to section "resolved", as not too many users are affected and also possible resolutions are already provided. Instead, I'd suggest to move up 'Cause 9002: ... (sqlite)' to section 'common problems', as many users are affected from this exception.

If you find the text fitting to your needs, you'd also be able to use the already provided German translation.
Otherwise, feel free to adjust everything according to your needs.

Additional fix: In the English version of the FAQ, for entry notifications: Cause 9002 (sqlite) the 'Android/Google' tag is missing in the title. I complemented it, according to the corresponding German entry.

Closing remark: 'timeout' is written in small letters, according to the original error message. It is suggested to not use a capital letter at the beginning of the word, in order to avoid (even more) confusion, if at a later point in time another 'Cause: 9002 - Timed Out waiting for 60000 ms' might be added to the FAQ.

### CODE REVIEW

**Comment by tkowark** [comment]
Thanks a lot, @vaubaehn !!
@MarlisFriedl could you (and/or @OlMue) have a look at the new entry and provide your review?

**Comment by OlMue** [comment]
No problem, I will have a look

**Review by OlMue — APPROVED** [review]

**Comment by OlMue** [comment]
Some minor corrections and additions, but overall a great contribution! I won't move the new section it to "Resolved" yet, because otherwise people might not see it.
I will merge the PR as soon as the automatic checks have been completed.

**Comment by tkowark** [comment]
The automatic checks unfortunately will not complete for external PRs, since Github Actions do not allow to run for those (security reasons...). Local check on my machine worked, though. I'll merge this using administrator privileges, though.

**Comment by vaubaehn** [comment]
Hi @tkowark and @OlMue ,

thank you very much for merging! I'm glad to contribute a little to the whole. 😊

There are just some small issues according to the additional links added by @OlMue :
As this is an Android specific error, the link to the iOS section is maybe not needed.
Additionally, the Android specific link guides to Prioritized Background Activity according to battery optimisation, not network setup. It's always good to have that activated, but in this context maybe a little bit confusing?
At last, the links in the German FAQ point to sections in the English FAQ (en instead of de).

Thanks again, and all the best!

**Comment by OlMue** [comment]
@vaubaehn Thanks for your comments. I think you are right, so I removed the links to the FAQs again that I had added. This closes #317

**Pull request merged**
