### PR TITLE
Fix/faq relative links

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR fixes the issues with relative links from https://github.com/corona-warn-app/cwa-website/issues/2611 "Multiple broken links in FAQs (approx. 65)".

Two points are addressed:

1. non-working links using `../` construction are corrected
2. different ways of writing links to other sections are harmonized

Harmonization:

1. For language dependent directories, with a /en and a /de variant, the construct `../../directory` is used. This applies to  `'../../screenshots`, `'../../eventregistration` and  `'../../blog`
2. The simpler construct `'/assets` is used, since this is a language independent directory, instead of `../../../assets`.

### CODE REVIEW

**Comment by Ein-Tim** [comment]
This is partly a duplicate of https://github.com/corona-warn-app/cwa-website/pull/2610.

**Comment by Ein-Tim** [comment]
I think neither my PR #2610 nor this PR covers all links. There are some changes here I forgot in #2610 but also some from #2610 are missing here.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> This is partly a duplicate of https://github.com/corona-warn-app/cwa-website/pull/2610.

That is correct. I submitted this PR in draft status because I want to hear feedback from the Open Source Team about how they want to handle the issues. If they want to go your route and correct only the blog links first, that is OK with me. I would modify this PR accordingly to remove the blog changes.

> I think neither my PR https://github.com/corona-warn-app/cwa-website/pull/2610 nor this PR covers all links. There are some changes here I forgot in https://github.com/corona-warn-app/cwa-website/pull/2610 but also some from https://github.com/corona-warn-app/cwa-website/pull/2610 are missing here.

Again, I suggest to wait for feedback from the Open Source Team before putting in more effort into either of the two PRs. I believe I fixed all the bad blog links in the FAQs in this PR. I didn't compare the two PRs so far.

**Comment by MikeMcC399** [comment]
This PR is now ready for review and merging.

The full (updated) Cypress suite passes with no remaining errors.

```

       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ √  applink_spec.js                          00:01        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  blog_spec.js                             00:01        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  check_anchor_links.js                    00:57       35       35        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  check_links.js                           10:53       37       37        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  hotline_spec.js                          416ms        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  pages/eventRegistration.js               00:09        6        6        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    √  All specs passed!                        12:03       84       84        -        -        -


```

**Comment by Ein-Tim** [comment]
Fixes #2609

**Comment by svengabr** [comment]
Changes approved, thanks @MikeMcC399 !

**Pull request merged**
