### PR TITLE
Reponsive of FAQ's form fixed

### PR DESCRIPTION
**Pull request by 10delin**
Responsive of FAQ's form fixed with bootstrap grid

### CODE REVIEW

**Comment by MikeMcC399** [comment]
- Is this PR supposed to solve https://github.com/corona-warn-app/cwa-website/issues/2601?

**Review by svengabr — APPROVED** [review]

**Comment by svengabr** [comment]
Yes exactly @MikeMcC399 

I made one addition in my latest push, made the box on mobile bigger.

**Before**

before

**After**

after

**Comment by MikeMcC399** [comment]
@svengabr 

The box width of /en/faq/ looks good when the window width is dynamically decreased, however at full width screen on a desktop the box does not fully display the text.

image

**Comment by svengabr** [comment]
Yes, you are right. I made another small adjustment and I think it turned out much better. More space now.

en
de

**Review by MikeMcC399 — APPROVED** [review]
I can't see any more issues when re-sizing, so it looks good to go! 👍🏻

**Review by svengabr — APPROVED** [review]

**Pull request merged**
