### PR TITLE
9360 Science blog 4 DE

### PR DESCRIPTION
**Pull request by dsarkar**
Internal Tracking ID: [EXPOSUREAPP-9360](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-)

### CODE REVIEW

**Comment by Ein-Tim** [comment]
BTW is the change on `package-lock.json` intended?

**Comment by MikeMcC399** [comment]
@dsarkar
GitHub cannot manage in-line comments for index_de.md. The file, with 4MB, is too big. I guess this is caused by the embedded graphics.

**Comment by dsarkar** [comment]
@MikeMcC399 Yes, it's the interactive figs that are embedded.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the review. We are right now refactoring the interactive figs. Other changed that will be commited shortly: Setzten -> Setzen and commas.

**Pull request closed without merging**
