### PR TITLE
optimise app icons svg

### PR DESCRIPTION
**Pull request by mojoaxel**
Optimized the svg for the App-Icons:

## Filesize 

This brings a overall filesize reduction of 28,6 kB

| file                                                   | old size    | new size  |
| --------------------------------------------- |:-------------:| ------------:|
| App_Store_Badge_US-UK.svg      |   21,2 kB  |    11,1 kB |
| google-play-badge.svg                  |    26,8 kB |      8,3 kB |

### old
image

### new
image

The icons are based on the orginal icons from wiki-commons that are both in the public domain: [Apple](https://commons.wikimedia.org/wiki/File:Download_on_the_App_Store_Badge.svg), [Google](https://commons.wikimedia.org/wiki/File:Google_Play_Store_badge_EN.svg)

### CODE REVIEW

**Comment by mroderick** [comment]
Very nice 👍

**Comment by tkowark** [comment]
👍

**Comment by mroderick** [comment]
@tkowark a little GitHub tip, you might know it already.

If you use the "Rebase and merge" function of the merge button, then the extra merge commits in this branch are not added to the destination branch (`master`), keeping the history clean.

**Comment by tkowark** [comment]
Thanks for the hint ... But just to clarify, @mroderick , I've merged this PR using the Squash and Merge Functionality, so the merges are not part of the destination branch. Am I missing something?

**Comment by mroderick** [comment]
> I've merged this PR using the Squash and Merge Functionality, so the merges are not part of the destination branch. Am I missing something?

I should have checked the destination branch before chiming in. I apologise.

It looks like "Squash and merge" also does a rebase (which makes sense, since it's a new commit anyway), so it leaves no merge commits behind. All squeaky clean history! 🧼

**Comment by tkowark** [comment]
No worries. Always good to be reminded of best practices, and every now and then there are also new Github features that we're not aware of.

**Pull request merged**
