### PR TITLE
Remove broken URL (Addresses #3514)

### LINKED ISSUE #3514: Science 5 links to unavailable end-point svc90.main.px.t-online.de
The Science 5 blogs

- https://www.coronawarn.app/en/science/2022-03-03-science-blog-5/
- https://www.coronawarn.app/de/science/2022-03-03-science-blog-5/

refer to the disabled exposure notification endpoint http://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date. This URL currently returns HTTP error 404 (not found).

> A further option for estimating the active apps/devices (in the narrower sense) are the [files of the daily keys](http://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date) downloaded by the users of the CWA and provided via the CWA backend.

This link should be removed from the Science 5 blogs.

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description
This PR removes a URL that doesn't work anymore as the backend infrastructure is being shut down.

---

**Fixes #3514**

### CODE REVIEW

**Comment by dsarkar** [comment]
@Ein-Tim I thought it was agreed, not to remove broken links, but to mark them as "outdated".

**Comment by Ein-Tim** [comment]
@dsarkar Thanks for the reminder, please let me clarify with the team what our maintenance strategy for the science blogs is.

**Comment by Ein-Tim** [comment]
Yes, I will come back to you as soon as I have more information.

**Comment by Ein-Tim** [comment]
I have not forgotten about this and I hope to come back to you sooner than later.

**Comment by Ein-Tim** [comment]
We agreed to go another way, although implementing the changes that are necessary for this might take some time.

**Pull request closed without merging**
