### PR TITLE
FAQ google_security_vulnerability

### PR DESCRIPTION
**Pull request by dsarkar**

### CODE REVIEW

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-6979](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6979)

**Comment by vaubaehn** [comment]
Hi @dsarkar ,
imho the text is not quite complete in some small but important points, and may people probably worry more than necessary.
Original:

> On April 27, 2021, reports appeared that announced a vulnerability in the Exposure Notification Framework (ENF) in the Android operating system. This vulnerability allowed pre-installed apps on Android smartphones to access system log files, thus reading ENF data that is also provided by the Corona-Warn-App (CWA). Google has provided a fix for Android, and says that it has now been rolled out up to 98%. All Android versions that use the Google Play Services below version 21.15 are affected.

I'd suggest to change it to:
On April 27, 2021, reports appeared that announced a vulnerability in the Exposure Notification Framework (ENF) in the Android operating system. This vulnerability allowed `manufacturer` pre-installed `system` apps on Android smartphones to access system log files, thus reading ENF data that is also provided by the Corona-Warn-App (CWA). Google has provided a fix for Android, and says that it has now been rolled out up to 98%. All Android versions that use the Google Play Services below version 21.15 are affected.

Also, the title is still German :)
Information zur bereits von Google geschlossenen Sicherheitlücke im Exposure Notification Framework

**Comment by Ein-Tim** [comment]
I'm on the German title in the English FAQ. PR follows ASAP

**Comment by vaubaehn** [comment]
Another suggestion: Maybe it could also be added to the text:
"There are no known reports so far, that system apps of manufacturers actually gathered privacy disclosing ENF data."
As to my best knowledge, it could have been abused, but I did not read anything that it was done...

**Comment by vaubaehn** [comment]
There is another mistake:

> thus reading ENF data that is also provided by the Corona-Warn-App (CWA).

No privacy disclosing data from CWA appear in the system logs (was provided by CWA). It was all from Google's ENS logging.

**Comment by vaubaehn** [comment]
Just FYI: the relevant data looked like this, for example (I replaced original data with random values):

```logcat
04-22 21:07:47.477  3577 23655 I ExposureNotification: getCurrentRollingProximityId: generated a new RollingProximityId=A1B2C3D4E5F6G7H8I9ABABABABABABFF [CONTEXT service_id=236 ]
...
04-22 21:07:50.601  3577 23655 I ExposureNotification: Start advertising with packet (AdvertiseData [mServiceUuids=[0000fd6f-0000-1000-8000-00aa09bb0acc], mManufacturerSpecificData={}, mServiceData={0000fd6f-0000-1000-8000-00aa09bb0acc=[-11, 22, -33, 44, 55, 66, -77, -88, -99, 100, -111, 112, 113, 114, 115, 116, -117, 118, 119, 120]}, mIncludeTxPowerLevel=false, mIncludeDeviceName=false]) mode: ADVERTISE_MODE_BALANCED tx power level ADVERTISE_TX_POWER_LOW [CONTEXT service_id=236 ]
```

**Comment by vaubaehn** [comment]
Actually, I think one of the devs should have a look over the texts again.
Pinging @mlenkeit and @thomasaugsten here in the first place.

**Comment by thomasaugsten** [comment]
@vaubaehn 
You are correct the date logged by the Google ENF are not provided from or to the CWA. This is ENF data only
Regarding the apps this is correct only system apps pre installed by the manufacture but some manufacture also pre install Facebook this makes it difficult to say the is typical system app from the manufacture.

**Comment by vaubaehn** [comment]
@thomasaugsten thanks for your assessment and support here!

**Pull request merged**
