### PR TITLE
Cypress test for correct FAQ link attributes

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR implements the enhancement request https://github.com/corona-warn-app/cwa-website/issues/3158 "Add Cypress test for FAQ link conventions"

It tests that the following conventions are abided by:

- All internal and external links on the FAQ pages should use the HTML hyperlink attribute `target='_blank'` to open in a new frame. This provides a consistent user experience and works around an issue with the browser back arrow button in the FAQ Glossary.
- External links should use the HTML hyperlink attribute `rel='noopener noreferrer'` to avoid a cross-domain security issue in older browsers when the link also contains `target='_blank'`.
- Internal links should **not** contain the attribute `rel='noopener noreferrer'`. There is no security issue for internal links.

## Test log

The test successfully identifies issues in the production environment. These issues should be resolved by PR https://github.com/corona-warn-app/cwa-website/pull/3157.

```
$ npx cypress run -s cypress/integration/faq_link_attr.js -c baseUrl=https://coronawarn.app


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.7.0                                                                          │
  │ Browser:        Electron 100 (headless)                                                        │
  │ Node Version:   v16.18.0 (C:\Program Files\nodejs\node.exe)                                    │
  │ Specs:          1 found (faq_link_attr.js)                                                     │
  │ Searched:       cypress\integration\faq_link_attr.js                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  faq_link_attr.js                                                                (1 of 1)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating


  Check attributes of FAQ links
    Check links are using _blank to open in new frame
      √ Test links for _blank presence (75219ms)
    Check link cross-origin security for links with _blank
      1) Test FAQ external links for rel presence
      √ Test FAQ internal links for rel absence (65894ms)


  2 passing (3m)
  1 failing

  1) Check attributes of FAQ links
       Check link cross-origin security for links with _blank
         Test FAQ external links for rel presence:
     Error: tnAssertionError: https://www.bundesregierung.de/breg-de/themen/coronavirus/infektionsschutzgesetz-2068856 in /en/faq/results/: expected '<a>' to have attribute 'rel'nAssertionError: https://www.bundesgesundheitsministerium.de/coronavirus.html#c23063 in /en/faq/results/: expected '<a>' to have attribute 'rel'nAssertionError: https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187 in /en/faq/results/: expected '<a>' to have attribute 'rel'nAssertionError: https://www.bundesregierung.de/breg-de/themen/coronavirus/infektionsschutzgesetz-2068856 in /de/faq/results/: expected '<a>' to have attribute 'rel'nAssertionError: https://www.bundesgesundheitsministerium.de/coronavirus.html#c23063 in /de/faq/results/: expected '<a>' to have attribute 'rel'nAssertionError: https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187 in /de/faq/results/: expected '<a>' to have attribute 'rel'
      at Context.eval (https://coronawarn.app/__cypress/tests?p=cypress\support\index.js:186:13)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     2 minutes, 33 seconds                                                            │
  │ Spec Ran:     faq_link_attr.js                                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  C:\Users\mikem\github\cwa-website\cypress\screenshots\faq_link_attr.js\Check att     (1280x720)
     ributes of FAQ links -- Check link cross-origin security for links with _blank -
     - Test FAQ external links for rel presence (failed).png


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ×  faq_link_attr.js                         02:33        3        2        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ×  1 of 1 failed (100%)                     02:33        3        2        1        -        -

```

---
Internal Tracking ID: [EXPOSUREAPP-14213](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14213)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
- Due to merge of https://github.com/corona-warn-app/cwa-website/pull/3157 which corrected some links, this Cypress test is now successful

**Comment by dsarkar** [comment]
```
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        9.6.1                                                                          │
  │ Browser:        Electron 94 (headless)                                                         │
  │ Node Version:   v16.14.0 (/usr/local/bin/node)                                                 │
  │ Specs:          1 found (faq_link_attr.js)                                                     │
  │ Searched:       cypress/integration/faq_link_attr.js                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  faq_link_attr.js                                                                (1 of 1)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating


  Check attributes of FAQ links
    Check links are using _blank to open in new frame
      ✓ Test links for _blank presence (20164ms)
    Check link cross-origin security for links with _blank
      ✓ Test FAQ external links for rel presence (7884ms)
      ✓ Test FAQ internal links for rel absence (16895ms)


  3 passing (47s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      3                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     46 seconds                                                                       │
  │ Spec Ran:     faq_link_attr.js                                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  faq_link_attr.js                         00:46        3        3        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:46        3        3        -        -        -  
```

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Beautiful! Thanks for the suggestion and PR, enjoy your weekend!

**Comment by MikeMcC399** [comment]
@dsarkar 

Thanks! Likewise, wishing a you a nice weekend!

**Pull request merged**
