### PR TITLE
Replaces node-sass with sass

### LINKED ISSUE #2412: Deprecation of node-sass
## Where to find the issue

https://github.com/corona-warn-app/cwa-website/blob/master/package.json
https://github.com/corona-warn-app/cwa-website/blob/master/gulpfile.js 

## Describe the issue

According to https://www.npmjs.com/package/node-sass "Node Sass" used by cwa-website is deprecated:

"Warning: LibSass and Node Sass are deprecated. While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto [Dart Sass](https://sass-lang.com/dart-sass)."

## Suggested change

Migrate from [node sass](https://www.npmjs.com/package/node-sass) to [Dart Sass](https://sass-lang.com/dart-sass) see https://sass-lang.com/blog/libsass-is-deprecated which says:

"If you’re a user of Node Sass, migrating to Dart Sass is straightforward: just replace node-sass in your package.json file with sass."

however the change is not quite so simple. To remediate 
`Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.`
`More info and automated migrator: https://sass-lang.com/d/slash-div`
it is necessary to run the migrator.

1. `npm uninstall node-sass`
2. `npm install sass@latest`
3. Replace `node-sass` by `sass` in `gulpfile.js`
4. `npm install -g sass-migrator`
5. `sass-migrator division **/*.scss`

---
Internal Tracking ID: [EXPOSUREAPP-14243](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14243)

### PR DESCRIPTION
**Pull request by brianebeling**
Please let me know if you find any mistakes or something not working.

I'm not entirely sure myself, if I replaced it correctly

Fixes #2412

---
Internal Tracking ID: [EXPOSUREAPP-14243](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14243)

### CODE REVIEW

**Comment by brianebeling** [comment]
I used an older sass version, we could probably use 1.55.0

**Comment by MikeMcC399** [comment]
@brianebeling 

Could you share what issue you are trying to solve with this PR or what improvement you expect?

**Comment by MikeMcC399** [comment]
- This PR seems to implement the suggestion from issue https://github.com/corona-warn-app/cwa-website/issues/2412, which was previously rejected.

**Comment by MikeMcC399** [comment]
@brianebeling 

Since this PR is still in Draft state, I don't want to comment in detail, but I suggest that you look at the comments in https://github.com/corona-warn-app/cwa-website/issues/2412 regarding resolving the deprecation warnings which appear when running `npm run build`.

**Comment by brianebeling** [comment]
Hey @MikeMcC399, thanks for the additional info. I will check it out and should have been more precise in the PR.

We want to replace node-sass with sass, because node-sass has been deprecated for a while. When we upgrade to node 18 (LTS), node-sass won't work any longer. But upgrading to node 18 is worthwhile because of the security upgrades, and hopefully it will also improve compiling on M1 Chips or other ARM architectures in the future. 

With sass version 1.15.* there are even more deprecation warnings. I'm currently working on resolving them.

**Comment by MikeMcC399** [comment]
@brianebeling 

Thanks for explaining the background. That sounds good.

I would suggest that you do `npm install sass@latest` to get the package.json up to "version": "1.55.0" which is already showing in package-lock.json.

**Comment by brianebeling** [comment]
@Ein-Tim Hey Tim, thanks for testing! Feel free to do that now.

I migrated with the tool suggested by @MikeMcC399 (thanks!) using the division migrator. We could potentially further improve it using the modules migrator, but that broke the css completely and would be a lot of effort that won't pay off.

Let me know what you think, in the current state the css seems to be working fine and we removed the dependency on node-sass.

**Comment by MikeMcC399** [comment]
@brianebeling 

I think you can take this PR out of draft state if you want it reviewed. (It seems to be fine in any case.)

**Review by mtb77 — APPROVED** [review]

**Review by dsarkar — APPROVED** [review]

**Comment by Ein-Tim** [comment]
I'm currently testing this PR on my M1 MacBook. Please stand by, feedback will be provided in the next 15 min.

**Review by Ein-Tim — APPROVED** [review]
No problems detected on my M1 MacBook Air. I did not test the website for functionality but only checked if it still builds.

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Thanks for testing and your feedback!

**Comment by dsarkar** [comment]
@Ein-Tim So, you have no problem with the build. Are you using Rosetta, i.e. are you running in Intel emulation mode? See for example https://stackoverflow.com/questions/64899827/how-to-install-nodejs-natively-on-apple-silicon-m1/64902152#64902152

**Comment by Ein-Tim** [comment]
@dsarkar I have not enabled Rosetta for the native Terminal app I'm using on my Mac. See also the screenshot below.

Other environment details:
- MacBook Air M1 (late 2020)
- macOS Ventura 13.0

Bildschirm­foto 2022-10-27 um 15 44 27

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for your feedback.  And in the native terminal app you run the build, correct?

**Comment by Ein-Tim** [comment]
@dsarkar That's affirmative!

**Pull request merged**
