### PR TITLE
Android clear data function effects on Random IDs (closes #1067)

### LINKED ISSUE #1067: FAQ: Effect of clear data on random ID storage
## Where to find the issue

**Are the exposure logs/random IDs removed from my phone when I uninstall the app?**
https://www.coronawarn.app/en/faq/#delete_random_ids

**Werden die gesammelten Zufalls-IDs beim Deinstallieren der App entfernt?**
https://www.coronawarn.app/de/faq/#delete_random_ids

## Describe the issue

The FAQs misleadingly say:
"We recommend that before you re-install the app, you try clearing the app data first as this will not delete the random IDs:"

"Wir empfehlen daher, vor der Neu-installation zunächst die Daten in der App zurückzusetzen, da hierbei die gesammelten Zufalls-IDs nicht gelöscht werden:"

The FAQs mean resetting the app, not clearing the app data using the operating system UI.

The side-effect of using Android's "Clear data" storage maintenance function on the App listed as "Corona-Warn" is not explicitly mentioned. "Clear data" acts like uninstalling the app as far as the Google Exposure Notifications System is concerned. Keys will be deleted.

## Background

In an old post https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-719786581 from on Oct 30, 2020 @thomasaugsten wrote:

> I doubled check and it looks Google is now registering the data deleting and turns off the exposure notification framework the leads to a key wiping. We will update our FAQ

From the context of the issue https://github.com/corona-warn-app/cwa-app-android/issues/642 it seems that the FAQ being referred to was https://www.coronawarn.app/en/faq/#delete_random_ids.

The intention of updating the FAQ stated by @thomasaugsten was never actioned.

The general issue of the side-effects of deleting the data from the CWA on Android has been brought up in https://github.com/corona-warn-app/cwa-app-android/issues/2795.

### EN
[Are the exposure logs/random IDs removed from my phone when I uninstall the app?](https://www.coronawarn.app/en/faq/#delete_random_ids)

Reword:

"On Android devices, the current implementation deletes the ['database and keys' from the device](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#methods) when uninstalling the app. Hence, you should expect that the collected random IDs are deleted when the app is uninstalled. **Random IDs are also deleted if the Android App storage maintenance "Clear data" function is used on the App "Corona-Warn".**"

...

"We recommend that before you re-install the app, you try **resetting the app** first as this will not delete the random IDs:"

### DE
[Werden die gesammelten Zufalls-IDs beim Deinstallieren der App entfernt?](https://www.coronawarn.app/de/faq/#delete_random_ids)

Reword:

"Auf Android-Geräten werden in der derzeitigen Implementierung beim Deinstallieren 'Datenbank und Schlüssel' vom Gerät gelöscht. Sie sollten daher davon ausgehen, dass mit Deinstallation der App auch die Begegnungsaufzeichnungen verloren gehen. **Die Begegnungsaufzeichnungen gehen ebenso verloren, sollte die Android App-Speicherplatzverwaltungsfunktion "Daten löschen" auf die App "Corona-Warn" angewandt werden.**

...

"Wir empfehlen daher, vor der Neu-installation zunächst **die App zurückzusetzen**, da hierbei die gesammelten Zufalls-IDs nicht gelöscht werden:"

---

I will put the above into a draft PR later today.

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR implement text changes proposed in "FAQ: Effect of clear data on random ID storage" https://github.com/corona-warn-app/cwa-website/issues/1067 to FAQ articles:

(EN) Are the exposure logs/random IDs removed from my phone when I uninstall the app?
https://www.coronawarn.app/en/faq/#delete_random_ids

(DE) Werden die gesammelten Zufalls-IDs beim Deinstallieren der App entfernt?
https://www.coronawarn.app/de/faq/#delete_random_ids

## Changes made

- The FAQs are extended to describe that Random IDs are lost if the Android operating system storage "Clear data" function is applied to the "Corona-Warn" app. This could for example be through
1. Settings > Apps > "Corona-Warn"
2. Tap "Storage"
3. Tap "Clear data"
depending on Android version and implementation.
- The paragraph referring to "reset app" is made clearer that it does not apply to "clear data" from the operating system.

## English (EN)

Are the exposure logs/random IDs removed from my phone when I uninstall the app?
https://www.coronawarn.app/en/faq/#delete_random_ids

delete_random_ids EN

## German (DE)

Werden die gesammelten Zufalls-IDs beim Deinstallieren der App entfernt?
https://www.coronawarn.app/de/faq/#delete_random_ids

delete_random_ids DE

## References

corona-warn-app/cwa-app-android#642 (comment) from on Oct 30, 2020 @thomasaugsten wrote:

> I doubled check and it looks Google is now registering the data deleting and turns off the exposure notification framework the leads to a key wiping. We will update our FAQ

Perhaps @thomasaugsten could review this PR for technical accuracy?

---
Internal Tracking ID: [EXPOSUREAPP-5956](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5956)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
I also corrected three typos in the sentence:
"Da sich dieses Verhalten bei der App-Deinstallation auch ohne Änderungen an der Corona-Warn-App jederzeit ändern kann, sollten **Sie** die App wirklich nur in Ausnahmefällen deinstallieren oder wenn die technische Hotline oder Entwickler auf GitHub **Sie** explizit darum bitten."

I changed "sie" to "Sie" and added a full-stop at the end of the sentence.

**Review by dsarkar — APPROVED** [review]

**Comment by vaubaehn** [comment]
@MikeMcC399 @dsarkar

Just one point:
In the German text in the sixth paragraph, you refer to "Zufalls-IDs" whereas before it was always called "Begegnungsaufzeichnungen". "Zufalls-IDs" is introducing a new terminus in this section, what could lead to confusion. I'd suggest to keep it consistent. Personally, I like "Zufalls-IDs" more, as it better describes the data stored in ENS.

Would it make sense to add information at the end of the section, that installing another ENS-based contact tracing app (like Immuni and alike) before uninstalling CWA or deleting its data, prevents 'Random IDs" to be erased? So that this method could be used as a last resort in case of non-functional CWA without losing RPIs/TEKs?

**Comment by MikeMcC399** [comment]
@vaubaehn 

> In the German text in the sixth paragraph, you refer to "Zufalls-IDs" whereas before it was always called "Begegnungsaufzeichnungen". "Zufalls-IDs" is introducing a new terminus in this section, what could lead to confusion. I'd suggest to keep it consistent. Personally, I like "Zufalls-IDs" more, as it better describes the data stored in ENS.

This PR does not change the use of the terms "Begegnungsaufzeichnungen" and "Zufalls-IDs". The use is consistent with the definition in the app under Startseite > Dreipunkte-Symbol > Überblick 

Wichtige Begriffe
 

> Would it make sense to add information at the end of the section, that installing (and activating) another ENS-based contact tracing app (like Immuni and alike) before uninstalling CWA or deleting its data, prevents 'Random IDs' to be erased? So that this method could be used as a last resort in case of non-functional CWA without losing RPIs/TEKs?

The Open Source Team decided in #320 to remove this information from the FAQ because it was not documented by Google.

So, in summary I don't plan further changes and I would be happy for this PR to be merged.

**Comment by vaubaehn** [comment]
@MikeMcC399 
I think I couldn't explain well enough what I mean. If it's about my bad expressions in English language, I beg your pardon in case I'm excessively straining your patience.
When we are talking about Rolling Proximity Identifiers (RPIs), in German language CWA app and CWA website refer to:
- Begegnungsaufzeichnungen
- Begegnungs-Aufzeichnung
- Zufalls-IDs
- rollierende Näherungs-IDs
- if we refer to the link 'Datenbank und Schlüssel vom Gerät gelöscht' to Google's documentation within the section of this PR: Datenbank

... and probably more, which I couldn't spot within a quick research.
Moreover, Google names them inside the ENS UI: Zufallserkennungen.

What I was proposing to change, was to replace the 'Zufalls-IDs' in the sixth paragraph with 'Begegnungsaufzeichnungen' to have the same wording throughout the whole section. I felt irritated by the change of naming RPIs from 'Begegnungsaufzeichnungen' to 'Zufalls-IDs', and needed to think (again) if both words are meaning the same thing. I guess that a less technically advanced user might have even more problems to understand, what is talked about. Yes, you're right, there is a definition inside the CWA app, but I doubt that users, who want to understand if 'Zufalls-IDs' and 'Begegnungsaufzeichnungen' means the same, spontanously knew where to look it up (and do so).
So, changing the last 'Zufalls-IDs' to 'Begegnungsaufzeichnungen' (or all 'Begegnungsaufzeichnungen' in this section to 'Zufalls-IDs') would have made a difference for me with regard to readability, comprehensibility and style.

When I was reading the German section once again before writing this comment, I found that I overlooked the title of the German section before: 'Werden die gesammelten Zufalls-IDs beim Deinstallieren der App entfernt?' Following the title, the subject in this section handled 'Begegnungsaufzeichnungen' except inside the sixth paragraph. Together with the title, it's more clear, that 'Zufalls-IDs' also means 'Begegnungsaufzeichnungen'. However, I think the style can still be improved with minimum effort:
If we look to the English section, the title is 'Are the exposure logs/random IDs removed from my phone when I uninstall the app?'
Both synonyms are introduced within the title. Within the following text, both terms are used interchangingly. For me, in the English text it's much more clear, that both terms refer to the same object.

So, my (pendatic) final proposal to improve both English and German texts is:
Change English title to: 'Are the exposure logs (random IDs) removed from my phone when I uninstall the app?' - because the brackets give a better signal that 'exposure logs' and 'random IDs' are the same. The slash '/' often (but not always) refers to _different_ objects that have the same importance.
Change the German title to: 'Werden die gesammelten Begenungsaufzeichnungen (Zufalls-IDs) beim Deinstallieren der App entfernt'? in line with the English title. I think, the following text is more clear then, and there is no need to replace any 'Begenungsaufzeichnungen' or 'Zufalls-IDs'.

I'm aware that you're not the creator of the original texts and the intentenion of this PR was a clarification in a different subject - but why not using the opportunity to improve style and comprehensibility?

---

>> Would it make sense to add information at the end of the section, that installing (and activating) another ENS-based contact tracing app (like Immuni and alike) before uninstalling CWA or deleting its data, prevents 'Random IDs' to be erased? So that this method could be used as a last resort in case of non-functional CWA without losing RPIs/TEKs?

> The Open Source Team decided in #320 to remove this information from the FAQ because it was not documented by Google.

Yes, you are right. But if we relied on the (sketchy) documentation by Google always, things may be improved with an extraordinary delay, if ever. I'm trusting @kbobrowski 's findings here https://github.com/corona-warn-app/cwa-app-android/issues/1084#issuecomment-719642452 100%, and if I remember correctly, there were additional user reports in this context that confirmed this fact. So a possible addition at the end of this section could be:
German
Nach einzelnen Berichten von wenigen Nutzern werden die Begegnungsaufzeichnungen weder beim Löschen der Daten der Corona-Warn-App über die Systemeinstellungen von Android noch beim Deinstallieren der Corona-Warn-App gelöscht, wenn noch eine zweite App zur Kontaktnachverfolgung aus einem anderen Land auf dem Gerät installiert und aktiviert wurde, die auch auf dem Exposure Notification Framework von Google basiert. **Hierfür können wir allerdings weder eine Bestätigung noch eine Gewährleistung geben.**
Sollten Sie dennoch die Cororna-Warn-App-Daten löschen oder die App deinstallieren müssen, wollen aber die Begegnungsaufzeichnungen nicht verlieren, könnten Sie dies über die Installation einer zweiten App (auf eigenes Risiko) versuchen. Eine Liste dafür geeigneter Kontaktverfolgungsapps anderer Länder finden Sie hier: https://developers.google.com/android/exposure-notifications/apps

English
According to individual reports from a few users, the exposure logs are not deleted when the data from the Corona-Warn-App is deleted via the Android system settings or when the Corona-Warn-App is uninstalled, if a second app for contact tracing from another country is on the device installed and activated, which is also based on the Exposure Notification Framework from Google. **However, we can neither give a confirmation nor a guarantee for this.**
Should you still have to delete the Corona-Warn-App data or have to uninstall the app, but you do not want to lose the random IDs, you can try this by installing a second app (at your own risk). A list of suitable contact tracing apps from other countries can be found here: https://developers.google.com/android/exposure-notifications/apps

However, I respect the fact, that this addition is not in the scope of your PR and could be seperated. On the other hand, your PR is a nice opportunity to add these findings. Feel free to use/adapt above text, in case you agree.

---

> So, in summary I don't plan further changes and I would be happy for this PR to be merged.

When I'm submitting manuscripts to journals for review (or change requests on GH), I also don't plan any further changes to my work 😆 In best case there is a fast agreement of necessary (or possible) changes between submitter, referee and editor (on GH: product owner, here represented by @dsarkar ). So let's wait in modest patience for @dsarkar 's remarks.

**Comment by MikeMcC399** [comment]
@vaubaehn 
I would defer to @heinezen on this topic since he is revising a lot of FAQ articles at this time and I am not the original author of the article.

I was attempting to make small changes to the article without questioning the base assumptions. I have marked up changes in the screen shots.

I think it would be preferable to sign off first on the small changes and take your points into consideration as a separate issue.

**Comment by vaubaehn** [comment]
@MikeMcC399 
Let's do like you suggested.

**Comment by vaubaehn** [comment]
Hi @thomasaugsten , when you find time would be nice if you could approve @MikeMcC399 's PR for technical correctness. Please ignore my comments in this place, they are not associated with the technical content.
Thanks in advance!

**Comment by heinezen** [comment]
@vaubaehn The translation of "RPI" used by us should always be "Zufalls-IDs", but has not yet been changed in all FAQ entries. However, we can consider changing the heading to make it more clear what is meant by that. I would do this in my PR for #971 .

> Should you still have to delete the Corona-Warn-App data or have to uninstall the app, but you do not want to lose the random IDs, you can try this by installing a second app (at your own risk).

I'm not sure if we can just recommend a random app. Although it would work as a workaround of course.

**Comment by dsarkar** [comment]
image

**Comment by dsarkar** [comment]
image

**Comment by dsarkar** [comment]
@MikeMcC399 @vaubaehn @heinezen Thanks!

**Pull request merged**
