### PR TITLE
Reintroducing MultiQR

### PR DESCRIPTION
**Pull request by svengabr**
- draft
- some text changes will be made

screencapture-localhost-8000-de-event-qr-code-guide-2021-09-07-08_47_19
screencapture-localhost-8000-de-eventregistration-2021-09-07-08_47_48

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Replaced by #2105?

**Comment by dsarkar** [comment]
@Ein-Tim indeed.

**Comment by Ein-Tim** [comment]
Can the branch `multiqr` be deleted?

**Comment by dsarkar** [comment]
@Ein-Tim We are doing some clean up here ;-)

**Comment by Ein-Tim** [comment]
@dsarkar 

Yes, sorry for the comments, I was selecting the branch from #2261 locally and saw that there were many branches which were already merged, so I commented. 

Hope you have a nice day!

**Comment by dsarkar** [comment]
@Ein-Tim No sorries, no worries... Same to you, enjoy your day!

**Pull request closed without merging**
