### PR TITLE
Miscellaneous FAQ typos

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR corrects some minor typos in the English and German FAQs.

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.

**Comment by MikeMcC399** [comment]
@dsarkar 
Was there some reason for not merging this PR after you approved it?

**Comment by dsarkar** [comment]
@MikeMcC399 The reason that I hesitated is that we are migrating the content to the new FAQ. But I will merge now, and we keep track of all changes since a couple of days. Thanks again for all the effort!

**Comment by MikeMcC399** [comment]
@dsarkar 
> The reason that I hesitated is that we are migrating the content to the new FAQ. But I will merge now, and we keep track of all changes since a couple of days. Thanks again for all the effort!

It's good to know about the migration plans. I hope this work is semi-automated otherwise it will probably be quite error-prone!

I will hold back on any other PRs in that case until your migration is completed.

**Pull request merged**
