### PR TITLE
Harmonize term "Contact Journal" / "Kontakt-Tagebuch" in Blog, FAQ, Glossary and Event Registration

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/2315 "Inconsistent use of terms for Contact Journal"

The app uses the terms:
- Journal / Contact Journal (EN)
- Tagebuch / Kontakt-Tagebuch (DE)

For reference, view the screenshots on:
- https://www.coronawarn.app/en/screenshots/#ios_journal
- https://www.coronawarn.app/en/screenshots/#android_journal
- https://www.coronawarn.app/de/screenshots/#ios_journal
- https://www.coronawarn.app/de/screenshots/#android_journal

The Blogs, FAQ, Glossary and the Event Registration form have been aligned to use only the terms used in the app.
Text relating to screenshot labelling before the current 2.15 version has not been changed.

The terms  "Contact Journal" (EN) and "Kontakt-Tagebuch" (DE) replace other equivalent terms:

- Contact diary (used in English texts)
- Kontakttagebuch (alternative spelling, without hyphen, used in German texts)

Although the term "Contact diary" is used internally in the source code, even the first version with this functionality (CWA 1.10.1) was released displaying the names as "Contact Journal" and "Kontakt-Tagebuch" on the main screen.

### CODE REVIEW

**Review by Ein-Tim — APPROVED** [review]
LGTM (reviewed all changes to German texts)! Maybe the commits can be squashed? But that's just a minor detail. 🙂

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thank you for checking.

The commits are separate, and not squashed, so that if there is anything wrong they can be replaced or changed individually.

The tacit practice in this repository is to squash-merge PRs, which means that the individual commits are not carried into the master branch. Instead they are replaced with a squashed commit, created at the time of the merge.

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks!

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks, I didn't ever notice that we uses squash & merge! 

Learned something new today: ☑️

Have a nice evening everyone 😀

**Comment by MikeMcC399** [comment]
@dsarkar 

Unfortunately this PR broke the Cypress test suite 🙁 , so I have submitted PR #2318 to change one word in the Cypress strings.

**Pull request merged**
