### PR TITLE
Faq Personal data update

### PR DESCRIPTION
**Pull request by ahodzic2**
Update related to issue #1729. Replaced list of data inputs with link to privacy policy.

- https://www.coronawarn.app/en/faq/#personal_data

- https://www.coronawarn.app/de/faq/#personal_data

---
Internal Tracking ID: [EXPOSUREAPP-12410](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12410)

### CODE REVIEW

**Review by MikeMcC399 — CHANGES_REQUESTED** [review]
I suggest to convert the hyperlinks to relative i.e. remove the `https://www.coronawarn.app` and remove the `rel='noopener noreferrer'` which is not necessary for internal links.

Check out https://www.coronawarn.app/en/faq/#have_to_use for an example of another FAQ article which refers to the Privacy notice using a relative link.

**Comment by ahodzic2** [comment]
> I suggest to convert the hyperlinks to relative i.e. remove the `https://www.coronawarn.app` and remove the `rel='noopener noreferrer'` which is not necessary for internal links.
> 
> Check out https://www.coronawarn.app/en/faq/#have_to_use for an example of another FAQ article which refers to the Privacy notice using a relative link.

I agree this is a good idea. Let me make those changes on my end and I can push another round of commits.

**Comment by ahodzic2** [comment]
Apologies if I did something out of order but the latest commit captures @MikeMcC399 's suggestion and it is ready for review.

**Comment by MikeMcC399** [comment]
@ahodzic2 

- The end result of your changes now look fine! 👍🏻 

Here are just some additional points to consider:

- In the [Contributing Guide](https://github.com/corona-warn-app/cwa-website/blob/master/CONTRIBUTING.md#pull-request-checklist) we are asked to squash commits after making corrections.

- Your branch is out of date with the base ([master](https://github.com/corona-warn-app/cwa-website/tree/master)) branch.

- You would need to update your fork's copy of the `master` branch, rebase on this, squash your commits, then force push to your `FAQ-Data-Update` branch on GitHub.

- Note that @dsarkar wrote in https://github.com/corona-warn-app/cwa-website/issues/1729#issuecomment-1076223553 "we would appreciate a PR after going live with the new FAQ website (today)." however the PR for the FAQ (which is https://github.com/corona-warn-app/cwa-website/pull/2434) has been delayed due to technical issues and it has not yet been merged.

---
Some optional points:

- I would suggest editing the title from "FAQ data update" to "FAQ personal data update" as the original title is a little vague.

- It is helpful for checking to include the URLs, which will be changed, in the original post i.e.
    - https://www.coronawarn.app/en/faq/#personal_data
    - https://www.coronawarn.app/de/faq/#personal_data

**Comment by ahodzic2** [comment]
> @ahodzic2
> 
> * The end result of your changes now look fine! 👍🏻
> 
> Here are just some additional points to consider:
> 
> * In the [Contributing Guide](https://github.com/corona-warn-app/cwa-website/blob/master/CONTRIBUTING.md#pull-request-checklist) we are asked to squash commits after making corrections.
> * Your branch is out of date with the base ([master](https://github.com/corona-warn-app/cwa-website/tree/master)) branch.
> * You would need to update your fork's copy of the `master` branch, rebase on this, squash your commits, then force push to your `FAQ-Data-Update` branch on GitHub.
> * Note that @dsarkar wrote in [`personal_data` FAQ entry is outdated #1729 (comment)](https://github.com/corona-warn-app/cwa-website/issues/1729#issuecomment-1076223553) "we would appreciate a PR after going live with the new FAQ website (today)." however the PR for the FAQ (which is [FAQ page rework #2434](https://github.com/corona-warn-app/cwa-website/pull/2434)) has been delayed due to technical issues and it has not yet been merged.
> 
> Some optional points:
> 
> * I would suggest editing the title from "FAQ data update" to "FAQ personal data update" as the original title is a little vague.
> * It is helpful for checking to include the URLs, which will be changed, in the original post i.e.
>   
>   * https://www.coronawarn.app/en/faq/#personal_data
>   * https://www.coronawarn.app/de/faq/#personal_data

Thank you @MikeMcC399 for the feedback! I reviewed those contributing guide previously but I think I may have confused myself when actually creating the PR and pushing commits. I don't think I am able to squash the commits at this point as there is a merge commit as I rebased before making the updates. Additionally, the rebase option is no longer available at this point as it says there are merge conflicts.

I did a fetch with my forked version of master and that had nothing else to pull in. Any idea how I can proceed from here? I am using Github Desktop.

Apologies for the beginner questions. I very much appreciate your guidance and tips for how to improve moving forward :)

**Comment by MikeMcC399** [comment]
@ahodzic2
> I don't think I am able to squash the commits at this point as there is a merge commit as I rebased before making the updates. Additionally, the rebase option is no longer available at this point as it says there are merge conflicts.
>
>I did a fetch with my forked version of master and that had nothing else to pull in. Any idea how I can proceed from here? I am using Github Desktop.

GitHub Desktop is limited in functionality. To rebase you need to use the CLI version of `git`.

There are a couple of ways to tackle this:

1. `git rebase master FAQ-Data-Update-work` will throw a merge conflict, however if you use an editor you can resolve the conflict and continue the rebase

2. Another way is to use `git reset` to move the `HEAD` back to before your first commit. You can then recommit your changes.

If that is unclear or you need some more detailed help, then please ask.

**Comment by MikeMcC399** [comment]
@ahodzic2 

I just looked at the effect of the new FAQ site which was merged this morning and it introduces some major changes into the FAQ source files which cause conflicts in this PR if you try to merge them. That was the reason that @dsarkar advised you to wait before submitting a PR.

Let me look at how you might sort this out. I think it might be possible, but it is more an academic exercise. The simplest solution would be to close this PR and open a new one based on the updated `master` branch from this morning.

One thing you could do in any case is to update your master branch locally and in your fork:

```
git switch master
git fetch upstream
git merge upstream/master
git push origin
```

assuming that you are using standard naming for "upstream" and "origin".

**Comment by MikeMcC399** [comment]
@ahodzic2 
I think it is simplest to close this PR and submit a new PR based on the new master. Otherwise you will need to make a lot of manual corrections to resolve the conflicts. You can't simply cherry-pick your changes unfortunately.

**Comment by ahodzic2** [comment]
> @ahodzic2 I think it is simplest to close this PR and submit a new PR based on the new master. Otherwise you will need to make a lot of manual corrections to resolve the conflicts. You can't simply cherry-pick your changes unfortunately.

Thank you so much for the details @MikeMcC399! I'll look to close this PR, make sure I have the most up to date master and then make the changes under a new PR. I noticed that the contributing guide suggests keeping commits as independent as possible, so do you recommend two commits (1 for faq and one for fag_de) or do you think these can go under the same commit?

**Comment by MikeMcC399** [comment]
@ahodzic2 

> do you recommend two commits (1 for faq and one for fag_de) or do you think these can go under the same commit?

One commit is fine. You can look at closed PRs to see how other contributors have done this in the past. In general, if an article is being corrected at the same time in English and German it will be one commit. Sometimes if a new article is being written and it is first available in one language, you might find one commit for one language followed by a later commit for the other language.

**Pull request closed without merging**
