### PR TITLE
Fix PR 1736: Complete step-by-step guide and specify date

### PR DESCRIPTION
**Pull request by larswmh**
In [this pull request](https://github.com/corona-warn-app/cwa-website/pull/1736) I have added the FAQ entries eu_dcc_export and vac_cert_booster and have also adjusted the existing entry vac_cert_booster_cwa. In the step-by-step guide of eu_dcc_export, I missed out on a couple of steps that are now included with this pull request. I have also replaced the word "click" with "tap" as it is more fitting. In vac_cert_booster_cwa, I've previously said that in a future version users will receive a notification to consider a booster vaccination if necessary. This has now been more specified to version 2.10.

eu_dcc_export:
DE:
chrome_5Co2KrCElq

EN:
chrome_w3jDNtYBFl

vac_cert_booster_cwa
DE:
chrome_tBDHax7VII

EN:
chrome_8G4DJsNba9

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Regarding `eu_dcc_export`, the app links to this entry when it's unable to create a PDF because of the limitation that only German certificates can create a printout.
However, this FAQ entry (particularly the section "Limitation") isn't really helpfully for the user as it doesn't answer the question why it's not possible to create a PDF for the certificate. 

This should be improved IHMO.

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@Ein-Tim OK, there is a bit of more explanation in the blog. I suggest we can also add a link to the blog.

**Comment by dsarkar** [comment]
1. Add sentence with link to blog at the end to "Limitations"-section: 
  - See also the blog article **Mit Version 2.10 ist die Corona-Warn-App bereit, schnell über Auffrischungsimpfungen zu informieren**.

- Link to blog:
  - **DE** https://www.coronawarn.app/de/blog/2021-09-22-cwa-version-2-10/
  - **EN** https://www.coronawarn.app/en/blog/2021-09-22-cwa-version-2-10/

2. Add sentences with links to blogs at the end to "vac_cert_booster" FAQ article: 

  - Link 1 to blog:
    - **DE** https://www.coronawarn.app/de/blog/2021-09-08-cwa-version-2-9/
    - **EN** https://www.coronawarn.app/en/blog/2021-09-08-cwa-version-2-9/
  - Link 2 to blog:
    - **DE** https://www.coronawarn.app/de/blog/2021-09-22-cwa-version-2-10/
    - **EN** https://www.coronawarn.app/en/blog/2021-09-22-cwa-version-2-10/

**Comment by MikeMcC399** [comment]
There is a missing full stop at the end of the sentence
"This function is primarily used to create backup copies of the certificates for your personal purposes"
I can't comment in-line because this line wasn't changed by this PR.

**Comment by MikeMcC399** [comment]
Also in the German text, there is a missing full stop:
"Diese Funktion dient vorrangig der Erstellung von Sicherheitskopien der Zertifikate für Ihre persönlichen Zwecke"

**Comment by larswmh** [comment]
@MikeMcC399 full stops have been added at the end of the mentioned sentences, thanks!
@Ein-Tim blog articles are now mentioned the way @dsarkar commented it here. Mentioned blog article titles for /blog/2021-09-22-cwa-version-2-10/ may differ from the actual title in the future, since we don't know which exact title will be used yet. This will of course be changed once we know it

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@larswmh @Ein-Tim @MikeMcC399 Thanks.

**Pull request merged**
