### PR TITLE
Screenshots page update and remove space on FAQ's left menu (rebase)

### PR DESCRIPTION
**Pull request by brifemu**
In this update I had work on the next features:

**app.js**

- On jQuery tabs function, add anchor link to keep it on refresh

**screenshots.js**

- On option input now appears the version that the user is consulting
- Keep tab selected on refresh or change version clicking of version option
- Left menu switchable on change OS tab

**_box.scss**

- Created new class 'nav-link-left-menu' to remove space between options on left side menu in Screenshots and FAQ pages

**global.json**

- Remove option 'Version' for DE and EN, now it is not necessary
- Added tag 'Version' to every version

**page-faq.html**

- Added class 'nav-link-left-menu' to remove space between left side options menu

**page-screenshots.html**

- Added left side menu

### CODE REVIEW

**Comment by dsarkar** [comment]
Suggestion from @MikeMcC399 https://github.com/corona-warn-app/cwa-website/pull/1761#issuecomment-925646384:

Add dashes or points to each menu item. Alternatively a light (maybe grey) vertical line to the left:

image

**Comment by MikeMcC399** [comment]
@dsarkar 
Some of the titles are long and one of the titles "Check Certificates for Validity Before a Trip" takes up three lines in the menu on the left, so it is not so readable, even though a vertical line appears as the mouse is moved over the menu.

That was the reason for suggesting a marker character at the beginning of each section title.

Alternatively perhaps introduce a short title (used in the menu) and a long title (used in the actual screen shot display), so that the menu is more readable. The disadvantage would be extra maintenance for the screenshots where there are already 4 different variants (iOS / Android * English / German).

**Comment by MikeMcC399** [comment]
@brifemu 

Are you also able to solve https://github.com/corona-warn-app/cwa-website/issues/1402 "Switch screenshot language gives 404 error" if you are re-working this area?

**Comment by dsarkar** [comment]
@MikeMcC399 

- #1402 "Switch screenshot language gives 404 error" will be addressed separately.

**Comment by brifemu** [comment]
Added decoration for every menu item and scroll bar (only appears if it's necessary)

2fc18e7032c52904d6e7ffd824213f42

**Comment by brifemu** [comment]
Fixed left side menu. Now it scrolls on desktop and mobile view

**Comment by MikeMcC399** [comment]
@brifemu 
This seems to solve also issues
#882 and #1496
regarding scrolling the menu for the FAQ. 👍🏻

**Comment by Ein-Tim** [comment]
Thank you @brifemu!

Is it intended that the sidebar sometimes cuts off although there is enough space available?

See for example this screenshot: 
Bildschirmfoto 2021-09-23 um 19 08 16

**Comment by MikeMcC399** [comment]
@Ein-Tim 
There is something strange about your screenshot!
You have selected iOS Version 2.2 German yet the text in your screenshot is for Version 2.1.
The menu does not fit Version 2.2. The last entry for 2.2 is "Schnelltest" when I view it on my system.

I can't reproduce what you are seeing.

Perhaps you could check that you are working from `cuisines:brifemu-screenshots-update-rebase` with the last commit being https://github.com/corona-warn-app/cwa-website/pull/1762/commits/fd5a811084aa6e57bb1b03c522593f1c86ca6e10?

**Comment by Ein-Tim** [comment]
@MikeMcC399 Actually, what's shown first when the local build finishes and I open the screenshot page opens is what is shown in the screenshot above.

I can confirm that I build on https://github.com/corona-warn-app/cwa-website/commit/fd5a811084aa6e57bb1b03c522593f1c86ca6e10.

**Comment by Ein-Tim** [comment]
Now I get what's wrong here: The "Version xx" always stays as "Version 2.2", no matter which version I actually select. 

Here's a video:

https://user-images.githubusercontent.com/67682506/134564334-3defa0aa-0f95-4ebc-8f4a-118756726d7b.MOV

This should be fixed.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

So there are two problems:

1. Where you are trying to view the information for Version 2.10 the menu gets cut off at "Ungültige". It is not displaying the last word in the menu which is "Zertifikate" and you cannot scroll to this word.
2. The version displays "Version 2.2" whatever version you have just chosen. "Version 2.2" is the first entry in the list.

I am using Google Chrome Version 94.0.4606.54 (Official Build) (64-bit) on Windows 10.
What is your environment?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thank you for summarizing, these are exactly the errors I encounter on my MacBook Air 2020 (M1) with the latest version of macOS Big Sur (11.6) and the latest version of Safari (15.0).

**Comment by brifemu** [comment]
Fixed dropdown button bug keeping version selected on Safari replacing jQuery function to add attributes to the input

**Comment by Ein-Tim** [comment]
Thank you @brifemu!

I can confirm that the "Version 2.2" issue is fixed, however, the issue that the last menu point is cut off hasn't been fixed:

Bildschirmfoto 2021-09-24 um 21 02 13

**Comment by brifemu** [comment]
Hi @Ein-Tim 

The point is not cut off really, sidebar is now scrollable. Can you scroll it?

**Comment by Ein-Tim** [comment]
@brifemu 

Yes, I can, but shouldn't the menu only be scrollable if there is not enough space to show it directly?

**Comment by brifemu** [comment]
@Ein-Tim 

Now menu is scrollable if there is not enough space

**Comment by MikeMcC399** [comment]
It looks good to me on Google Chrome and Mozilla Firefox.

**Comment by Ein-Tim** [comment]
@brifemu 

The menu is still cut off here, but only under Safari, so I guess this is a Safari "exclusive" issue. 

It would be great to see a fix, but this is not merge blocking, so from my POV this could be merged as it is now.

**Comment by dsarkar** [comment]
@Ein-Tim @brifemu LGTM, also I cannot reproduce the issue "last menu item cut-off":

image

**Pull request closed without merging**
