### PR TITLE
Remove "other" from QR-Code generator

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR removes the option to choose "Other" in the QR-Code generator since there is no option for this in the app and thus the app shows an error/unlocalized string.

Related: https://github.com/corona-warn-app/cwa-app-ios/issues/2564

### CODE REVIEW

**Comment by dsarkar** [comment]
@Ein-Tim Thanks

anderes Event ==> Anderes Event

Anyway, I am wondering why the word Event is used instead of Veranstaltung

**Comment by dsarkar** [comment]
@Ein-Tim I confirm, Other must be removed, leads to error on CWA

**Comment by DerVogel2020** [comment]
> anderes Event ==> Anderes Event

This should be fixed for both apps and the website and all occurrances where like "private Feier" or "öffentliches Gebäude" see #2981.

> Anyway, I am wondering why the word Event is used instead of Veranstaltung

See also https://github.com/corona-warn-app/cwa-app-android/issues/2888#issuecomment-824115062

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@DerVogel2020 @Ein-Tim Merged, since urgent. I see, wording is aligned with CWA. Will do for the moment. Thanks.

**Comment by dsarkar** [comment]
@DerVogel2020 Right, I forgot you mentioned all that already.

**Comment by DerVogel2020** [comment]
@dsarkar just opened https://github.com/corona-warn-app/cwa-wishlist/issues/491 because this regards both apps and the website

**Pull request merged**
