### PR TITLE
Improve `2022-01-11-omikron` (Addresses #2308)

### LINKED ISSUE #2308: Plain links in yesterdays blog post
## Where to find the issue
- https://www.coronawarn.app/de/blog/2022-01-11-cwa-omikron/
- https://www.coronawarn.app/en/blog/2022-01-11-cwa-omikron/

## Describe the issue
At the very end of the blog post, it links to another blog post. This link is visible in plain text.

## Suggested change
Don't use plain text links.

## Additional information
I'll provide a PR for this.

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR improves the blog post [2022-01-11-omikron"](https://www.coronawarn.app/de/blog/2022-01-11-cwa-omikron/) by:
- adding  `&nbsp;` in `z.B.`?
- changing a plain text link at the end of the blog

---

**Closes #2308**

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@Ein-Tim 
This is a good improvement! In fact now that the last sentence has been changed, the paragraph break could be removed so that it flows together better.

"...Dafür informieren wir mit der jüngsten App-Version 2.15 die Nutzerinnen und Nutzer umfassend, wie sie sich verhalten sollten, wenn die App eine rote Kachel zeigt. Lesen Sie dazu den Blog-Artikel "[Was tun bei einer roten Kachel?](http://localhost:8000/de/blog/2021-12-15-cwa-red-tile-guidance)" für mehr Informationen."

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Thanks for the review, @Ein-Tim Do you remove the  paragraph break?

**Comment by Ein-Tim** [comment]
@dsarkar I will do this later today.

**Comment by dsarkar** [comment]
@Ein-Tim  FYI the paragraph break was removed and PR merged.

**Comment by Ein-Tim** [comment]
@dsarkar 

Thanks, however, only `index_de` was edited, not `index` too. Will you do this?

**Comment by dsarkar** [comment]
@Ein-Tim Ah, true... Could you fix that? Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar 

For sure! PR will follow in ca. 60 minutes.

**Comment by Ein-Tim** [comment]
PR #2316 created.

**Pull request merged**
