### PR TITLE
update screenshots

### PR DESCRIPTION
**Pull request by dsarkar**

### CODE REVIEW

**Review by Ein-Tim — CHANGES_REQUESTED** [review]
Something went wrong with the iOS Screenshots:

Bildschirmfoto 2021-05-01 um 13 18 27

**Comment by Ein-Tim** [comment]
https://github.com/corona-warn-app/cwa-website/blob/release-screenshots/src/assets/img/screenshots/de/ios/rat_7.png has to be changed in accordance to https://github.com/corona-warn-app/cwa-app-ios/pull/2603

**Comment by dsarkar** [comment]
image

no 9 missing, we know. for the moment I will put there an Android screen until can produce an iPhone screen

**Comment by Ein-Tim** [comment]
@dsarkar Okay, agreed. Please also take a look at the "Testergebnis abrufen" section, the screenshots always show the same screen...

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for point that out

EN fixed:
image

**Comment by dsarkar** [comment]
iOS DE kaputt

image

**Comment by Ein-Tim** [comment]
@dsarkar Yes, indeed it's kaputt (; If you don't have these screenshots at the moment I suggest that you replace it with the English once 🙂

**Comment by dsarkar** [comment]
DE fixed - nicht mehr kaputt ;-) using 2.0 ones. 

image

**Review by Ein-Tim — APPROVED** [review]

**Comment by dsarkar** [comment]
do not delete branch.

**Pull request merged**
