### PR TITLE
Remove function modifying results subheader links

### LINKED ISSUE #2827: Unexpected target of header links on FAQ results page
## Where to find the issue

https://www.coronawarn.app/en/faq/results/
https://www.coronawarn.app/de/faq/results/

## Describe the issue

The FAQ links in the `header` section of https://www.coronawarn.app/en/faq/results/ are dynamically pointing to articles in https://www.coronawarn.app/en/faq/ instead of in https://www.coronawarn.app/en/faq/results/.

Sometimes the Cypress test `check_anchor_links.js` fails leaving the log file `broken_anchor_links_result.txt` in the `cypress/logs` directory showing:

```
==================== Broken anchor links ====================

http://localhost:8000/en/faq/#who_can_help on '/en/faq/results/' 
http://localhost:8000/en/faq/#where_can_i_get_tested on '/en/faq/results/' 
http://localhost:8000/en/faq/#test_result_issues on '/en/faq/results/' 
```

This may be due to the time it takes to redirect multiple times to the correct article.

## Steps to reproduce

Open https://www.coronawarn.app/en/faq/results/
Hover over the link "Who helps regarding Corona-Warn-App questions?" and note that the tool-tip shows https://www.coronawarn.app/en/faq/#who_can_help. This is not expected.

who_can_help on results

Open https://www.coronawarn.app/en/faq/
Hover over the link "Who helps regarding Corona-Warn-App questions?" and note that the tool-tip shows https://www.coronawarn.app/en/faq/results/#who_can_help. This is expected and for comparison with the above.

## Expected behaviour

The header links on https://www.coronawarn.app/en/faq/results/ should link directly to the https://www.coronawarn.app/en/faq/results/ page. For instance, if https://www.coronawarn.app/en/faq/results/ is opened, hovering over the link "Who helps regarding Corona-Warn-App questions?" should show the tool-tip https://www.coronawarn.app/en/faq/results/#who_can_help not https://www.coronawarn.app/en/faq/#who_can_help

## Suggested change

The source `public/en/faq/results/index.html` shows for example `/en/faq/results/#who_can_help` not /`en/faq/#who_can_help` in the `header` so presumably the URL is being changed dynamically.

```
        <ul class="col-sm-12 text-center subheader pt-2 pb-2 list-inline">
          <li>
          <a href="/en/faq/results/#who_can_help" >
              Who helps regarding Corona-Warn-App questions?
          </a>
          </li>
          <li class="list-inline-item">
          <a href="/en/faq/results/#where_can_i_get_tested" >
              Where to get tested?
          </a>
          </li>
          <li class="list-inline-item">
          <a href="/en/faq/results/#test_result_issues" >
              Missing test result/test certificate?
          </a>
          </li>
        </ul>
```

Check JavaScript actions so that the three links in the header on https://www.coronawarn.app/en/faq/results/ do not get the `/results` part of the path removed:

1. `/en/faq/results/#who_can_help`
2. `/en/faq/results/#where_can_i_get_tested`
3. `/en/faq/results/#test_result_issues`

### PR DESCRIPTION
**Pull request by larswmh**
Fixes #2827

### CODE REVIEW

**Comment by MikeMcC399** [comment]
As @dsarkar noted in https://github.com/corona-warn-app/cwa-website/issues/2827#issuecomment-1115987937 this PR currently has the unwanted side effect of not displaying the target article.

Clicking on https://www.coronawarn.app/en/faq/results/#who_can_help should display this article with its following text visible.

**Comment by larswmh** [comment]
@MikeMcC399 
With a new function provided by @ibexad (https://github.com/corona-warn-app/cwa-website/pull/2828/commits/5c8ff422f53a725f4c8a3b65d67372a543794b00) this is now fixed and Cypress does not consider the subheader links on the FAQ results page broken anymore

**Review by dsarkar — APPROVED** [review]

**Review by svengabr — APPROVED** [review]

**Review by MikeMcC399 — APPROVED** [review]
I checked on the Ubuntu machine where Cypress was previously producing unreliable fail/pass results and now all tests pass.

Thank you!

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for your feedback!

**Pull request merged**
