### PR TITLE
Screenshot archive: select functionality and styling

### PR DESCRIPTION
**Pull request by notariorob**

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Could you explain what this PR does @notariorob, please (:

**Comment by notariorob** [comment]
Definitely! It adds the redirect functionality to a version select input that will send the user to the appropriate page once the selected option has changed. It also styles said control using bootstrap's classes so that it looks similar to the other controls on the site and positions itself to the right side of the android/iOS nav-tabs on desktop, and above them on mobile.

**Comment by Ein-Tim** [comment]
@notariorob Thanks for the explanation!

**Comment by svengabr** [comment]
Sorry for the confusion here, this pull request was developed by one of your internal team members - @notariorob - and he got the task assigned from me directly.

Our UX team said that the dropdown visual indicators were missing on the event registration page:

2021-05-26 08_16_36-Open-Source-Projekt für Corona-Warn-App – Event QR Code

**Comment by Ein-Tim** [comment]
@svengabr 

No need to apologize, thank you too for your explanation!

**Pull request merged**
