### PR TITLE
Release 2.8 Screenshots + alt changes

### PR DESCRIPTION
**Pull request by larswmh**
In addition to the new screenshot section for 2.8, I also replaced the old undefined/falsely defined alts with correct alts. ([this issue](https://github.com/corona-warn-app/cwa-website/issues/1655)). Furthermore, I've removed every unused image from the 2.8 screenshots folder.

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by Ein-Tim** [comment]
Bildschirmfoto 2021-08-24 um 22 43 20

iOS screenshots in Android section?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> iOS screenshots in Android section? This is also live currently, maybe we can change this with this PR?

This is the same issue as already reported for the 2.6 screenshots in https://github.com/corona-warn-app/cwa-website/issues/1549

**Comment by Ein-Tim** [comment]
@MikeMcC399 Thanks for mentioning this issue. I knew that we have an issue reg. this but I couldn't find it. 
Anyways, I think this PR would be a good opportunity to fix this.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
>  I think this PR would be a good opportunity to fix this.

The Android app needs to automatically generate the required screenshots for the sections:

1. "Check certificates for validity before a trip"
2. "Invalid certificates"

and as far as I can see, the functionality to capture these screenshots has not yet been programmed into the Android app, so that would need a separate PR in https://github.com/corona-warn-app/cwa-app-android/pulls. The website PR can only deal with available screenshots.

@larswmh 
Should we submit a separate issue against the Android app to get these screenshots generated or is this already in hand internally?

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim The mentioned Android screenshots are not yet produced automatically (therefore not in the assets). We will correct this at a later stage. We have that internally tracked, stand by for ticket numbers. 

Thanks!

**Comment by MikeMcC399** [comment]
@dsarkar 

Unfortunately there is a typo:

"In addition to the name in country-specific spelling, the name is now also displayed in standardized atin spelling in each certificate"

That should be "Latin" not "atin".

**Pull request merged**
