### PR TITLE
Update faq 39508

### PR DESCRIPTION
**Pull request by dsarkar**
Closes https://github.com/corona-warn-app/cwa-website/issues/781

### CODE REVIEW

**Comment by dsarkar** [comment]
EN

image

**Comment by dsarkar** [comment]
DE version in progress ...

**Comment by MikeMcC399** [comment]
@dsarkar 
> DE version in progress ...

The error message in German is:

<string name="errors_risk_detection_limit_reached_title">"Limit bereits erreicht"</string>

<string name="errors_risk_detection_limit_reached_description">"Heute sind keine weiteren Risiko-Überprüfungen möglich, weil das von Ihrem Betriebssystem festgelegte Limit von Risiko-Überprüfungen pro Tag bereits erreicht ist. Bitte überprüfen Sie Ihren Risikostatus morgen wieder."</string>

from strings
```
errors_risk_detection_limit_reached_title
errors_risk_detection_limit_reached_description
```

**Comment by heinezen** [comment]
@dsarkar @MikeMcC399 Should this get its own FAQ entry? I don't see why the "limit reached" error necessarily has to be group together with a seemingly unelated issue.

**Comment by MikeMcC399** [comment]
@heinezen 

The underlying Android error status is still 39508. The message from CWA is however no longer 39508, it has been changed to a reader-friendlier message which says:


<string name="errors_risk_detection_limit_reached_title">"Limit already reached"</string>

Here is the link to the Google documentation for the error code:
https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationStatusCodes?hl=en#public-static-final-int-failed_rate_limited.

**Comment by heinezen** [comment]
I think from a user-perspective, the ammendment of 39508 is confusing (even though it makes technical sense).

I have made a counter-proposal to this approach https://github.com/corona-warn-app/cwa-website/commit/491faf68a96c4b6e08de803697845e41afd0dca1 where the limit reached error has a separate entry that is linked in the original 39508 entry. Didn't change much else.

**Comment by MikeMcC399** [comment]
@heinezen 
That's a valid point and a good suggestion!

**Comment by dsarkar** [comment]
@heinezen @MikeMcC399 
 491faf6 LGTM. 
 Usually we keep the history and track of changes of all entries. Suggestion: We move the old 39508 entry to the bottom of the FAQ, section "resolved" with a comment/link to your new article. Altogether this will look cleaner. I will discuss this internally if it is ok to proceed this way, and then, if approved, we can create finally a PR as you suggested. Thanks!

**Comment by dsarkar** [comment]
@heinezen @MikeMcC399 
Internally discussed:
In order to harmonize, shorten, clean-up the FAQ page we now create a .md file, where we document outdated FAQ entries. We will link the old and new article mutually, so it is transparent but at the same time it should look cleaner.

**Comment by MikeMcC399** [comment]
@dsarkar 
> In order to harmonize, shorten, clean-up the FAQ page we now create a .md file, where we document outdated FAQ entries. We will link the old and new articles mutually, so it is transparent but at the same time, it should look cleaner.

Good idea! The FAQ list is now very long and if someone is viewing on a mobile device it can be quite difficult to find the relevant information.

If the minimum versions of the app on iOS and Android are increased then the entries which only refer to problems with versions which are subject to forced update can be archived. So in the .md file split into a section for resolved issues and another section for resolved issues with versions no longer supported perhaps?

See your comments about minimum versions:
https://github.com/corona-warn-app/cwa-website/pull/852#issuecomment-775905999
https://github.com/corona-warn-app/cwa-website/pull/852#issuecomment-775979928

and server config:
https://github.com/corona-warn-app/cwa-server/blob/a22242bea548dea6f6e35c4fe4c8eba3d8b4fc64/services/distribution/src/main/resources/application.yaml#L112-L119

    app-versions:
      latest-ios: ${IOS_LATEST_VERSION:1.5.3}
      min-ios: ${IOS_MIN_VERSION:1.5.3}
      latest-android: ${ANDROID_LATEST_VERSION:1.5.1}
      min-android: ${ANDROID_MIN_VERSION:1.5.1}
      # With ENF v2 Android apps are versioned by Version Code and not by Semantic Versioning
      min-android-version-code: ${ANDROID_MIN_VERSION_CODE:48}
      latest-android-version-code: ${ANDROID_LATEST_VERSION_CODE:48}

**Comment by dsarkar** [comment]
replaced in favour of https://github.com/corona-warn-app/cwa-website/pull/895

**Pull request closed without merging**
