### PR TITLE
Search function for the blog

### PR DESCRIPTION
**Pull request by Crystalskulls**
I have created a search function for the blog page. The search is based on the search function of the FAQ section.

For each blog entry i create a json object in the gulp workflow with blog title as key and the value consists of the blog title, the page description and the html content. I was not able to find a solution to use a javascript object as gulp source stream. So i decided to store the blog entries in a tmp file, used the tmp file as source stream und afterwards removed the tmp files (see changes in gulpfile.js). Not the best way, but still working. Maybe someone has a better solution for this.

If you search and press enter, you see that a URL parameter called "search" is added. This way, you can also link to search results. (Similar to FAQ Page)

---
Internal Tracking ID: [EXPOSUREAPP-13072](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13072)

### CODE REVIEW

**Comment by Ein-Tim** [comment]
I tested this change and can confirm that the search works as I expect!
I can't comment on code style/quality, though.

Anyways, thank you very much @Crystalskulls!

**Comment by dsarkar** [comment]
@Crystalskulls Thanks for the PR. We are currently doing a mayor makeover of the FAQ, so, please be patient. We will consider this after going online with the new FAQ. Thanks again!

**Comment by Crystalskulls** [comment]
@dsarkar Thanks for the information. As soon as the new FAQ page is online, i would adjust the search function in the blog page if necessary.

**Comment by Crystalskulls** [comment]
@dsarkar I merged the latest commits of the master branch and resolved the conflicts in gulpfile.js and app.js. The blog search is based on the old faq search. I think this is good enough as first version for the blog search feature.

@Ein-Tim Would you please test the blog search again to confirm that it still works as expected? That would be nice!

Feel free to contact me, if you have additional requirements for the blog search feature. Thank you guy's, have a good afternoon! 🙂

**Comment by Crystalskulls** [comment]
I've merged the latest changes of the master branch and resolved the conflicts in gulpfile.js
I found a bug in the blog search feature depending on the new function **AddEnglishSpecifier**. This function replaces english text snippets in the html code of the blog entries. This results in some corrupt html because i used the blog title as ID for the Blog entries. So i decided to use the blog slug instead.

I did some additional testing and in my opinion the blog search still works.

**Review by Ein-Tim — APPROVED** [review]
Tested again with the latest changes, still works. So still a GO from my side!

## Environment

- macOS Monterey (12.3.1)
- Safari 15.4
- MacBook Air M1

**Comment by Ein-Tim** [comment]
@dsarkar / @larswmh / @svengabr 

Dear Open-Source-Team, 
could you please let us know what the plan for this enhancement is?

Thank you!

**Comment by dsarkar** [comment]
@Ein-Tim  @Crystalskulls  We are waiting for final approval. Thanks!

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@Crystalskulls Thanks again for the PR and contributing here. This PR has been approved. We will have to wait with merging it until we fix some server issues. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Review by Ein-Tim — COMMENTED** [review]
Somehow the blog does not show the correct number of blogs but only "X / X".

FYI @Crystalskulls

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The deployment is broken at the moment.

**Comment by MikeMcC399** [comment]
There was a problem with the deployment not setting the mime-types correctly.

**Comment by HelTob** [comment]
Dear Benedict (@Crystalskulls) ,

thank you very much for your contribution. 
We appreciate your commitment and are very happy to see the active participation of the community. 
Without people like you, the project would not have been such a success.
Also, thank you to all the other contributors from the community for testing and your helpful comments.

Have a great day and keep up the good work
Tobias

**Pull request merged**
