### PR TITLE
Update iOS version to 15.0

### PR DESCRIPTION
**Pull request by jucktnich**

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Just FYI, this update is shown like this: 
IMG_1893

I would argue that we should wait with a general recommendation for iOS 15 until it's tested with the current release and the next upcoming release (2.10) to make sure everything is working.

But I'd leave this decision to the Open Source Team

Btw @jucktnich Do you plan to maintain the versions in the gulpfile on a regular basis now? Because I had already prepared this and also prepare the other gulpfile changes, so if you want to maintain the versions to we should make sure that we don't duplicate our work (:

**Comment by jucktnich** [comment]
Oh yeah sorry. I think apple stage rollouts its iOS updates, so for some it appears while for others not. But I guess it makes sense to wait a bit before updating it.

**Comment by jucktnich** [comment]
But you can still maintain this file, I'll stand back

**Comment by Ein-Tim** [comment]
Apple has announced the release now: https://developer.apple.com/news/releases/?id=09202021d & https://www.apple.com/newsroom/2021/09/ios-15-is-available-today/

In the future I'll continue to prepare updates to this file, however, I understand the excitement about iOS 15, so please, leave this PR open (-:

The Open-Source Team should probably talk to the devs whether we should recommend an update already or still wait some time. 

Thanks for taking care @jucktnich!

**Comment by jucktnich** [comment]
I more meant, that we maybe should wait a bit, cause the staged rollout could confuse people if they don't get the update shown but we recommend it ;-)

**Comment by jucktnich** [comment]
Btw I made this PR only cause I started learning git/GitHub, I don't have the desire to maintain it, but I would be ok with maintaining it for sure.

**Comment by Ein-Tim** [comment]
@jucktnich If you want to take maintenance of this file over, please, feel free to do so. 
However, there are more "exciting" ways to learn Git (-;
Just lemme know what you want, we can also chat via Slack direct message (:

**Comment by jucktnich** [comment]
Yeah it was just a "my first PR in the wild" thing :-). But thank you for the offer

**Comment by MikeMcC399** [comment]
@jucktnich 

You should follow the recommendation in https://github.com/corona-warn-app/cwa-website/blob/master/CONTRIBUTING.md to create a new branch from the `master` branch with a suitable name (like in this instance `update-ios-to.15.0`) then do the edits in the branch. You might need to rebase your branch on a `master` branch which other people have updated and you can't do that if you work directly in `master`.

You might get away without creating a new branch this time. Wait and see.

Also, there is a note about squashing your commits. You first made a change to 15, then to 15.0 so those two commits should be squashed.

It took me quite a while to learn how to do this and I am still learning!

Did you already take any git training course?

**Comment by jucktnich** [comment]
I did, but it weirdly never mentioned the topics you stated 🤷‍♂️

**Comment by MikeMcC399** [comment]
@jucktnich 
> I did, but it weirdly never mentioned the topics you stated

This section covers what I wrote about:

https://github.com/corona-warn-app/cwa-website/blob/master/CONTRIBUTING.md#pull-request-checklist

* Branch from the `master` branch and also target `master` with your Pull Request.
* If you make several related fixup commits in a row, you should [squash](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) them into a single commit.

If you branch from the `master` branch, your branch is not called `master` any more. You have to give it a different name.

**Comment by jucktnich** [comment]
@MikeMcC399 i meant I did a course about git. I missed that there's a contributing file.

**Comment by jucktnich** [comment]
Btw the broad rollout seems to have started in Germany

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@jucktnich @Ein-Tim @MikeMcC399 Thanks!

**Comment by dsarkar** [comment]
@jucktnich Congrats to your first PR!

**Comment by jucktnich** [comment]
@dsarkar thank you
@Ein-Tim @MikeMcC399 thanks for your help and patience

**Comment by MikeMcC399** [comment]
@jucktnich 
You will probably find that you'll need to clean up the [master branch of your fork](https://github.com/jucktnich/cwa-website/tree/master) now because it is out of sync with the [upstream master branch](https://github.com/corona-warn-app/cwa-website/tree/master). That is, if you are planning to submit any other PRs. Unfortunately working directly in the `master` branch causes these issues, which is why it's normal practice to create a new branch (forked from `master`) and work in that one.

**Comment by Ein-Tim** [comment]
@jucktnich 

Just to be sure I didn't got you wrong: Will you continue to update the versions in the gulpfile or should I do it? 😅

**Comment by jucktnich** [comment]
You should do it, but if you can't do it (longer vacation, ...) I would volunteer to step in.

**Comment by Ein-Tim** [comment]
@jucktnich 

Okay, sounds good! Thank you!

**Pull request merged**
