### PR TITLE
Accessibility Improvements

### LINKED ISSUE #94: Accessibility: Missing alternative texts for images
## Where to find the issue
1. Decorative images in the section _Wie funktioniert die App?_ or _How does the app work?_ on the main page
2. GitHub Icon in the header and the footer
3. Card images for news articles on `/news`

## Describe the issue
1. The decorative images on the main page have no alternative text.
2. The GitHub icon functions as a link but lacks an alternative text to describe its destination 
3. The images, used in the news cards have no alternative text.

## Suggested change
1. Add an empty alternative text `alt=""` to declare the image as purely decorative, [as recommended by the WCAG](https://www.w3.org/WAI/tutorials/images/decorative/#image-used-as-part-of-page-design).
2. Add an alternative text, describing the GitHub repository as the links destination, for example `alt="GitHub Repository"`
3. Add an alternative text to the `` tag. Depending on, whether these images are deemed purely decorative or functional, the alt text has to be empty `alt=""` or a description of the iamge content.

### PR DESCRIPTION
**Pull request by mojoaxel**
I did some improvements to satisfy [Google's Lighthouse Accessability tests](https://web.dev/measure/).

_this also fixes #94 as far as I can see it._

 ## Before
image

## With these changes (and the changes from #150 )
image

Please let me know If you need me to change this PR in any way.

### CODE REVIEW

**Comment by mojoaxel** [comment]
I moved commit 3e41f5064a10edf56adecaa8b60a93be025742f9 , that was part of this PR to to a seperate pull request #150

**Comment by mojoaxel** [comment]
@tkowark Any comment on this? Are you still interested in external contributions?

**Comment by tkowark** [comment]
Yes, we‘re still interested and I will review next week (currently on a short vacation)

**Comment by mojoaxel** [comment]
:tada: You are welcome!

**Pull request merged**
