### PR TITLE
Correct TRL

### LINKED ISSUE #765: Blog post December 17, 2020 note: Number of transmission risk level
## Where to find the issue
https://github.com/corona-warn-app/cwa-website/blob/master/blog/2020-12-17-risk-calculation-enf-2-0/index.md
https://github.com/corona-warn-app/cwa-website/blob/master/blog/2020-12-17-risk-calculation-enf-2-0/index_de.md

## Describe the issue
Mention of only VII (7) transmission risk level instead of VIII (8), while the nomalized risk factor is given as 0.6 to 1.6 (Division by 5) acc. to the linked diagram: 
https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf

This holds true for the English as well as the German version of the blogpost. 

## Suggested change
Changing the number of transmission risk level to VIII (8).

---
[EXPOSUREAPP-4529](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4529)

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR corrects the TRL in the blog post and in the FAQ entry.

Closes #765

---
[EXPOSUREAPP-4529](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4529)

### CODE REVIEW

**Comment by Ein-Tim** [comment]
I only touched the TRL, the other changes (are no real changes) and seem to come from my editor (VSC). I will investigate why this happens.

**Comment by dsarkar** [comment]
Info forwarded. Thanks.

**Comment by Ein-Tim** [comment]
Okay I thought maybe I could get the diff a bit smaller but seems to be not possible. Now trying to squash the commits...

**Comment by MikeMcC399** [comment]
I don't think this should be merged in its current state. It has too many changes to unrelated parts of the FAQ.

**Comment by Ein-Tim** [comment]
Yeah it's not optimal, @dsarkar should I open a new PR for this?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Yeah it's not optimal, @dsarkar should I open a new PR for this?

Of course it is up to the Open Source Team to decide, but I would be a bit scared of merging this one in its current state.  Unfortunately I don't know how you could clean it up. As you know, I'm not such an expert and I am still learning myself!

**Comment by Ein-Tim** [comment]
I think this PR is ok, since if you hide whitespace changes here everything is correct

**Comment by Ein-Tim** [comment]
Will close this PR, completely mess... I'm so sorry. Will open a new PR soon

**Comment by Ein-Tim** [comment]
New PR: #793

**Pull request closed without merging**
