### PR TITLE
Restore [Browsersync] Reloading Browsers functionality

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves issue https://github.com/corona-warn-app/cwa-website/issues/2239 "browser-sync does not refresh browser".

It adds back `'unsafe-inline' 'unsafe-eval'` in the Content Security Policy `default-src` fetch directive in places where it was removed.

The CSP of https://www.coronawarn.app/en/analysis/ already includes the two directive values `'unsafe-inline' 'unsafe-eval'`, so there is already a precedent for allowing these values on the production website.

## Verification

Execute
```
npm ci
npm start
```

When the web browser starts, go to http://localhost:8000/en/faq/.

Edit `src\data\faq.json` and save the change.
For instance make a change in the title on line 4.

Wait for `[Browsersync] Reloading Browsers...` to appear in the terminal window.
Notice that the contents of the browser has been automatically updated and includes the change made above.

### CODE REVIEW

**Review by browkin — APPROVED** [review]
@MikeMcC399 Tested locally. Thank you for the fix.

**Comment by mtb77** [comment]
Hi @MikeMcC399 - thanks for the suggestion. I think it's a good idea which makes sense especially for text changes, so I would like to approve this.
However, this was added to test and see new upcoming issues with JS and the server-based CSP. Would you be so kind and also add a description for testers how to add the policy back again to test according to the server policies?
Thanks so much!

Sascha

**Comment by MikeMcC399** [comment]
Hi @mtb77 

Thank you for your inputs and your comments that you would like to approve.

Are the server policies which you refer to published anywhere? I don't think there is anything documented in the README here, so I don't know how this is supposed to work.

Are the CSP settings produced by the `npm run build` command used by the production nginx server https://www.coronawarn.app or are they ignored or overwritten? I see for the science blogs there is an explicit `--remove-header=Content-Security-Policy` so that makes it look like they might be transferred by default from the build result. Have any or all of the Content Security Policy settings on the production server been defined through manual AWS S3 console commands?

I think I would need to understand the above first before I could get close to adding a description for testers to test in a stricter environment. An alternative would perhaps be to add a parameter to the `npm run start-server` task to make it run with stricter CSPs.

---

The fallback for this PR would be not to implement it and simply document in the README that it is necessary to refresh the browser manually (F5) to get an update. In practice this means for multiple updates of text, you would be pressing Ctrl-S to save in an editor, then F5 to view, each time you wanted to view the results of a change. This is the way it is working right now.

I also found https://github.com/BrowserSync/browser-sync/issues/1395 which discusses using `nonce` to allow Browsersync to refresh, which could be an alternative to `'unsafe-inline' 'unsafe-eval'`. Unfortunately this is past my level of expertise, so if that were a viable alternative I would have to pass it on to somebody else to implement.

**Comment by MikeMcC399** [comment]
@mtb77
If you could take a look at 
- https://github.com/corona-warn-app/cwa-website/issues/2258

and comment, that would also help me understand. This would be an example of a JS issue which might be hidden in a test environment if this PR were to be merged as it stands today.

I do not yet understand how the CSPs are set in the production environment though.

**Comment by mtb77** [comment]
Hi @MikeMcC399  - i have approved this PR right now - we can discuss the changes for the README.md in the issue #2258  which you mentioned!

Thank you,

Sascha

**Comment by MikeMcC399** [comment]
Hi Sascha (@mtb77)
Thanks for your approval and merge!

We can continue in #2258 as you suggest.

**Pull request merged**
