### PR TITLE
Made Links prettier

### PR DESCRIPTION
**Pull request by browkin**
- hide github link behind text

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Suggestion to change the link as suggested by @MikeMcC399 in https://github.com/corona-warn-app/cwa-website/pull/2206#issuecomment-996564271

**Comment by MikeMcC399** [comment]
@browkin 
Thank you for picking up my suggestion to make the link appear prettier!

I did also suggest using a modified search string
https://github.com/corona-warn-app/cwa-server/pulls?q=is%3Apr+log4j+2.16.0+in%3Atitle

to narrow down the results. Unfortunately whether the original search string or the one above is used, there are several PRs which were closed (not merged) so it's more difficult to find out which ones are really relevant.

I wonder even if it is helpful to publish that search string. The person who suggested it may be able to explain why it was thought to be necessary instead of just stating that the issue has been remediated through a version update.

image

**Comment by MikeMcC399** [comment]
The search string above is not such a good suggestion because it misses one PR.

Stand by for an alternative.

**Comment by MikeMcC399** [comment]
Try this search string instead:

`is:pr log4j in:title merged:>2021-12-01`

https://github.com/corona-warn-app/cwa-server/pulls?q=is%3Apr+log4j+in%3Atitle+merged%3A%3E2021-12-01

image

**Review by Ein-Tim — CHANGES_REQUESTED** [review]
Servers are currently updated to use log4j 2.17.0.
See https://github.com/corona-warn-app/cwa-server/pull/1656 & https://github.com/corona-warn-app/cwa-ppa-server/pull/377

Please reflect this in the text, either by changing the text in this PR or by changing the text in a new PR.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Good catch!

According to https://logging.apache.org/log4j/2.x/security.html there was a DoS vulnerability in Log4j 2.16.0.

Probably @ioangut should be consulted about the external message in https://www.coronawarn.app/en/faq/#log4j.

The search string I proposed
https://github.com/corona-warn-app/cwa-server/pulls?q=is%3Apr+log4j+in%3Atitle+merged%3A%3E2021-12-01
also pulls up and displays the 2.17 updates.

**Comment by MikeMcC399** [comment]
"Log4J" is incorrect capitalized in the title. It should be "Log4j" (lower case "j").

See https://logging.apache.org/log4j/2.x/

**Comment by dsarkar** [comment]
continues here https://github.com/corona-warn-app/cwa-website/pull/2214

**Comment by MikeMcC399** [comment]
@browkin 
Please close this PR, since it has been replaced by 
- #2214.

**Pull request closed without merging**
