### PR TITLE
FAQ page rework

### PR DESCRIPTION
**Pull request by brifemu**
In this PR I will include all the features where we were working lately.

- FAQ home page includes:

1. Search bar with topic filter (including glossary).
2. Section with topic and subtopics filter.
3. Link to Glossary.

image

- FAQ results page includes:

1. Right filter menu by topic and subtopic (with and without search). 
2. Search bar to make or modify a FAQ search (including glossary). 
image
Screenshot 2022-02-16 at 13 57 05
3. Breadcrumbs under search bar to navigate inside or outside a search result. 
image
4. Clickable titles and subtitles with same functionality as right filter menu.
5. In case of search: 
6.1 Highlighted subtopics on the right filter menu
image
6.2 Show the count results found in the breadcrumbs
image
6.3 Clean button on search input to reset the search.
image
6.4 Highlighted searched word in FAQ title, FAQ content and Glossary. 
image

**Page without a search:**
image

**Page with a search:**
image

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@brifemu 

Will you rebase this PR on the current https://github.com/corona-warn-app/cwa-website/tree/master branch?

This branch is still using Node14 instead of Node16.

**Comment by MikeMcC399** [comment]
@brifemu 

Please think about checking that the Cypress suite run succeeds before you finish this PR.

**Comment by MikeMcC399** [comment]
This FAQ is still in draft status, so I don't expect it to be fully working. It does however still fail the anchor links check in Cypress.

See log file: [broken_anchor_links_result.zip](https://github.com/corona-warn-app/cwa-website/files/8205559/broken_anchor_links_result.zip)

**Comment by MikeMcC399** [comment]
The links at the top of the page don't work due to their targets having moved. This kills the Cypress link tests to the extent that Google Chrome reports it is out of memory.

image

**Comment by MikeMcC399** [comment]
- According to the comment of @dsarkar in https://github.com/corona-warn-app/cwa-website/issues/1729#issuecomment-1076223553 it is planned to go live with the new FAQ website today, so probably this PR should no longer be in "Draft" status if you want it reviewed.
- The issue of dead links I mentioned in https://github.com/corona-warn-app/cwa-website/pull/2434#issuecomment-1074021396 is not yet resolved in this PR. To review, execute:
`npm run test:open`
In Cypress console select `check_anchor_links.js`
This test fails multiple times. So I hope this PR will not be merged until this issue is resolved.

**Review by GisoSchroederSAP — APPROVED** [review]
Many coding changes, I double-checked a few.
Intentionally, these changes complete the FAQ rework.

Approved from my side.

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 
> Approved from my side

Are you concerned that this PR breaks multiple links on the FAQ site?

**Comment by dsarkar** [comment]
@MikeMcC399 We are on it! We understand why it happens, fix is WIP.

**Review by MikeMcC399 — CHANGES_REQUESTED** [review]
Links need fixing. See result of `npm test`:

image

**Comment by dsarkar** [comment]
@MikeMcC399 

- We found several situations where links, as you mention in https://github.com/corona-warn-app/cwa-website/pull/2434#issuecomment-1074021396, failed, this is now fixed. 
- check_anchor_links.js fails 4 times:  #check_in_luca and #background_updates, however, we checked locally and the links work. We assume it is a timing problem of Cypress. We will look into this later.
-  check_links.js passes, except (check 851 in DE and EN blog) of https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1 , which think will not fail with https://github.com/corona-warn-app/cwa-website/pull/2554, which is not yet in this branch
image

**Comment by MikeMcC399** [comment]
For certain narrower screen widths the texts may overlap.

image

**Comment by MikeMcC399** [comment]
@dsarkar 

Thank you for the feedback about the Cypress checks. I will take another look at this myself and see if I can find any reason for the remaining failures.

**Comment by MikeMcC399** [comment]
I'm seeing the following errors logged:

```
==================== Broken anchor links ====================

http://localhost:8000/de/faq/#background_updates on '/de' 
http://localhost:8000/en/faq/#background_updates on '/en' 
http://localhost:8000/de/faq/#check_in_luca on '/de/blog/' 
http://localhost:8000/de/faq/#expcheck_160 on '/de/blog/' 
http://localhost:8000/de/faq/#low_risk_text on '/de/blog/' 
http://localhost:8000/de/faq/#app_does_not_open on '/de/blog/' 
http://localhost:8000/en/faq/#check_in_luca on '/en/blog/' 
http://localhost:8000/en/faq/#expcheck_160 on '/en/blog/' 
http://localhost:8000/en/faq/#low_risk_text on '/en/blog/' 
http://localhost:8000/en/faq/#app_does_not_open on '/en/blog/' 
```

**Comment by MikeMcC399** [comment]
Possibly the Cypress problems are due to what appears in the address bar.

After accessing `http://localhost:8000/en/faq/#background_update`s manually, the address bar shows `http://localhost:8000/en/faq/results/` which does not match.

**Comment by MikeMcC399** [comment]
@dsarkar 

I don't think it is a timing problem. If I run it in Cypress manually and hover over the link which is supposed to be `http://localhost:8000/en/faq/#background_updates` then it shows me 
`http://localhost:8000/de/community/faq/#background_updates` instead.

It looks more like some problem with dynamic redirection.

**Comment by MikeMcC399** [comment]
@dsarkar 
There are some strange interactions happening which I do not understand. I modified `check_anchor_links.js` just for troubleshooting purposes:

- checking `'/de', '/en'` passes on `'/de'` then fails on `'/en'` 
- checking `'/en'` on its own passes

Between tests, kill all browser sessions and stop the Cypress console, otherwise the results may be different.

**Comment by ibexad** [comment]
Screenshot 2022-03-24 at 11 11 45
check anchor links passed.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for your comments. I thinks all ok now with latest commits.
image

**Comment by dsarkar** [comment]
@MikeMcC399 There is some "trouble" with Cypress, and yes, I think it is due to the redirects, however, all the links now pass and work.

**Comment by MikeMcC399** [comment]
@dsarkar

I also see  `check_anchor_links.js` passing. 👍🏻 

I see two remaining issues:

1.  The formatting issue which I mentioned in https://github.com/corona-warn-app/cwa-website/pull/2434#issuecomment-1076586560.
2. `check_links.js` fails.

---
Formatting issue:

1. Open Google Chrome in desktop viewing http://localhost:8000/en/faq/
2. Shrink browser width to minimum allowed
3. Scroll down and click on "View all topics and questions" in "App Features" section
4. Note that the text shown is not formatted

---
 `check_links.js` issue

The fix from PR https://github.com/corona-warn-app/cwa-website/pull/2554 is missing. Perhaps you could Cherry pick https://github.com/corona-warn-app/cwa-website/commit/cee8b3aff1924664458a28d2c1890497b9292cdb into this branch?

**Comment by dsarkar** [comment]
@MikeMcC399 If you clicking on "View all topics and all questions" in the first column you get the badly formatted view, correct?

**Comment by MikeMcC399** [comment]
@dsarkar 
> If you clicking on "View all topics and all questions" in the first column you get the badly formatted view, correct?

There is no "first column" if the browser width is minimized. The sections are on top of one another.

image

image

**Comment by MikeMcC399** [comment]
I wondered why `build` did not run. According to https://www.githubstatus.com/ there are issues with GiHub actions currently.

**Comment by dsarkar** [comment]
@MikeMcC399 Yes, we notice already yesterday issues with GH actions.

**Comment by MikeMcC399** [comment]
The formatting seems to be fixed now. With minimum width browser window I no longer see problems.

**Comment by dsarkar** [comment]
@MikeMcC399 Filtering search results with the left menu works slightly different on desktop and mobile view:
Desktop: you can really navigate in the hierarchy and see it in the breadcrumb navigation
Mobile: It stays in the up most level (/FAQ), but jumps & opens the section or topic.

**Review by MikeMcC399 — APPROVED** [review]
I do not see any show-stoppers any more.
The Cypress issue with the link `https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1` should be solved after merging if https://github.com/corona-warn-app/cwa-website/commit/cee8b3aff1924664458a28d2c1890497b9292cdb is not Cherry-picked into this branch.

- Edit: Unfortunately the assumption about the link checking turned out to be false. PR https://github.com/corona-warn-app/cwa-website/pull/2574 submitted to fix.

**Comment by MikeMcC399** [comment]
@dsarkar 

@MikeMcC399 

> Filtering search results with the left menu works slightly different on desktop and mobile view:
Desktop: you can really navigate in the hierarchy and see it in the breadcrumb navigation
Mobile: It stays in the up most level (/FAQ), but jumps & opens the section or topic.

Thank you for explaining about the differences. I had not tried it out on a mobile device previously. I have done that now.

On a mobile device, starting at `/en/faq` if you scroll down to and tap on "Risk Assessment" then scroll back up again, it says "You can filter the content using the menu on the left side", although that menu is not visible. There is however a right-arrow visible.

I think this is something which could be optimized later though.

**Review by dsarkar — APPROVED** [review]

**Review by svengabr — APPROVED** [review]

**Pull request merged**
