### PR TITLE
Update FAQ 2.19 #rat_tan_hotline: Mention rapid PCR tests

### PR DESCRIPTION
**Pull request by larswmh**
imageimage

---
Internal Tracking ID: [EXPOSUREAPP-12118](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12118)

### CODE REVIEW

**Review by Ein-Tim — CHANGES_REQUESTED** [review]
I suggest to think about adjusting the reasoning.

1. Rapid PCR tests are always performed by trained personnel, never by users (there is no such thing as a "self rapid PCR tests")
2. [Testifly](https://testifly.de/en/), is connected to the CWA. It offers the service that users carry out a self rapid antigen test at home, record themselves by doing so and then sending the video to testify. There a staff member of Testifly looks at the video and if everything is OK, the result of the test is certified.
While one could argue that this is according to the dual control principle, it was definitely not performed by trained personnel.

**Comment by dsarkar** [comment]
@Ein-Tim Good point at this stage. We will remove last sentence for the time being. Thanks for the review.

**Review by Ein-Tim — APPROVED** [review]
Thank you, looks good to me!

**Comment by dsarkar** [comment]
ok, lets hope it will not result in a merge conflict....

**Comment by Ein-Tim** [comment]
@dsarkar I think it should not as I identically copied the content from the 2.19 branch. 

I opened #2535.

**Pull request merged**
