### PR TITLE
Bump current iOS & Android app version

### PR DESCRIPTION
**Pull request by Ein-Tim**
This commit PR the current iOS & Android app version to 2.20.3.

---

GitHub releases:
- iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.20.3
- Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.20.3

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@svengabr 

This PR should be merged.

- https://apps.apple.com/de/app/corona-warn-app/id1512595757 already shows 2.20.3 for iOS
- https://play.google.com/store/apps/details?id=de.rki.coronawarnapp is not showing 2.20.3 yet, but @thomasaugsten confirmed that it is already in rollout. See https://github.com/corona-warn-app/cwa-app-android/issues/3698#issuecomment-1084787060.

**Comment by Ein-Tim** [comment]
@dsarkar 

Please, could you merge this PR?

**Comment by dsarkar** [comment]
Good mornin g@MikeMcC399 @Ein-Tim,
 Thanks!

**Comment by MikeMcC399** [comment]
Good morning @dsarkar! It's good to see that you are back in action! 🙂

**Pull request merged**
