### PR TITLE
Uniformly use "Risiko-Ermittlung" (instead of "Risikoermittlung") in the German FAQs

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description

This PR changes all occurrences of "Risikoermittlung" to "Risiko-Ermittlung" in the German FAQ, as this is the name used in the app.

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Is it intended that I see a "build" workflow which doesn't start automatically, which is "Required" to merge this PR?
I think there were actions to the GitHub actions workflows reg. the checks for PRs, maybe you could re-check if everything is correct?

Bildschirm­foto 2023-01-12 um 23 11 58

**Comment by MikeMcC399** [comment]
@larswmh 

The [build](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) workflow is disabled

image

I guess that there is a [branch protection rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule) in place that includes the `build` workflow and which needs to be reviewed. That should be checked by a repo admin.

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
Good morning @Ein-Tim, thanks for the PR and making the wording consistent with the app across the FAQ.
@MikeMcC399 thanks for the hint, we looking for a solution right now.

**Comment by larswmh** [comment]
Good morning @Ein-Tim and @MikeMcC399, I provided a solution for the status checks in #3324

**Pull request merged**
