### PR TITLE
[Minor] "Anzahl der abgeglichenen Schlüssel" -> "Übereinstimmende Schlüssel" & "Anzahl der bereitgestellten Schlüssel" -> "Bereitgestellte Schlüssel"

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR fixes a minor inaccuracy in https://www.coronawarn.app/de/faq/#keys_matches.
Only German was affected.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@Ein-Tim 
For Android this article no longer corresponds to the v1.8 UI of the Google Exposure Notifications System and that affects both the English and German versions.

I will open an issue to describe what is wrong for Android.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Please check https://github.com/corona-warn-app/cwa-website/issues/1028. If you could comment which issues also affect iOS, that would be helpful. We can then work out which changes need to be made.

**Comment by Ein-Tim** [comment]
I changed one more thing sin this entry (see commit https://github.com/corona-warn-app/cwa-website/pull/1027/commits/966d4ca35bc0d958b6abdb69753117d66b063aec)

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.

**Pull request merged**
