### PR TITLE
Update info sharing behaviour

### PR DESCRIPTION
**Pull request by HelTob**
Hi there,

added a text passage on the subject of retrospective adjustment of the sharing behaviour data.

Best regards,
Tobias

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@HelTob 

Your change fails to build.
It seems that you have a syntax error `<br \>`  instead of `<br />` .

You can check this locally before committing if you use `npm build`.

**Comment by HelTob** [comment]
Just saw it, gosh. 
Should have tested it. 
Thanks for the advice, Mike.

**Comment by MikeMcC399** [comment]
Hi Tobias @HelTob 
Don't worry. It was easily fixed and now the build is successful!

I have some grammar improvement suggestions for the English text:

"Retrospective adjustment of the data on the sharing behaviour" =>
"Retrospective adjustment of the data on sharing behaviour" (remove "the")

"As soon as the result is shared, the number of shared results changes accordingly at the scan or call date." =>
"As soon as the result is shared, the number of shared results changes accordingly regarding the scan or call date." (change "at" to "regarding")

"The user already receives a QR code when making the appointment and scans it immediately, although he or she may not have the test performed until later." =>
"The user already receives a QR code when making their appointment and scans it immediately, although he or she may not have the test performed until later." change "the" to "their"

The text was already understandable. The changes just make the English text a bit more polished.

**Comment by HelTob** [comment]
Thanks again for your words of advice, I really appreciate it.

**Comment by MikeMcC399** [comment]
@HelTob 
> Thanks again for your words of advice, I really appreciate it.

You very welcome!

**Review by MikeMcC399 — APPROVED** [review]
It looks good to go. No further comments!

**Review by dsarkar — APPROVED** [review]

**Pull request merged**
