### PR TITLE
Release/2.22

### PR DESCRIPTION
**Pull request by dsarkar**
Closes https://github.com/corona-warn-app/cwa-website/issues/2806

### CODE REVIEW

**Review by Ein-Tim — COMMENTED** [review]
Although there was a new screenshot delivery, there are still many out of date screenshots and screenshots of the wrong OS in the iOS/Android section. I wonder where the problem lays and why it is not addressed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks we are well aware that not all screenshots are up to date. Some screenshots could be replaced in a series, but some are not in the assets. Currently, features programming and bug fixing has in general higher priority than coding the automated screenshot generator. Screenshots, which are not updated, usually have been generated manually.

**Comment by Ein-Tim** [comment]
@dsarkar 

Ah, okay, I understand, but e.g. take the screenshots from the contact journal. I can run the screenshots test manually on my device on the `release/2.22.x` branch and get other results then the screenshots which are delivered here. There seems to be a problem that the screenshots are not really generated again from each new release branch, but only the screenshots of newly implemented features are delivered. Everything else stays out of date and is not looked after.

**Comment by dsarkar** [comment]
@Ein-Tim OK, thanks, we will check whats happening there.

**Pull request merged**
