### PR TITLE
Android Screenshots for Version: 2.0.0

### PR DESCRIPTION
**Pull request by Corona-Warn-App-Technical-User**
Android Screenshots for Version: 2.0.0

---
Internal Tracking ID: [EXPOSUREAPP-6338](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6338)

### CODE REVIEW

**Comment by dsarkar** [comment]
[Open-Source Project Corona-Warn-App – Screenshots Android.pdf](https://github.com/corona-warn-app/cwa-website/files/6311047/Open-Source.Project.Corona-Warn-App.Screenshots.Android.pdf)

**Review by dsarkar — APPROVED** [review]

**Comment by Ein-Tim** [comment]
@dsarkar 

Wouldn't it make sense to add a new section "Event-Registration" to the screenshots page?

Should I open another issue for this?

**Comment by dsarkar** [comment]
@Ein-Tim we have a ticket already! Thanks!

**Comment by dsarkar** [comment]
image

**Comment by Ein-Tim** [comment]
Some screenshots have a dark overlay (second screenshot in "Contact Journal " section, first four screenshots of "Statistics" section, last screenshot in "Test registration & Key sharing" & third screenshot in "Test result home" section)

**Comment by dsarkar** [comment]
@Ein-Tim Will check, thanks.

**Comment by Art4** [comment]
> we have a ticket already! Thanks!
> EXPOSUREAPP-6420

@dsarkar Is this ticket publicly available? I couldn't find it on Github.

**Comment by Ein-Tim** [comment]
@Art4 

This is an internal tracking ID, it's not public.

**Pull request merged**
