### PR TITLE
Refresh page on change location hash in faq-results

### PR DESCRIPTION
**Pull request by brifemu**
Due to issue #2981 I'm creating this PR. The problem is that on faq-results page we don't navigate, content is hidden or showed depend on the location hash.

So, when a user go back on his browser history the content doesn't change, because the content is manipulated by our script. To get this functionality, we need refreshing on hash change.

**Pros:**
- We can navigate like in a normal web using back and forward buttons

**Cons:**
- Every time we browse we will consume more resources, because before the web was only refreshed when searching or selecting a topic, now it will refresh every time we change the hash (which are many).
- Visually it is easier to get dizzy because when you refresh the web, all the content loads again and the script have to hide again the content that we do not want to show, creating jumps on the screen.

I will leave this PR open for a time to give you the opportunity to test it and receive feedback from the community, as well as to receive suggestions for other ways to solve the problem.

---
Internal Tracking ID: [EXPOSUREAPP-13506)](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13506)

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Although this PR fixes the issue, it introduces graphic glitches caused by the reloading mentioned in the OP all over the FAQ page, so I would vote to not merge this in the current state.

**Comment by MikeMcC399** [comment]
@brifemu 

- Thank you for making an attempt to fix issue #2981!
- I had only noted this problem in the Glossary section, not in other parts of the FAQ. In the rest of the FAQ links in the body of the articles are generally set up to open in a new frame `target='_blank'` in which case the back arrow has no effect in any case.
- There is however an example https://www.coronawarn.app/en/faq/results/#who_can_help which links to https://www.coronawarn.app/en/faq/results/#qr_test without  `target='_blank'` and in this case the back arrow works (without this PR), so this shows that the issue is only in the Glossary.
- In the Glossary the links (`href`) are set up without any `target` defined.
- It has been noted that the refresh has undesirable side-effects.

## Conclusion

Since the problem only affects the Glossary and if the solution produces side-effects which negatively affect the rest of the FAQ then it would be better not to implement this solution.

**Comment by svengabr** [comment]
Agreed, so would it be better to have `target="_blank"` in the glossary so it's the same as in faq?

**Comment by MikeMcC399** [comment]
@svengabr 

> ... so would it be better to have target="_blank" in the glossary so it's the same as in faq?

That would work around the back-arrow issue and provide a more consistent user experience.

If this is changed for the Glossary, then it would be good to also make sure all the corresponding links in the top part of the FAQs also use  `target="_blank"` as currently there are a few internal links which don't have this attribute set.

**Pull request closed without merging**
