### PR TITLE
Create URL allow list  for check_links test

### PR DESCRIPTION
**Pull request by brifemu**
Due to issue #2132 I have create a allow list to avoid errors like the one like the mentioned issue. For add more URLs just have to insert it into the new arrays.

### CODE REVIEW

**Comment by Ein-Tim** [comment]
I did not test whether the changes work, however, I want to add that the word "whitelist" should not be used anymore, see https://github.com/corona-warn-app/cwa-website/issues/952#issuecomment-791924528 and the related issue https://github.com/corona-warn-app/cwa-documentation/issues/580.

I suggest you change it to "allowlist" or something similar that fits here.

**Comment by MikeMcC399** [comment]
@brifemu 

I executed 
`npm run test:open` then 
`check_links.js`
which showed 31 passed tests and 0 failed tests.

Thank you for solving this issue!

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for testing and feedback.
@Ein-Tim Thanks for your comment.
@brifemu See comment above and change the wording also in the code to "allowlist"

**Comment by brifemu** [comment]
Thanks, I've already learned it for next time. I'm sorry.

**Review by dsarkar — APPROVED** [review]

**Pull request merged**
