### PR TITLE
Update FAQ #vac_booster_basics: Replace screenshot and change text

### LINKED ISSUE #2906: Outdated graphic in FAQ #vac_booster_basics
## Where to find the issue

- FAQ https://www.coronawarn.app/en/faq/results/#vac_booster_basics "What is a booster vaccination and how does it appear in the CWA?" => https://www.coronawarn.app/assets/img/faq/vac_booster_basics_en.png

- FAQ https://www.coronawarn.app/de/faq/results/#vac_booster_basics "Was ist eine Auffrischimpfung und wie wird sie in der CWA dargestellt?" => https://www.coronawarn.app/assets/img/faq/vac_booster_basics_de.png

## Describe the issues

The images:
- https://www.coronawarn.app/assets/img/faq/vac_booster_basics_en.png
- https://www.coronawarn.app/assets/img/faq/vac_booster_basics_de.png

are supposed to show what a booster vaccination certificate looks like in the app, however the tile for the booster vaccination is missing the button for "Check Validity for Travel" which is displayed on CWA Android 2.22.

- The screenshot is taken from a small device and the tile regarding the device owner only shows half of it with text "Onehundred Reminder Booster" which makes no sense as it is cut off from the beginning of the sentence.
- The tile "Vaccination Status" is not shown at all.
- The images are very large (1.8 MB). 

## Comparison

Current web image | Screenshot 2.22 Android
--- | ---
vac_booster_basics_en_saved | Example Booster 2 22

## Suggested change

Replace the images with up-to-date and smaller images. The PNG file size should not need to be more than 250KB. Even re-saving the existing outdated file reduces its size from 1.8MB to 192KB.

### PR DESCRIPTION
**Pull request by larswmh**
Fixes #2906 

- Replace small screenshot with larger screenshot
- Reduce size to ~200KB
- Adjust recommended booster vaccination wait time in text according to BNR-DE-0110
image
image

### CODE REVIEW

**Review by MikeMcC399 — COMMENTED** [review]
- Issue https://github.com/corona-warn-app/cwa-website/issues/2906 is resolved by this issue.

Regarding the images:

- vac_booster_basics_en.png (207 KB - 1242 x 2688 pixels) 
- vac_booster_basics_de.png (200 KB - 1242 x 2688 pixels)

and considering that the image is first displayed using `width="300"` (compare to image width 1242), the image could be further reduced in size for web viewing without loss of clarity.

**Comment by larswmh** [comment]
@MikeMcC399 
> considering that the image is first displayed using `width="300"` (compare to image width 1242), the image could be further reduced in size for web viewing without loss of clarity.

Considering this screenshot will only be used inside the FAQ, I totally agree. The width is relatively low to the screenshots original width so it does not take up that much space. However, when opening it in a new tab and zooming in, it would lose a lot of quality. I would prefer to leave it as it is, although we could get each screenshot down to about 30KB with this. Current implementation is still an improvement compared to the last screenshot used in this FAQ and using this screenshot now keeps the possibility for others to inspect this screenshot in full quality.

**Review by MikeMcC399 — APPROVED** [review]
@larswmh

> I would prefer to leave it as it is, although we could get each screenshot down to about 30KB with this.

It's OK with me if that is your preference.

Thank you in any case for addressing the issue!

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
Hi @MikeMcC399 Thanks for reporting the issue and commenting/reviewing!

**Pull request merged**
