### PR TITLE
dcc_replacement_howto article added

### PR DESCRIPTION
**Pull request by svengabr**
/de/faq/results/?search=&topic=all#dcc_replacement_howto
/en/faq/results/?search=&topic=all#dcc_replacement_howto

German:
deutsch

English:
englisch

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Same as #2905?

**Comment by svengabr** [comment]
@Ein-Tim 
This is actually #2905 I'm sure it was a typo. Did I create a duplicate here?

**Comment by Ein-Tim** [comment]
@svengabr Sorry, yes, I think this is a duplicate of #2904, or?

**Comment by svengabr** [comment]
Looks like we both grabbed the same Ticket, I will close my PR since Brians's PR is already a bit further ahead

**Pull request closed without merging**
