### PR TITLE
Update info banner

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description

This PR updates the site-wide info banner to reflect that the 31.04.2023 has passed.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@Ein-Tim 

For consistency, also https://github.com/corona-warn-app/.github/tree/main/profile/README.md should be updated.

**Review by MikeMcC399 — APPROVED** [review]

**Comment by Ein-Tim** [comment]
As well as the descriptions of some of the GitHub repositories.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> As well as the descriptions of some of the GitHub repositories.

I expect that the repositories will be archived soon and I would not suggest to change them now. If the status of a repository is archived, then it says that the information is no longer current. It would be possible of course to change the READMEs etc. but I don't think that the effort is justified.

 I seem to remember you have quite a few dangling 2023 copyright PRs open in various repos, which you might want to close.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Sorry for not being clear, I didn't mean to change the information in the README.md files but these texts:
image

I will take care of the copyright PRs, thanks for the reminder!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

It seems that you are referring to the text which appears in the "About" section of the repository which comes from the "Description" field.

That same text is also in a pinned locked issue, for example https://github.com/corona-warn-app/cwa-website/issues/3445

@larswmh may have an automated way to update these texts. If it would need to be done manually, then I don't think that the work is justified. The text is not incorrect.

**Review by dsarkar — APPROVED** [review]

**Pull request merged**
