### PR TITLE
Add markdown-link-check and checklinks script

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR implements the suggestion from https://github.com/corona-warn-app/cwa-website/issues/3313 "Add Markdown-link-check for unchecked Markdown files"

It adds the npm package [markdown-link-check](https://www.npmjs.com/package/markdown-link-check) with a  `checklinks` script to check Markdown source files.

Only `*.md` files in the top-level directory of the cwa-website and the sub-directory `docs` are checked. (Other `*.md` files are used as source files for HTML output and this is checked by the Cypress tests already.)

To check Markdown files execute:

```bash
npm run checklinks
```

An individual Markdown file can also be checked using the npm package [markdown-link-check](https://www.npmjs.com/package/markdown-link-check) directly, for example:

```bash
npx markdown-link-check README.md
```

## Verification

Execute
```bash
npm ci
```
to install [markdown-link-check](https://www.npmjs.com/package/markdown-link-check).

Execute the following on Windows, Ubuntu and macOS and confirm that 8 Markdown files are successfully checked:

```text
npm run checklinks
> corona-warn-app-landingpage@1.3.0 checklinks
> find . docs -maxdepth 1 -name '*.md' -print0 | xargs -0 -n1 markdown-link-check


FILE: ./CODE_OF_CONDUCT.md
  [✓] mailto:corona-warn-app.opensource@sap.com
  [✓] https://www.contributor-covenant.org
  [✓] https://www.contributor-covenant.org/version/2/0/code_of_conduct.html
  [✓] https://github.com/mozilla/diversity
  [✓] https://www.contributor-covenant.org/faq
  [✓] https://www.contributor-covenant.org/translations

  6 links checked.

FILE: ./CONTRIBUTING.md
  [✓] CODE_OF_CONDUCT.md
  [✓] mailto:corona-warn-app.opensource@sap.com
  [✓] #steps-to-contribute
  [✓] CODEOWNERS
  [✓] #pull-request-checklist
  [✓] LICENSE
  [✓] https://git-scm.com/downloads/guis/
  [✓] https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
  [✓] https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things
  [✓] https://git-scm.com/book/en/v2/Git-Branching-Rebasing

  10 links checked.

FILE: ./README.md
  [✓] https://www.coronawarn.app/en/
  [✓] https://observatory.mozilla.org/analyze/coronawarn.app
  [✓] #about-this-repository
  [✓] #development
  [✓] #documentation
  [✓] #support-and-feedback
  [✓] #how-to-contribute
  [✓] #licensing
  [✓] https://coronawarn.app
  [✓] https://github.com/corona-warn-app/cwa-documentation
  [✓] https://nodejs.org/en/
  [✓] https://support.apple.com/en-us/HT211861
  [✓] package.json
  [✓] ./docs/
  [✓] https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell
  [✓] https://www.coronawarn.app
  [✓] #getting-started
  [✓] https://docs.cypress.io/guides/guides/command-line#cypress-version
  [✓] https://docs.cypress.io/guides/guides/command-line#cypress-cache-list
  [✓] https://docs.cypress.io/guides/guides/command-line#cypress-cache-prune
  [✓] https://developer.mozilla.org/en-US/docs/Glossary/MIME_type
  [✓] ./blog
  [✓] ./docs
  [✓] https://github.com/features/actions
  [✓] .github/workflows
  [✓] https://github.com/corona-warn-app/cwa-website/issues/new/choose
  [✓] mailto:corona-warn-app.opensource@sap.com
  [✓] ./CONTRIBUTING.md
  [✓] ./CODE_OF_CONDUCT.md
  [✓] https://github.com/corona-warn-app/cwa-documentation/blob/main/README.md#repositories
  [✓] https://www.apache.org/licenses/LICENSE-2.0
  [✓] ./LICENSE
  [✓] https://www.bundesregierung.de/breg-en/federal-government/federal-press-office
  [✓] https://raw.githubusercontent.com/corona-warn-app/cwa-documentation/main/images/CWA_title.png
  [✓] https://img.shields.io/mozilla-observatory/grade/coronawarn.app
  [✓] https://img.shields.io/github/issues/corona-warn-app/cwa-website?style=flat-square
  [✓] https://img.shields.io/badge/email-CWA%20team-green?logo=mail.ru&style=flat-square&logoColor=white

  37 links checked.

FILE: ./SECURITY.md
  [✓] mailto:corona-warn-app.opensource@sap.com
  [✓] https://www.sap.com/about/trust-center/security/incident-management.html
  [✓] https://github.com/corona-warn-app/cwa-website/releases

  3 links checked.

FILE: docs/CHANGE_WEBSITE_CONTENT.md
  [✓] https://github.com/foundation/panini
  [✓] ../src/pages/
  [✓] ../src/layouts/
  [✓] ../src/partials/
  [✓] ../src/data/
  [✓] https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq.json
  [✓] https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq_de.json

  7 links checked.

FILE: docs/CREATE_BLOG_REDIRECTS.md
  [✓] ../blog/2020-08-11-hinweise-qr-code/index.md

  1 links checked.

FILE: docs/FAQ_SEARCH_SUMMARY.md
  [✓] ../gulpfile.mjs
  [✓] ../src/data/faq.json
  [✓] ../src/data/faq_de.json
  [✓] ../src/assets/js/app.js

  4 links checked.

FILE: docs/WRITE_BLOG_POSTS.md
  [✓] https://getbootstrap.com/docs/4.0/content/images/#aligning-images
  [✓] https://raw.githubusercontent.com/corona-warn-app/cwa-documentation/main/images/CWA_title.png

  2 links checked.
```

### Windows alternative shells

To test in Microsoft Windows Command Prompt or Windows PowerShell in addition to the Git BASH shell, first ensure that the npm config parameter `script-shell` points to  the Git BASH shell, so that the commands `find `and `xargs` can be executed without error:

```bash
npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe" --location user
```

---
Internal Tracking ID: [EXPOSUREAPP-14537](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14537)

### CODE REVIEW

**Comment by larswmh** [comment]
Thanks for the PR @MikeMcC399.

I was able to verify that this works on macOS and Windows. However, I would suggest to extend the README.md documentation for it with the information that this won't work in Command Prompt or PowerShell on Windows. As a Windows user, these are the default options to go to and it could be confusing for some when this doesn't work. If I remember correctly, this is also the default selection in VSCode.

```
'xargs' is not recognized as an internal or external command,
operable program or batch file.
```

Maybe we can find a working alternative for Windows instead?

**Comment by MikeMcC399** [comment]
@larswmh

Thank you for your comments about using `npm run checklinks` using Windows Command Prompt or PowerShell. It worked for me on Windows 11 Pro 22H2 in these terminal environments. Which version of Windows did you test on? Which version of `npm` are you using?

https://github.com/corona-warn-app/cwa-documentation/blob/main/package.json also provides a very similar command, so adding this to cwa-website would make it a consistent use of tools:

    "checklinks": "find . -not -path \"*node_modules*\" -not -path \"*.github*\" -name \"*.md\" | xargs -n 1 markdown-link-check",

I agree that if we know it doesn't work under certain circumstances, then it would be good to add this information to the README. Let me also check in parallel if I can reproduce the problem which you saw.

**Comment by MikeMcC399** [comment]
@larswmh 

I can reproduce the issue on another Windows 11 machine. I will try to find out why it works on one machine and not on another.

**Comment by larswmh** [comment]
@MikeMcC399 

> Which version of Windows did you test on? Which version of `npm` are you using?

I've tested this on Windows 11 Pro 22H2 (npm version 8.19.2) and Windows 10 Enterprise 2004 (npm version 8.19.3). Updating to the latest npm version 9.2.0 didn't make a difference unfortunately. 

Another thing I've been notified about is that the new package would need to be added to the list in [THIRD-PARTY-NOTICES](https://github.com/corona-warn-app/cwa-website/blob/master/THIRD-PARTY-NOTICES)

Following the format we recently used, I supposed it should look like this:
```
Component: markdown-link-check
Licensor: Thomas Cort
Website: https://www.npmjs.com/package/markdown-link-check
License: ISC
```

**Comment by MikeMcC399** [comment]
@larswmh 

I have added a note that a Unix-type shell needs to be used on Windows:

"The `checklinks` script uses Unix commands. If you run the above command on a Microsoft Windows operating system it is recommended to use a Unix-type shell such as Git Bash available through the [git for Windows download](https://git-scm.com/download/win)."

In fact if Unix commands are not available in the terminal window, the `find` command doesn't work either because it is also a Windows command, and with completely different syntax compared to Unix.

I have read that packages which are only included in the `devDependencies` of package.json do not need to be listed in THIRD-PARTY-NOTICES. I added `markdown-link-check` to this section. Perhaps you could check? Since this is a legal question I take my lead from you and will add the license if you confirm it is necessary.

**Comment by MikeMcC399** [comment]
@larswmh 

We used to have the following text in the README:

"ensure that [git](https://git-scm.com/downloads) is installed and execute the following command:

`npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"`"

I will check if that solves the issue.

**Comment by MikeMcC399** [comment]
@larswmh 

I have updated the README and you can read this conveniently on
https://github.com/MikeMcC399/cwa-website/blob/feat/checklinks/README.md#checking-markdown-documents.

I would be grateful if you could check if 

```bash
npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
```

solves your issue.

I have had this setting for a long time and unfortunately I forgot about it.

Also let me know if I have to add the license information or not.

**Comment by MikeMcC399** [comment]
@larswmh 

> Thanks for the information about the THIRD-PARTY-NOTICES. We have reconsidered this and don't think this needs to be included anymore.

Thank you for the confirmation about the licensing. I will not add anything for that.

> This fixes it, thanks! It creates a .npmrc file though, it would probably be a good idea to add this to the [.gitignore](https://github.com/corona-warn-app/cwa-website/blob/master/.gitignore). What do you think?

I am glad to hear that the command fixes it! Thank you for spotting this problem.

The default location for `.npmrc` after executing the following is in the "user" config:

```bash
npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
```

Where was your `.npmrc` created and what does the following command show you?

```bash
npm config list
```

**Comment by larswmh** [comment]
@MikeMcC399 

> The default location for .npmrc after executing the following is in the "user" config:
> 
> `npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"`
>
> Where was your .npmrc created and what does the following command show you?
> 
> `npm config list`

.npmrc was created at the root of the repository.

image

When running `npm config list`, I'm getting the following result
```
; "builtin" config from C:\Users\Lars\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\Lars\\AppData\\Roaming\\npm"

; "project" config from C:\Users\Lars\Documents\GitHub\cwa-website-main-repository\.npmrc

script-shell = "C:\\Program Files\\git\\bin\\bash.exe"

; "cli" config from command line options

location = "project"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v16.14.2
; npm local prefix = C:\Users\Lars\Documents\GitHub\cwa-website-main-repository
; npm version = 9.2.0
; cwd = C:\Users\Lars\Documents\GitHub\cwa-website-main-repository
; HOME = C:\Users\Lars
; Run `npm config ls -l` to show all defaults.
```

**Comment by MikeMcC399** [comment]
@larswmh 

I will see if I can reproduce your problem.

I notice though that you are not using the recommended [Node.js LTS](https://nodejs.org/en/) version.
The current LTS includes node 18.13.0 and npm v8.19.3.

Are you using [nvm on Windows](https://github.com/coreybutler/nvm-windows)?

**Review by larswmh — APPROVED** [review]
> @larswmh
> 
> I will see if I can reproduce your problem.
> 
> I notice though that you are not using the recommended [Node.js LTS](https://nodejs.org/en/) version. The current LTS includes node 18.13.0 and npm v8.19.3.
> 
> Are you using [nvm on Windows](https://github.com/coreybutler/nvm-windows)?

Yes, I'm using nvm. It comes in handy when working on multiple projects that require different versions. I must've messed something up with it, so I reinstalled everything now. As it now doesn't generate the file I described anymore, this PR should be good now. We appreciate your effort a lot.

**Comment by MikeMcC399** [comment]
@larswmh 

Thank you once again for working together on this PR! Your previous configuration, before you reinstalled, revealed a weakness in the instructions, as it was assuming that the default npm config "user" was not overridden. I have added it explicitly to the command, so it now reads:

```bash
npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe" --location user
```

See npm documentation [npm config: location](https://docs.npmjs.com/cli/v8/commands/npm-config#location) and [npm config](https://docs.npmjs.com/cli/v8/using-npm/config).

I tested this on Git BASH, cmd and PowerShell, so I think it is ready to merge.

**Comment by dsarkar** [comment]
- Tested on Mac: 
  - the order of the tests is different compared to running it on other machines
  - in readme.md 38 links are check, instead of 37 as shown in OP https://github.com/corona-warn-app/cwa-website/pull/3314#issue-1521055929 --> OK, since link was added later
  - Link  https://www.bundesregierung.de/breg-en/federal-government/federal-press-office fails, not sure why, since link works

```
FILE: ./CODE_OF_CONDUCT.md
  [✓] mailto:corona-warn-app.opensource@sap.com
  [✓] https://www.contributor-covenant.org
  [✓] https://www.contributor-covenant.org/version/2/0/code_of_conduct.html
  [✓] https://github.com/mozilla/diversity
  [✓] https://www.contributor-covenant.org/faq
  [✓] https://www.contributor-covenant.org/translations

  6 links checked.

FILE: ./README.md
  [✓] https://www.coronawarn.app/en/
  [✓] https://observatory.mozilla.org/analyze/coronawarn.app
  [✓] #about-this-repository
  [✓] #development
  [✓] #documentation
  [✓] #support-and-feedback
  [✓] #how-to-contribute
  [✓] #licensing
  [✓] https://coronawarn.app
  [✓] https://github.com/corona-warn-app/cwa-documentation
  [✓] https://nodejs.org/en/
  [✓] https://support.apple.com/en-us/HT211861
  [✓] package.json
  [✓] ./docs/
  [✓] https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell
  [✓] https://www.coronawarn.app
  [✓] #getting-started
  [✓] https://docs.cypress.io/guides/guides/command-line#cypress-version
  [✓] https://docs.cypress.io/guides/guides/command-line#cypress-cache-list
  [✓] https://docs.cypress.io/guides/guides/command-line#cypress-cache-prune
  [✓] https://developer.mozilla.org/en-US/docs/Glossary/MIME_type
  [✓] ./blog
  [✓] ./docs
  [✓] https://gitforwindows.org/
  [✓] https://github.com/features/actions
  [✓] .github/workflows
  [✓] https://github.com/corona-warn-app/cwa-website/issues/new/choose
  [✓] mailto:corona-warn-app.opensource@sap.com
  [✓] ./CONTRIBUTING.md
  [✓] ./CODE_OF_CONDUCT.md
  [✓] https://github.com/corona-warn-app/cwa-documentation/blob/main/README.md#repositories
  [✓] https://www.apache.org/licenses/LICENSE-2.0
  [✓] ./LICENSE
  [✖] https://www.bundesregierung.de/breg-en/federal-government/federal-press-office
  [✓] https://raw.githubusercontent.com/corona-warn-app/cwa-documentation/main/images/CWA_title.png
  [✓] https://img.shields.io/mozilla-observatory/grade/coronawarn.app
  [✓] https://img.shields.io/github/issues/corona-warn-app/cwa-website?style=flat-square
  [✓] https://img.shields.io/badge/email-CWA%20team-green?logo=mail.ru&style=flat-square&logoColor=white

  38 links checked.

  ERROR: 1 dead links found!
  [✖] https://www.bundesregierung.de/breg-en/federal-government/federal-press-office → Status: 503

FILE: ./CONTRIBUTING.md
  [✓] CODE_OF_CONDUCT.md
  [✓] mailto:corona-warn-app.opensource@sap.com
  [✓] #steps-to-contribute
  [✓] CODEOWNERS
  [✓] #pull-request-checklist
  [✓] LICENSE
  [✓] https://git-scm.com/downloads/guis/
  [✓] https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
  [✓] https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things
  [✓] https://git-scm.com/book/en/v2/Git-Branching-Rebasing

  10 links checked.

FILE: ./SECURITY.md
  [✓] mailto:corona-warn-app.opensource@sap.com
  [✓] https://www.sap.com/about/trust-center/security/incident-management.html
  [✓] https://github.com/corona-warn-app/cwa-website/releases

  3 links checked.

FILE: docs/FAQ_SEARCH_SUMMARY.md
  [✓] ../gulpfile.mjs
  [✓] ../src/data/faq.json
  [✓] ../src/data/faq_de.json
  [✓] ../src/assets/js/app.js

  4 links checked.

FILE: docs/CREATE_BLOG_REDIRECTS.md
  [✓] ../blog/2020-08-11-hinweise-qr-code/index.md

  1 links checked.

FILE: docs/CHANGE_WEBSITE_CONTENT.md
  [✓] https://github.com/foundation/panini
  [✓] ../src/pages/
  [✓] ../src/layouts/
  [✓] ../src/partials/
  [✓] ../src/data/
  [✓] https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq.json
  [✓] https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq_de.json

  7 links checked.

FILE: docs/WRITE_BLOG_POSTS.md
  [✓] https://getbootstrap.com/docs/4.0/content/images/#aligning-images
  [✓] https://raw.githubusercontent.com/corona-warn-app/cwa-documentation/main/images/CWA_title.png

  2 links checked.
00qq:cwa-website ds$ npm run checklinks

> corona-warn-app-landingpage@1.3.0 checklinks
> find . docs -maxdepth 1 -name '*.md' -print0 | xargs -0 -n1 markdown-link-check


FILE: ./CODE_OF_CONDUCT.md
  [✓] mailto:corona-warn-app.opensource@sap.com
  [✓] https://www.contributor-covenant.org
  [✓] https://www.contributor-covenant.org/version/2/0/code_of_conduct.html
  [✓] https://github.com/mozilla/diversity
  [✓] https://www.contributor-covenant.org/faq
  [✓] https://www.contributor-covenant.org/translations

  6 links checked.

FILE: ./README.md
  [✓] https://www.coronawarn.app/en/
  [✓] https://observatory.mozilla.org/analyze/coronawarn.app
  [✓] #about-this-repository
  [✓] #development
  [✓] #documentation
  [✓] #support-and-feedback
  [✓] #how-to-contribute
  [✓] #licensing
  [✓] https://coronawarn.app
  [✓] https://github.com/corona-warn-app/cwa-documentation
  [✓] https://nodejs.org/en/
  [✓] https://support.apple.com/en-us/HT211861
  [✓] package.json
  [✓] ./docs/
  [✓] https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell
  [✓] https://www.coronawarn.app
  [✓] #getting-started
  [✓] https://docs.cypress.io/guides/guides/command-line#cypress-version
  [✓] https://docs.cypress.io/guides/guides/command-line#cypress-cache-list
  [✓] https://docs.cypress.io/guides/guides/command-line#cypress-cache-prune
  [✓] https://developer.mozilla.org/en-US/docs/Glossary/MIME_type
  [✓] ./blog
  [✓] ./docs
  [✓] https://gitforwindows.org/
  [✓] https://github.com/features/actions
  [✓] .github/workflows
  [✓] https://github.com/corona-warn-app/cwa-website/issues/new/choose
  [✓] mailto:corona-warn-app.opensource@sap.com
  [✓] ./CONTRIBUTING.md
  [✓] ./CODE_OF_CONDUCT.md
  [✓] https://github.com/corona-warn-app/cwa-documentation/blob/main/README.md#repositories
  [✓] https://www.apache.org/licenses/LICENSE-2.0
  [✓] ./LICENSE
  [✖] https://www.bundesregierung.de/breg-en/federal-government/federal-press-office
  [✓] https://raw.githubusercontent.com/corona-warn-app/cwa-documentation/main/images/CWA_title.png
  [✓] https://img.shields.io/mozilla-observatory/grade/coronawarn.app
  [✓] https://img.shields.io/github/issues/corona-warn-app/cwa-website?style=flat-square
  [✓] https://img.shields.io/badge/email-CWA%20team-green?logo=mail.ru&style=flat-square&logoColor=white

  38 links checked.

  ERROR: 1 dead links found!
  [✖] https://www.bundesregierung.de/breg-en/federal-government/federal-press-office → Status: 503

FILE: ./CONTRIBUTING.md
  [✓] CODE_OF_CONDUCT.md
  [✓] mailto:corona-warn-app.opensource@sap.com
  [✓] #steps-to-contribute
  [✓] CODEOWNERS
  [✓] #pull-request-checklist
  [✓] LICENSE
  [✓] https://git-scm.com/downloads/guis/
  [✓] https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
  [✓] https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things
  [✓] https://git-scm.com/book/en/v2/Git-Branching-Rebasing

  10 links checked.

FILE: ./SECURITY.md
  [✓] mailto:corona-warn-app.opensource@sap.com
  [✓] https://www.sap.com/about/trust-center/security/incident-management.html
  [✓] https://github.com/corona-warn-app/cwa-website/releases

  3 links checked.

FILE: docs/FAQ_SEARCH_SUMMARY.md
  [✓] ../gulpfile.mjs
  [✓] ../src/data/faq.json
  [✓] ../src/data/faq_de.json
  [✓] ../src/assets/js/app.js

  4 links checked.

FILE: docs/CREATE_BLOG_REDIRECTS.md
  [✓] ../blog/2020-08-11-hinweise-qr-code/index.md

  1 links checked.

FILE: docs/CHANGE_WEBSITE_CONTENT.md
  [✓] https://github.com/foundation/panini
  [✓] ../src/pages/
  [✓] ../src/layouts/
  [✓] ../src/partials/
  [✓] ../src/data/
  [✓] https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq.json
  [✓] https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq_de.json

  7 links checked.

FILE: docs/WRITE_BLOG_POSTS.md
  [✓] https://getbootstrap.com/docs/4.0/content/images/#aligning-images
  [✓] https://raw.githubusercontent.com/corona-warn-app/cwa-documentation/main/images/CWA_title.png

  2 links checked.
  ```

**Comment by MikeMcC399** [comment]
@larswmh / @dsarkar 

Thanks for the tests! I will take  

 [✖] https://www.bundesregierung.de/breg-en/federal-government/federal-press-office → Status: 503

out of the test. 

- This website has been problematic in the past (see also https://github.com/corona-warn-app/cwa-documentation/pull/847) because they have enhanced security and it does not like being tested automatically.

**Comment by MikeMcC399** [comment]
Added  the following to README

```text
<!-- The website of the Bundesregierung has implemented additional security which causes a 503 error (service unavailable) when any link on their site is tested automatically. -->
<!-- markdown-link-check-disable-next-line -->
```

directly before:

"The "Corona-Warn-App" logo is a registered trademark of The Press and Information Office of the Federal Government. For more information please see [bundesregierung.de](https://www.bundesregierung.de/breg-en/federal-government/federal-press-office)."

**Review by dsarkar — APPROVED** [review]

**Pull request merged**
