### PR TITLE
Multiple issues for links in FAQ #mask_rules

### LINKED ISSUE #3150: Multiple issues for links in FAQ #mask_rules
## Where to find the issue

Links in 
- https://www.coronawarn.app/en/faq/results/#mask_rules "Mask Feature"
- https://www.coronawarn.app/de/faq/results/#mask_rules "Maskenpflicht / Maskenpflichtbefreiung"

specifically:

- https://www.bundesregierung.de/breg-de/themen/coronavirus/infektionsschutzgesetz-2068856
- https://www.bundesgesundheitsministerium.de/coronavirus.html#c23063
- [https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#\_\_bgbl\_\_%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187](https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187)

### Link relevance

1. The content of the link https://www.bundesgesundheitsministerium.de/coronavirus.html#c23063 has changed since the [#mask_rules](https://www.coronawarn.app/en/faq/results/#mask_rules) FAQ was published on Sep 23, 2022. https://web.archive.org/web/20220925053332/https://www.bundesgesundheitsministerium.de/coronavirus.html#c23063 shows that the contents were previously relevant, however this link contains dynamic content and today the link points to "Aktuelles / 14.10.2022 / Lauterbach startet Corona-Kampagne „Ich schütze mich“" which is about ensuring vaccination protection, not primarily about mask wearing. The link no longer helps to understand the FAQ article. 

2. [https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#\_\_bgbl\_\_%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187](https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187) points to "Gesetz zur Stärkung des Schutzes der Bevölkerung und insbesondere vulnerabler Personengruppen vor COVID-19". Most of the text concerns changes to the Infektionsschutzgesetz (IfSG), so citing this law is redundant to the link https://www.bundesregierung.de/breg-de/themen/coronavirus/infektionsschutzgesetz-2068856 which already covers the changes to IfSG relating to masks in a readable way. The actual text changes are covered in IfSG [§ 28a](https://www.gesetze-im-internet.de/ifsg/__28a.html), [§ 28b](https://www.gesetze-im-internet.de/ifsg/__28b.html) & [§ 28c](https://www.gesetze-im-internet.de/ifsg/__28c.html). The link to [Bundesgesetzblatt Teil I, 2022, Nr. 32 vom 16.09.2022 Seite 1454](https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187) is factually correct, however it is very unhelpful for a lay-reader, since the relevant information about mask wearing is buried in other irrelevant legal text.

### Link presentation

1. Other lists of links on the FAQ page are presented as an HTML unordered list, so that a bullet point shows before each entry. This has not been done for this list of links, instead the links are separated only by a new line `<br>`.
   
2. The page URLs are used as the link description. Link best practice in https://web.dev/link-text/#link-text-best-practices says:<br><br>"Don't use the page's URL as the link description unless you have a good reason to do so, such as referencing a site's new address."

### Link security

Each of the links is using the `target='_blank'` attribute without specifying a `rel` attribute.

[Links on FAQ pages](https://github.com/corona-warn-app/cwa-website/blob/master/docs/CHANGE_WEBSITE_CONTENT.md#links-on-faq-pages) says:

"External links should use the HTML hyperlink attribute `rel='noopener noreferrer'` to avoid a cross-domain security issue in older browsers when the link also contains `target='_blank'`."

## Suggestion

Review the links.

Possibly the links:
- https://www.bundesgesundheitsministerium.de/coronavirus.html#c23063
- [https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#\_\_bgbl\_\_%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187](https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187)

could be removed without loss of understanding for the FAQ article.

- For https://www.bundesregierung.de/breg-de/themen/coronavirus/infektionsschutzgesetz-2068856 
change the link description to "Corona-Schutzmaßnahmen – was ab Oktober 2022 gilt", add `rel='noopener noreferrer'`

Similarly if the other links are kept then add an appropriate link description and the `rel` attribute.

If multiple links are kept, then change the presentation to an unordered list.

---
Internal Tracking ID: [EXPOSUREAPP-14165](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14165)

### PR DESCRIPTION
**Pull request by brianebeling**
Fixes #3150

Todos
- [ ] Set aktualisiert am/update to date of merge
- [ ] Run tests after initial approval

Changes are highlighted by the red line.

EN:
image

DE:
image

---
Internal Tracking ID: [EXPOSUREAPP-14165](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14165)

### CODE REVIEW

**Comment by brianebeling** [comment]
The Quellen / Sources are a list, even though its only one item. I think that fits the purpose of a list of sources better. In case there will be more. If we decide to go with only one source, we could also display it as:

Source: Corona Schutzmaßnahmen (...)

**Comment by MikeMcC399** [comment]
@brianebeling 

- You have addressed all the points I raised in issue #3150. Many thanks!

**Comment by brianebeling** [comment]
> @brianebeling 
> 
> - You have addressed all the points I raised in issue #3150. Many thanks!

Thank you for the great summary! In an optimal world, sources shouldn't change in the first place, that was a really good find.

**Comment by MikeMcC399** [comment]
@brianebeling 

When you update the publication date, please make sure that there is no dot in the English date. "Update on 28. September 2022" is wrongly formatted. It should have been "Update on 28 September 2022".

There has unfortunately been no standard in the FAQs about how to write the update text and date. In most of the FAQs it is written like "Updated, September 28, 2022".

**Review by GisoSchroederSAP — APPROVED** [review]
Smooth changes, approved.

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reviewing and suggestions, for the moment we have put the link to COVID-19-Schutzgesetz back, since we want to show the original sources. We might find a later a better solution; it is true that it difficult to read this document.

**Pull request merged**
