### PR TITLE
Update Datenschutz-Folgenabschätzung (DSFA)

### PR DESCRIPTION
**Pull request by brianebeling**
Internal Tracking ID: [EXPOSUREAPP-14362](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14362)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@brianebeling 

- The 2.00 version of the DSFA refers to newer versions of the "Anlagen" on the last page. These would also need to be updated.

- Anlage 9 "Glossar" is missing (also for the current version) and would need to be provided for completeness.

- Version 2.00 of the DSFA covers the CWA app up to version 2.25, released in July 2022. It does not cover the current version 2.28.

**Comment by brianebeling** [comment]
> Brian-J. Ebeling
> 
> * The 2.00 version of the DSFA refers to newer versions of the "Anlagen" on the last page. These would also need to be updated.
> * Anlage 9 "Glossar" is missing (also for the current version) and would need to be provided for completeness.
> * Version 2.00 of the DSFA covers the CWA app up to version 2.25, released in July 2022. It does not cover the current version 2.28.

Hey Mike, I currently do not seem to have access to the Anlagen and will have to double check those. I should have mentioned this in the PR and left it as a draft. As for the coverage, this is the most up to date document and the one I was tasked with integrating.

As for Anlage 9, that may actually be missing. I will take it to the devs, thanks!

**Comment by MikeMcC399** [comment]
@brianebeling 

Hi Brian, 
No worries. Getting updates or corrections made for this document has been very slow in the past, so I am not surprised here.

If you have problems getting updated attachments for the DSFA document I would tend not to wait and just publish the main PDF as is.

**Comment by MikeMcC399** [comment]
@brianebeling 

There is a letter "n" missing in the "folgeabschätzung" in the title of this PR.  "Datenschutz-Folgenabschätzung" is the name in the document. (In full: "Bericht zur Datenschutz-Folgenabschätzung für die Corona-Warn-App der Bundesrepublik Deutschland Öffentliche Version".)

**Comment by brianebeling** [comment]
This PR is currently on hold, will be resumed shortly

**Comment by brianebeling** [comment]
Update:
- [ ] Anlage 1
- [ ] Anlage 3
- [ ] Anlage 8

Anlage 9 will not be published right now. After updating Anlage 1, 3 and 8 this PR is good to go.

**Comment by Ein-Tim** [comment]
The `on hold` label could be applied to this PR.

**Comment by brianebeling** [comment]
> The `on hold` label could be applied to this PR.

Actually it was only on hold for an hour. I expcted further delay, but issues were resolved. So now I'm updating the Anlagen. 
Thanks for the headsup!

**Review by mtb77 — APPROVED** [review]

**Pull request merged**
