### PR TITLE
Add new page for QR code creation instructions

### PR DESCRIPTION
**Pull request by larswmh**
Due to the need of an instruction that's easy to understand for everyone, here's the pull request to implement a new page that includes a step by step guide on how to create QR code(s)

German:
chrome_eKakiam3uQ
chrome_nHsvuaxgZu
chrome_kj5XTFHtWV
chrome_GSyXM2NKfZ
chrome_o0X0j6Ydkl
chrome_3HYl5ZWlfT
chrome_bm1993FB6r
chrome_NOIWn1dRMf

English:
chrome_epTVRiEc4m
chrome_WinO87ddpE
chrome_rC0bsdLXpl
chrome_Dh6nTJfLcV
chrome_MCZMNrq8BV
chrome_FCC4RhRxZq
chrome_YKVKvS7iJV
chrome_ppq9Q8e5Rq

---
Internal Tracking ID: [EXPOSUREAPP-8494](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8494)

### CODE REVIEW

**Comment by Ein-Tim** [comment]
If this instructions only apply to windows machines, this should be made clear in the headline.

**Comment by dsarkar** [comment]
@Ein-Tim Right. Mac OS X (Linux should be similar) will follow in the next step.

**Comment by larswmh** [comment]
@Ein-Tim As the guides for other operating systems are supposed to follow soon, I don't think a specification in the headline is needed, especially since people can tell by the first step's headline that it only describes the Windows way right now. I'll happily update the page as soon as I get the information for other operating systems, and will then add hyperlinks at the top to quickly get to the different operating system's descriptions and the tables.

**Comment by Ein-Tim** [comment]
@larswmh 

For sure! Agreed! I checked the page and it LGTM!

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@larswmh @Ein-Tim Thanks!

**Pull request merged**
