### PR TITLE
Update FAQ #international: Remove paragraph about expansion to other countries

### PR DESCRIPTION
**Pull request by larswmh**
This PR removes

> Weitere Länder werden im Moment geprüft und schrittweise in den App Stores freigegeben. Das Robert Koch-Institut bittet um Verständnis, dass es während des laufenden Überprüfungsprozesses zu konkreten Ländern und dem Status ihrer Freigabe keine Auskunft erteilen kann.

or

> More countries are currently being checked and will be released in the App Stores step by step. The Robert Koch Institute asks for your understanding that it cannot provide any information on specific countries and the status of their release during the ongoing review process.

from the FAQ [#international](https://www.coronawarn.app/en/faq/results/#international). As brought up in #2711, the list has been stable and not been extended for a long time, therefore the wording does not fit current actions.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Please check also the rest of the text for consistency, such as 

"Nach eingehender Prüfung der Situation wurde festgestellt, dass eine Veröffentlichung der Corona-Warn-App in App Stores außerhalb von Deutschland im Moment aus rechtlichen Gründen nur nach einer Einzelfallprüfung möglich ist."

where "im Moment" seems to be outdated, and should be removed. ("currently" in English version as well.)

**Review by GisoSchroederSAP — APPROVED** [review]
Removal of outdated phrases; approved

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reviewing.

**Comment by MikeMcC399** [comment]
@dsarkar 
> Thanks for reviewing.

I had some more detailed comments, however the PR was merged too fast for me to add them. I'm going to leave it at that now, as I don't want to make more work for just very minor points. The major misleading elements have been removed.

Thanks!

**Comment by dsarkar** [comment]
@MikeMcC399 ok, thank you for all the effort! Sorry for merging to fast... , will try to leave PRs open for a bit longer.

**Pull request merged**
