### PR TITLE
Merge FAQ entries `risk_encounter_different_devices` & `dissimilar_indication_of_risk_status` (Addresses #2536)

### LINKED ISSUE #2536: Merge FAQ entries `risk_encounter_different_devices` & `dissimilar_indication_of_risk_status`
## Where to find the issue
- https://www.coronawarn.app/de/faq/#risk_encounter_different_devices
- https://www.coronawarn.app/en/faq/#risk_encounter_different_devices
- https://www.coronawarn.app/de/faq/#dissimilar_indication_of_risk_status
- https://www.coronawarn.app/en/faq/#dissimilar_indication_of_risk_status

## Describe the issue
The FAQ entries mentioned above cover exactly the same & answer the same question. They should be merged.

## Suggested change
Remove `dissimilar_indication_of_risk_status`, as it does not give any information which `risk_encounter_different_devices` does not give. 
Add a FAQ redirect from `dissimilar_indication_of_risk_status` to `risk_encounter_different_devices`.

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description

This PR removes the FAQ entry `risk_encounter_different_devices` & adds a redirect to the FAQ entry `dissimilar_indication_of_risk_status` instead.

## What was changed

- https://www.coronawarn.app/de/faq/#risk_encounter_different_devices was deleted
- https://www.coronawarn.app/en/faq/#risk_encounter_different_devices was deleted 
- A FAQ redirect from `risk_encounter_different_devices` to `dissimilar_indication_of_risk_status` was added

## Screenshots

Nothing to see here, move along.

---

Follow up to  #2673.

**Fixes #2536**

### CODE REVIEW

**Comment by Ein-Tim** [comment]
https://github.com/corona-warn-app/cwa-website/pull/2674/commits/0bfb9dc704e717d0c4884904da1ddc6b57da0aee resolved merge conflicts. 
PR is ready to merge.

**Comment by Ein-Tim** [comment]
@dsarkar Is something blocking the merge of this PR? I'm just wondering because other PRs are merged as normal, even if they were just provided today.

**Comment by dsarkar** [comment]
@Ein-Tim Nothing blocking it, will have a closer look.

**Review by dsarkar — APPROVED** [review]

**Comment by dsarkar** [comment]
@Ein-Tim LGTM. One small thing: In our OP is says:

> A FAQ redirect from risk_encounter_different_devices to dissimilar_indication_of_risk_status was added

It's the other way around... ;-)

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar I fixed the OP, sorry.

**Pull request merged**
